/**
 * GENERATED by `scripts/capture-ui-stills.mjs` — do not edit by hand.
 *
 * Why a generated module instead of letting the browser find out:
 *
 * The stills live in `public/`, so nothing in the bundle can know at render time
 * whether a capture actually produced a file. Before this module existed, a
 * still that had never been captured (the admin ones need a signed-in session,
 * and this project has no auth users yet) still rendered a `<picture>`, so every
 * marketing route fired an AVIF/WebP/PNG request that 404'd and only *then* fell
 * back through `onError`. That is the "intermittent 404 asset request" seen
 * across routes: three wasted requests, a console error, and a fallback frame
 * that arrives one paint late.
 *
 * The capture script writes the ids whose full format set exists on disk, so
 * `UiStill` can render the honest fallback frame immediately and issue no
 * request at all. No placeholder image is ever written to disk — a placeholder
 * on disk is indistinguishable from a real capture.
 *
 * Regenerate with `bun run assets:stills`.
 */
export const CAPTURED_STILLS: readonly string[] = ["storefront-mobile"];

/** True when every declared format for `id` exists in `public/media/stills`. */
export function stillCaptured(id: string): boolean {
  return CAPTURED_STILLS.includes(id);
}
