/**
 * বাংলা twins for every string authored in the blueprint presets.
 *
 * `sectionFactory(BLUEPRINT_BN)` fills the বাংলা side of each bilingual prop at
 * construction time, so a blueprint can never ship half-translated copy and the
 * publish gate (≥90% coverage) stays green.
 */
export const BLUEPRINT_BN: Record<string, string> = {
  "Search results": "সার্চ ফলাফল",
  /* ---------------------------------------------------- atelier · chrome */
  "Free size exchange within 7 days": "৭ দিনের মধ্যে ফ্রি সাইজ বদল",
  "New season drop is live": "নতুন সিজনের ড্রপ চালু হয়েছে",
  "Free delivery over BDT 2,000": "২,০০০ টাকার বেশি অর্ডারে ফ্রি ডেলিভারি",
  "Studio pickup available in Dhanmondi": "ধানমন্ডি স্টুডিও থেকে পিকআপ করা যাবে",
  "Size guide": "সাইজ গাইড",
  Exchanges: "বদল ও ফেরত",
  "Contact us": "যোগাযোগ করুন",
  "Search the collection": "কালেকশনে খুঁজুন",
  Search: "খুঁজুন",
  Collections: "কালেকশন",
  Shop: "শপ",
  Help: "সহায়তা",
  Studio: "স্টুডিও",
  Legal: "লিগ্যাল",
  "Ways to pay": "পেমেন্টের উপায়",
  "Follow the studio": "স্টুডিও ফলো করুন",
  "About this store": "এই স্টোর সম্পর্কে",
  "Small-batch clothing cut and finished in Dhaka, photographed on real bodies.":
    "ঢাকায় ছোট ব্যাচে কাটা ও ফিনিশ করা পোশাক, সত্যিকারের মানুষের গায়ে ছবি তোলা।",

  /* ------------------------------------------------------ atelier · home */
  "Season 04": "সিজন ০৪",
  "Cut for the way you live": "আপনার জীবনযাত্রার জন্য কাটা",
  "Limited runs, natural fibres, honest photography.":
    "সীমিত সংখ্যায় তৈরি, প্রাকৃতিক সুতা, সৎ ফটোগ্রাফি।",
  "Shop the edit": "এডিট দেখুন",
  "The lookbook": "লুকবুক",
  "The fabric": "কাপড়",
  "Handloom cotton, woven in Tangail": "টাঙ্গাইলে বোনা হ্যান্ডলুম কটন",
  "Breathable in humidity, softer with every wash.":
    "আর্দ্রতায় আরামদায়ক, প্রতিবার ধোয়ার পর আরও নরম।",
  "Read the story": "গল্পটি পড়ুন",
  Collection: "কালেকশন",
  "Everyday tailoring": "প্রতিদিনের টেইলারিং",
  "Twelve pieces that work from office to iftar.":
    "অফিস থেকে ইফতার—সব জায়গায় মানানসই বারোটি পিস।",
  "See the collection": "কালেকশন দেখুন",
  "Shop the look": "লুকটি কিনুন",
  "Worn by you": "আপনাদের পরা",
  "Tag us to be featured.": "ফিচার হতে আমাদের ট্যাগ করুন।",
  "This season": "এই সিজন",
  "The fit is exactly what the size chart promised.":
    "সাইজ চার্টে যা লেখা ছিল, ফিট ঠিক তেমনই।",
  "Verified buyer, Dhaka": "ভেরিফায়েড ক্রেতা, ঢাকা",

  /* ------------------------------------------------- atelier · sustainability */
  "Made responsibly": "দায়িত্ব নিয়ে তৈরি",
  "Local workshops": "স্থানীয় কারখানা",
  "Supplier list, 2026": "সরবরাহকারী তালিকা, ২০২৬",
  "Low-waste cutting": "কম অপচয়ে কাটিং",
  "Production audit, 2026": "উৎপাদন অডিট, ২০২৬",
  "Recycled packaging": "রিসাইকেলড প্যাকেজিং",
  "Packaging spec, 2026": "প্যাকেজিং স্পেক, ২০২৬",

  /* ------------------------------------------------------- atelier · PDP */
  "Select a size": "সাইজ বেছে নিন",
  "Notify me": "জানিয়ে দিন",
  "Open size guide": "সাইজ গাইড খুলুন",
  Chest: "বুক",
  Waist: "কোমর",
  Length: "লম্বা",
  "Measurements are of the garment, laid flat.":
    "মাপগুলো পোশাকের, সমতলে বিছিয়ে নেওয়া।",
  "Relaxed through the shoulder.": "কাঁধে একটু ঢিলেঢালা।",
  "Model is 175cm": "মডেলের উচ্চতা ১৭৫ সেমি",
  "Wearing size M": "পরেছেন সাইজ M",
  "Save for later": "পরে দেখার জন্য রাখুন",
  Saved: "সংরক্ষিত",
  "Sold out in your size?": "আপনার সাইজ শেষ?",
  "We will email you when it returns.": "স্টকে ফিরলে আমরা ইমেইল করব।",
  "I agree to receive one restock email.":
    "একটি রিস্টক ইমেইল পেতে আমি সম্মত।",
  "Fabric and care": "কাপড় ও যত্ন",
  "100% handloom cotton": "১০০% হ্যান্ডলুম কটন",
  "Cold hand wash, dry in shade": "ঠান্ডা পানিতে হাতে ধুয়ে ছায়ায় শুকান",
  "Cut and sewn in Dhaka": "ঢাকায় কাটা ও সেলাই করা",
  "Complete the look": "লুকটি পূর্ণ করুন",
  "Add the look": "পুরো লুক যোগ করুন",
  "Customer reviews": "ক্রেতাদের রিভিউ",
  "No reviews yet.": "এখনও কোনো রিভিউ নেই।",
  "You may also like": "আপনার পছন্দ হতে পারে",
  "Add to bag": "ব্যাগে যোগ করুন",
  "VAT included where applicable.": "প্রযোজ্য ক্ষেত্রে ভ্যাট অন্তর্ভুক্ত।",

  /* ------------------------------------------------ atelier · collection */
  "The collection": "কালেকশন",
  "Filter by size, fabric and price.": "সাইজ, কাপড় ও দাম দিয়ে ফিল্টার করুন।",
  Home: "হোম",
  "Clear all": "সব মুছুন",
  "No filters applied.": "কোনো ফিল্টার দেওয়া হয়নি।",
  Filters: "ফিল্টার",
  Category: "ক্যাটাগরি",
  Type: "ধরন",
  Price: "দাম",
  Availability: "স্টক",
  "In stock only": "শুধু স্টকে আছে",
  pieces: "পিস",
  Sort: "সাজান",
  "All pieces": "সব পিস",
  "Load more": "আরও দেখুন",
  Previous: "পূর্ববর্তী",
  Next: "পরবর্তী",
  Page: "পেজ",
  "Nothing matches those filters": "এই ফিল্টারে কিছু মেলেনি",
  "Try removing a filter or two.": "একটি-দুটি ফিল্টার সরিয়ে দেখুন।",

  /* ----------------------------------------------- atelier · page / blog */
  "Visit the studio": "স্টুডিওতে আসুন",
  "Dhanmondi studio": "ধানমন্ডি স্টুডিও",
  "Road 8, Dhanmondi, Dhaka": "রোড ৮, ধানমন্ডি, ঢাকা",
  "11am - 8pm": "সকাল ১১টা - রাত ৮টা",
  "Gulshan counter": "গুলশান কাউন্টার",
  "Gulshan 2, Dhaka": "গুলশান ২, ঢাকা",
  "Behind the seam": "সেলাইয়ের পেছনে",
  "Meet the makers": "কারিগরদের সাথে পরিচয়",
  "The families who cut and finish every run.":
    "যে পরিবারগুলো প্রতিটি রান কাটে ও ফিনিশ করে।",
  "Get the next post": "পরের লেখাটি পান",
  "One email when we publish. No spam.":
    "প্রকাশ হলে একটি ইমেইল। কোনো স্প্যাম নয়।",
  Subscribe: "সাবস্ক্রাইব",

  /* -------------------------------------------- atelier · cart, checkout */
  Add: "যোগ করুন",
  "more for free delivery": "আরও যোগ করলে ফ্রি ডেলিভারি",
  "Free delivery unlocked": "ফ্রি ডেলিভারি চালু হয়েছে",
  "Order summary": "অর্ডার সারসংক্ষেপ",
  "Your bag": "আপনার ব্যাগ",
  "Shipping and COD charges are calculated at checkout.":
    "শিপিং ও ক্যাশ অন ডেলিভারি চার্জ চেকআউটে হিসাব হবে।",
  "Add something else": "আরও কিছু যোগ করুন",
  "Secure checkout": "নিরাপদ চেকআউট",
  Payment: "পেমেন্ট",
  "Payments are processed server-side.": "পেমেন্ট সার্ভারেই প্রসেস হয়।",
  "No payment method is enabled yet.": "এখনও কোনো পেমেন্ট মাধ্যম চালু নেই।",
  Checkout: "চেকআউট",
  Bag: "ব্যাগ",
  Address: "ঠিকানা",
  Done: "সম্পন্ন",
  Delivery: "ডেলিভারি",
  "Inside Dhaka": "ঢাকার ভেতরে",
  "1-2 days": "১-২ দিন",
  "Outside Dhaka": "ঢাকার বাইরে",
  "2-4 days": "২-৪ দিন",
  "Courier charge shown at checkout.": "কুরিয়ার চার্জ চেকআউটে দেখানো হবে।",
  "Free size exchange": "ফ্রি সাইজ বদল",
  "bKash / Nagad": "বিকাশ / নগদ",
  "Nationwide courier": "সারাদেশে কুরিয়ার",

  /* ---------------------------------------------------- bazaar · chrome */
  "Cash on delivery across 64 districts": "৬৪ জেলায় ক্যাশ অন ডেলিভারি",
  "7-day easy returns": "৭ দিনের সহজ রিটার্ন",
  "Order before 6pm for same-day dispatch": "সন্ধ্যা ৬টার আগে অর্ডার করলে একই দিনে ডিসপ্যাচ",
  "Track order": "অর্ডার ট্র্যাক করুন",
  "Help centre": "হেল্প সেন্টার",
  "Sell with us": "আমাদের সাথে বিক্রি করুন",
  "Search millions of products": "লাখো পণ্যের মধ্যে খুঁজুন",
  "All departments": "সব ডিপার্টমেন্ট",
  Account: "অ্যাকাউন্ট",
  Cart: "কার্ট",

  /* ------------------------------------------------------ bazaar · home */
  "Everything, from every seller": "সব বিক্রেতার সব পণ্য",
  "Millions of products, one trusted checkout.": "লাখো পণ্য, একটি নির্ভরযোগ্য চেকআউট।",
  "Shop deals": "ডিল দেখুন",
  "Shop by department": "ডিপার্টমেন্ট অনুযায়ী কিনুন",
  "Deals of the day": "আজকের ডিল",
  Deal: "ডিল",
  "Flash deal": "ফ্ল্যাশ ডিল",
  "Ends soon": "শীঘ্রই শেষ",
  "Grab it": "এখনই নিন",
  "Best sellers this week": "এই সপ্তাহের সেরা বিক্রি",
  "Delivered in 1-3 days": "১-৩ দিনে ডেলিভারি",
  Sponsored: "স্পনসরড",
  "Top brands": "শীর্ষ ব্র্যান্ড",
  "Trending in electronics": "ইলেকট্রনিকসে জনপ্রিয়",
  "Popular categories": "জনপ্রিয় ক্যাটাগরি",
  "Recommended for you": "আপনার জন্য প্রস্তাবিত",
  "Cash on delivery": "ক্যাশ অন ডেলিভারি",
  "Pay when the courier hands it over.": "কুরিয়ার পণ্য বুঝিয়ে দিলে টাকা দিন।",
  "7-day returns": "৭ দিনের রিটার্ন",
  "Unused items, no questions asked.": "অব্যবহৃত পণ্য, কোনো প্রশ্ন ছাড়াই।",
  "Verified sellers": "যাচাই করা বিক্রেতা",
  "Every seller is trade-licence checked.": "প্রতিটি বিক্রেতার ট্রেড লাইসেন্স যাচাই করা।",
  "64 districts, tracked end to end.": "৬৪ জেলায়, শুরু থেকে শেষ পর্যন্ত ট্র্যাকিং।",

  /* ---------------------------------------------------- bazaar · footer */
  Sellers: "বিক্রেতা",
  About: "আমাদের সম্পর্কে",
  "Need a hand?": "সাহায্য দরকার?",
  "Track your order": "আপনার অর্ডার ট্র্যাক করুন",
  "Live courier status.": "লাইভ কুরিয়ার স্ট্যাটাস।",
  Returns: "রিটার্ন",
  "Start a return in a minute.": "এক মিনিটেই রিটার্ন শুরু করুন।",
  Payments: "পেমেন্ট",
  "bKash, Nagad, Rocket and cards.": "বিকাশ, নগদ, রকেট ও কার্ড।",
  "Talk to us": "আমাদের সাথে কথা বলুন",
  "Every day, 9am to 9pm.": "প্রতিদিন সকাল ৯টা থেকে রাত ৯টা।",
  "Follow the marketplace": "মার্কেটপ্লেস ফলো করুন",
  "A marketplace of verified local sellers with one checkout and one return policy.":
    "যাচাই করা স্থানীয় বিক্রেতাদের মার্কেটপ্লেস — একটি চেকআউট, একটি রিটার্ন নীতি।",

  /* ------------------------------------------------------- bazaar · pdp */
  "Choose an option": "একটি অপশন বাছুন",
  Variant: "ভ্যারিয়েন্ট",
  "Add to cart": "কার্টে যোগ করুন",
  "Sold and shipped by the seller.": "বিক্রেতাই বিক্রি ও পাঠায়।",
  "Order before 6pm": "সন্ধ্যা ৬টার আগে অর্ডার করুন",
  "Dhaka Trade House": "ঢাকা ট্রেড হাউস",
  "Verified seller since 2021": "২০২১ সাল থেকে যাচাই করা বিক্রেতা",
  "7-day returns on unused items.": "অব্যবহৃত পণ্যে ৭ দিনের রিটার্ন।",
  "View seller": "বিক্রেতা দেখুন",
  Specifications: "স্পেসিফিকেশন",
  Detail: "বিবরণ",
  Description: "বর্ণনা",
  "Full product description from the seller.": "বিক্রেতার দেওয়া পূর্ণ পণ্য বর্ণনা।",
  "Return within 7 days in unused condition.": "অব্যবহৃত অবস্থায় ৭ দিনের মধ্যে ফেরত দিন।",
  Warranty: "ওয়ারেন্টি",
  "Warranty terms are listed on the invoice.": "ওয়ারেন্টির শর্ত ইনভয়েসে দেওয়া আছে।",
  Ratings: "রেটিং",
  "Questions and answers": "প্রশ্ন ও উত্তর",
  "Ask a question": "প্রশ্ন করুন",

  /* ------------------------------------- bazaar · collection, track, page */
  "Browse the department": "ডিপার্টমেন্ট ঘুরে দেখুন",
  "Filter by brand, price and delivery speed.": "ব্র্যান্ড, দাম ও ডেলিভারির সময় দিয়ে ফিল্টার করুন।",
  results: "ফলাফল",
  "All products": "সব পণ্য",
  "Order placed": "অর্ডার হয়েছে",
  Packed: "প্যাক হয়েছে",
  "With courier": "কুরিয়ারে",
  Delivered: "ডেলিভারি হয়েছে",
  "Updates arrive by SMS.": "আপডেট এসএমএসে আসবে।",
  "Common questions": "সাধারণ প্রশ্ন",
  "How long does delivery take?": "ডেলিভারিতে কত সময় লাগে?",
  "Inside Dhaka 1-2 working days, outside Dhaka 2-4 working days.":
    "ঢাকার ভেতরে ১-২ কর্মদিবস, ঢাকার বাইরে ২-৪ কর্মদিবস।",
  "Can I return an item?": "পণ্য কি ফেরত দেওয়া যায়?",
  "Yes, within 7 days of delivery in unused condition.":
    "হ্যাঁ, ডেলিভারির ৭ দিনের মধ্যে অব্যবহৃত অবস্থায়।",
  "Which payments do you accept?": "কোন কোন পেমেন্ট নেওয়া হয়?",
  "Cash on delivery, bKash, Nagad and Rocket.": "ক্যাশ অন ডেলিভারি, বিকাশ, নগদ ও রকেট।",
  "Pickup points": "পিকআপ পয়েন্ট",
  "Dhanmondi hub": "ধানমন্ডি হাব",
  "Road 27, Dhanmondi, Dhaka": "রোড ২৭, ধানমন্ডি, ঢাকা",
  "10am - 8pm": "সকাল ১০টা - রাত ৮টা",
  "Chattogram hub": "চট্টগ্রাম হাব",
  "Agrabad, Chattogram": "আগ্রাবাদ, চট্টগ্রাম",
  "10am - 7pm": "সকাল ১০টা - সন্ধ্যা ৭টা",
  "Sylhet hub": "সিলেট হাব",
  "Zindabazar, Sylhet": "জিন্দাবাজার, সিলেট",
  "Shop this story": "এই গল্প থেকে কিনুন",
  "Your cart": "আপনার কার্ট",

  /* --------------------------------------------------- circuit · chrome */
  "0% EMI up to 12 months": "১২ মাস পর্যন্ত ০% ইএমআই",
  "Official warranty on every unit": "প্রতিটি ইউনিটে অফিসিয়াল ওয়ারেন্টি",
  "Price match on official-warranty stock": "অফিসিয়াল ওয়ারেন্টি স্টকে প্রাইস ম্যাচ",
  Compare: "তুলনা করুন",
  "EMI plans": "ইএমআই প্ল্যান",
  "Service centres": "সার্ভিস সেন্টার",
  "Search by model or spec": "মডেল বা স্পেক দিয়ে খুঁজুন",
  "All categories": "সব ক্যাটাগরি",
  "Shop by category": "ক্যাটাগরি অনুযায়ী কিনুন",

  /* ----------------------------------------------------- circuit · home */
  "Electronics with the specs in writing": "লিখিত স্পেকসহ ইলেকট্রনিকস",
  "Official warranty, published specs, EMI on the spot.":
    "অফিসিয়াল ওয়ারেন্টি, প্রকাশিত স্পেক, সাথে সাথেই ইএমআই।",
  "Browse catalogue": "ক্যাটালগ দেখুন",
  "This week's prices": "এই সপ্তাহের দাম",
  "Why buy here": "কেন এখান থেকে কিনবেন",
  "Official, 12 months": "অফিসিয়াল, ১২ মাস",
  EMI: "ইএমআই",
  "0% up to 12 months": "১২ মাস পর্যন্ত ০%",
  Service: "সার্ভিস",
  "Authorised centres": "অনুমোদিত সেন্টার",
  "Compare the top picks": "সেরা পছন্দগুলো তুলনা করুন",
  Display: "ডিসপ্লে",
  Processor: "প্রসেসর",
  Battery: "ব্যাটারি",
  "Official brand partners": "অফিসিয়াল ব্র্যান্ড পার্টনার",
  "Popular models": "জনপ্রিয় মডেল",
  "Official warranty stock": "অফিসিয়াল ওয়ারেন্টি স্টক",
  "Serial numbers are registered with the brand.": "সিরিয়াল নম্বর ব্র্যান্ডের কাছে নিবন্ধিত।",
  "Service and support": "সার্ভিস ও সাপোর্ট",
  "Warranty claim": "ওয়ারেন্টি ক্লেম",
  "Book a service slot online.": "অনলাইনে সার্ভিস স্লট বুক করুন।",
  "Authorised centres in 12 cities.": "১২টি শহরে অনুমোদিত সেন্টার।",
  Manuals: "ম্যানুয়াল",
  "Download the PDF for any model.": "যেকোনো মডেলের পিডিএফ ডাউনলোড করুন।",

  /* --------------------------------------------------- circuit · footer */
  Support: "সাপোর্ট",
  Buying: "কেনাকাটা",
  Documents: "ডকুমেন্ট",
  "User manual": "ইউজার ম্যানুয়াল",
  PDF: "পিডিএফ",
  "Warranty card": "ওয়ারেন্টি কার্ড",
  "Energy rating": "এনার্জি রেটিং",
  "Official-warranty electronics with published specs, EMI and authorised service.":
    "প্রকাশিত স্পেক, ইএমআই ও অনুমোদিত সার্ভিসসহ অফিসিয়াল ওয়ারেন্টির ইলেকট্রনিকস।",

  /* ------------------------------------------------------ circuit · pdp */
  Configuration: "কনফিগারেশন",
  Storage: "স্টোরেজ",
  Colour: "রং",
  "EMI options": "ইএমআই অপশন",
  "Bank EMI is confirmed at checkout.": "ব্যাংক ইএমআই চেকআউটে নিশ্চিত হয়।",
  "EMI is not available on this item.": "এই পণ্যে ইএমআই নেই।",
  "per month": "প্রতি মাসে",
  "Price history": "দামের ইতিহাস",
  "Lowest price in the last 90 days.": "গত ৯০ দিনের সর্বনিম্ন দাম।",
  "No price history yet.": "এখনও দামের ইতিহাস নেই।",
  "Full specifications": "পূর্ণ স্পেসিফিকেশন",
  Specification: "স্পেসিফিকেশন",
  "At a glance": "এক নজরে",
  "As listed in specs": "স্পেকে যেমন দেওয়া আছে",
  "Manufacturing defects, parts and labour.": "উৎপাদনজনিত ত্রুটি, যন্ত্রাংশ ও শ্রম।",
  "Official warranty": "অফিসিয়াল ওয়ারেন্টি",
  "Parallel import": "প্যারালাল ইমপোর্ট",
  "Dhaka service centre": "ঢাকা সার্ভিস সেন্টার",
  "Panthapath, Dhaka": "পান্থপথ, ঢাকা",
  "Chattogram service centre": "চট্টগ্রাম সার্ভিস সেন্টার",
  "Trade in your old device": "পুরনো ডিভাইস এক্সচেঞ্জ করুন",
  "Send the model and condition; we quote within a day.":
    "মডেল ও অবস্থা পাঠান; এক দিনের মধ্যে দাম জানাই।",
  "Request a quote": "দাম জানতে চাই",
  "Sending...": "পাঠানো হচ্ছে...",
  "I agree to be contacted about this quote.": "এই দর নিয়ে আমার সাথে যোগাযোগে আমি সম্মত।",
  "Build your bundle": "নিজের বান্ডল সাজান",
  "Add bundle": "বান্ডল যোগ করুন",
  "Bundle totals are calculated on the server.": "বান্ডলের মোট হিসাব সার্ভারে করা হয়।",
  "Compare now": "এখনই তুলনা করুন",
  Clear: "মুছুন",
  "Add products to compare.": "তুলনার জন্য পণ্য যোগ করুন।",

  /* ----------------------------------- circuit · collection, page, cart */
  "Browse the category": "ক্যাটাগরি ঘুরে দেখুন",
  "Filter by spec, brand and price.": "স্পেক, ব্র্যান্ড ও দাম দিয়ে ফিল্টার করুন।",
  models: "মডেল",
  "All models": "সব মডেল",
  "Set up your new device": "নতুন ডিভাইস সেটআপ করুন",
  "Charge fully": "সম্পূর্ণ চার্জ দিন",
  "Charge to 100% before the first use.": "প্রথম ব্যবহারের আগে ১০০% চার্জ দিন।",
  "Sign in": "সাইন ইন করুন",
  "Use your own account, never the shop's.": "নিজের অ্যাকাউন্ট ব্যবহার করুন, দোকানের নয়।",
  "Register warranty": "ওয়ারেন্টি নিবন্ধন করুন",
  "Register the serial number within 7 days.": "৭ দিনের মধ্যে সিরিয়াল নম্বর নিবন্ধন করুন।",
  Update: "আপডেট",
  "Install the latest firmware.": "সর্বশেষ ফার্মওয়্যার ইনস্টল করুন।",
  "Sylhet service point": "সিলেট সার্ভিস পয়েন্ট",
  "10am - 6pm": "সকাল ১০টা - সন্ধ্যা ৬টা",
  "How to choose a laptop in Bangladesh": "বাংলাদেশে ল্যাপটপ কীভাবে বাছবেন",
  "Match the processor to the work, not the price tag; then check warranty and service coverage.":
    "দাম নয়, কাজ বুঝে প্রসেসর বাছুন; এরপর ওয়ারেন্টি ও সার্ভিস কভারেজ দেখুন।",
  "Processors explained": "প্রসেসর সহজ ভাষায়",
  "Battery and cooling": "ব্যাটারি ও কুলিং",
  "Warranty vs parallel import": "অফিসিয়াল ওয়ারেন্টি বনাম প্যারালাল ইমপোর্ট",
  "EMI plans are confirmed with your bank at checkout.":
    "ইএমআই প্ল্যান চেকআউটে আপনার ব্যাংকের সাথে নিশ্চিত হয়।",

  /* -------------------------------------------------- rupaboti · chrome */
  "Free samples on orders over BDT 1,500": "১,৫০০ টাকার বেশি অর্ডারে ফ্রি স্যাম্পল",
  "Authentic stock with batch codes": "ব্যাচ কোডসহ আসল পণ্য",
  "Advisor available 10am to 8pm": "সকাল ১০টা - রাত ৮টা পর্যন্ত পরামর্শক আছেন",
  "Shade finder": "শেড ফাইন্ডার",
  Ingredients: "উপাদান",
  "Search by concern or ingredient": "সমস্যা বা উপাদান দিয়ে খুঁজুন",
  "Shop all": "সব দেখুন",
  "Skin first": "আগে ত্বক",

  /* ---------------------------------------------------- rupaboti · home */
  "Beauty that matches your skin": "আপনার ত্বকের সাথে মেলে এমন বিউটি",
  "Shade matched, ingredient transparent, batch coded.":
    "শেড মিলিয়ে দেওয়া, উপাদান স্বচ্ছ, ব্যাচ কোডসহ।",
  "Find your shade": "আপনার শেড খুঁজুন",
  "Pick your undertone": "আন্ডারটোন বাছুন",
  "Pick your depth": "গভীরতা বাছুন",
  "No match yet — try another depth.": "এখনও মিল নেই — অন্য গভীরতা দেখুন।",
  "Two-minute skin quiz": "দুই মিনিটের স্কিন কুইজ",
  "Four questions, one routine.": "চারটি প্রশ্ন, একটি রুটিন।",
  "Your skin type": "আপনার ত্বকের ধরন",
  "Your main concern": "আপনার প্রধান সমস্যা",
  "How sensitive is your skin?": "আপনার ত্বক কতটা সংবেদনশীল?",
  "Finish you prefer": "যে ফিনিশ পছন্দ করেন",
  "Here is a routine for you.": "আপনার জন্য একটি রুটিন।",
  "See my routine": "আমার রুটিন দেখুন",
  "Tested claims": "যাচাই করা দাবি",
  "Dermatologist tested": "ডার্মাটোলজিস্ট পরীক্ষিত",
  "Clinical panel, 2026": "ক্লিনিক্যাল প্যানেল, ২০২৬",
  "Non-comedogenic": "নন-কমেডোজেনিক",
  "Lab report, 2026": "ল্যাব রিপোর্ট, ২০২৬",
  "Fragrance free": "সুগন্ধিমুক্ত",
  "Formulation sheet": "ফর্মুলেশন শিট",
  "Cruelty free": "প্রাণী পরীক্ষা ছাড়া",
  "Supplier declaration": "সরবরাহকারীর ঘোষণা",
  "Eight weeks of use": "আট সপ্তাহের ব্যবহার",
  "Week 0": "সপ্তাহ ০",
  "Week 8": "সপ্তাহ ৮",
  "Individual results vary. Photos are unretouched and taken in the same light.":
    "ফল একেকজনের একেক রকম। ছবিগুলো এডিট করা নয়, একই আলোয় তোলা।",
  "How it feels": "কেমন লাগে",
  Gel: "জেল",
  Cream: "ক্রিম",
  Serum: "সিরাম",
  Balm: "বাম",
  "Build your routine": "নিজের রুটিন সাজান",
  Morning: "সকাল",
  Evening: "সন্ধ্যা",
  Swap: "বদলান",
  "Add the routine": "রুটিন যোগ করুন",
  "Routine totals are calculated on the server.": "রুটিনের মোট হিসাব সার্ভারে করা হয়।",
  "Pick a free sample": "একটি ফ্রি স্যাম্পল বাছুন",
  "Free on orders over BDT 1,500": "১,৫০০ টাকার বেশি অর্ডারে ফ্রি",
  "Ingredient glossary": "উপাদান পরিচিতি",
  Niacinamide: "নায়াসিনামাইড",
  "Evens tone and supports the barrier.": "ত্বকের টোন সমান করে ও ব্যারিয়ার শক্ত রাখে।",
  "Hyaluronic acid": "হায়ালুরনিক অ্যাসিড",
  "Holds water in the upper layers of skin.": "ত্বকের উপরের স্তরে পানি ধরে রাখে।",
  "Salicylic acid": "স্যালিসিলিক অ্যাসিড",
  "Clears pores; use at night.": "লোমকূপ পরিষ্কার করে; রাতে ব্যবহার করুন।",
  SPF: "এসপিএফ",
  "Sun protection factor; reapply every few hours.":
    "সান প্রোটেকশন ফ্যাক্টর; কয়েক ঘণ্টা পরপর আবার লাগান।",
  "Earn points on every order": "প্রতিটি অর্ডারে পয়েন্ট জমান",
  "The shade match was right the first time.": "প্রথমবারেই শেড ঠিকঠাক মিলেছে।",

  /* -------------------------------------------------- rupaboti · footer */
  Guides: "গাইড",
  "Not sure what suits you?": "কোনটা আপনার জন্য বুঝতে পারছেন না?",
  "Send a photo and your concerns; our advisor replies the same day.":
    "ছবি ও আপনার সমস্যা পাঠান; আমাদের পরামর্শক একই দিনে উত্তর দেন।",
  "Chat on WhatsApp": "হোয়াটসঅ্যাপে চ্যাট করুন",
  "Call the advisor": "পরামর্শককে কল করুন",
  "Your skin concern": "আপনার ত্বকের সমস্যা",
  "Request a consult": "পরামর্শ চাই",
  "I agree to be contacted about this request.": "এই অনুরোধ নিয়ে আমার সাথে যোগাযোগে আমি সম্মত।",
  "Follow for routines": "রুটিনের জন্য ফলো করুন",
  "Authentic beauty with batch codes, full ingredient lists and honest shade matching.":
    "ব্যাচ কোড, পূর্ণ উপাদান তালিকা ও সৎ শেড ম্যাচিংসহ আসল বিউটি পণ্য।",

  /* ----------------------------------------------------- rupaboti · pdp */
  "Choose your shade": "আপনার শেড বাছুন",
  Shade: "শেড",
  "Soothes and reduces tightness.": "আরাম দেয় ও টানটান ভাব কমায়।",
  "Full INCI list": "পূর্ণ INCI তালিকা",
  "How to use": "যেভাবে ব্যবহার করবেন",
  Cleanse: "পরিষ্কার করুন",
  "Wash with lukewarm water and pat dry.": "কুসুম গরম পানিতে ধুয়ে আলতো করে মুছুন।",
  Apply: "লাগান",
  "Two drops on damp skin, morning and night.": "ভেজা ত্বকে দুই ফোঁটা, সকালে ও রাতে।",
  Moisturise: "ময়েশ্চারাইজ করুন",
  "Seal with your usual moisturiser.": "আপনার নিয়মিত ময়েশ্চারাইজার দিয়ে সিল করুন।",
  Protect: "সুরক্ষা দিন",
  "Use SPF every morning.": "প্রতিদিন সকালে এসপিএফ ব্যবহার করুন।",
  Safety: "নিরাপত্তা",
  "Patch test on the inner arm for 24 hours before first use.":
    "প্রথম ব্যবহারের আগে হাতের ভেতরের অংশে ২৪ ঘণ্টা প্যাচ টেস্ট করুন।",
  "Apply a small amount, wait a day, check for redness.":
    "অল্প পরিমাণ লাগান, একদিন অপেক্ষা করুন, লালচে ভাব দেখুন।",
  "How to patch test": "প্যাচ টেস্ট যেভাবে করবেন",
  "Batch and expiry": "ব্যাচ ও মেয়াদ",
  Manufactured: "উৎপাদনের তারিখ",
  "Best before": "সেরা মেয়াদ",
  Batch: "ব্যাচ",
  "Subscribe and refill": "সাবস্ক্রাইব ও রিফিল",
  "Pick a cadence; skip or cancel any time.": "সময়সূচি বাছুন; যেকোনো সময় বাদ বা বাতিল করুন।",
  "Every 30 days": "প্রতি ৩০ দিনে",
  "Every 60 days": "প্রতি ৬০ দিনে",
  "Every 90 days": "প্রতি ৯০ দিনে",
  "Start refills": "রিফিল শুরু করুন",
  "Make it a gift": "উপহার হিসেবে পাঠান",
  "Gift message": "উপহারের বার্তা",
  "Add the gift box": "গিফট বক্স যোগ করুন",
  "Gift box totals are calculated on the server.": "গিফট বক্সের মোট হিসাব সার্ভারে করা হয়।",

  /* --------------------------------- rupaboti · collection, page, cart */
  "Shop the range": "সব পণ্য দেখুন",
  "Filter by concern, finish and price.": "সমস্যা, ফিনিশ ও দাম দিয়ে ফিল্টার করুন।",
  products: "পণ্য",
  "Beauty counters": "বিউটি কাউন্টার",
  "Dhanmondi counter": "ধানমন্ডি কাউন্টার",
  "Uttara counter": "উত্তরা কাউন্টার",
  "Sector 7, Uttara, Dhaka": "সেক্টর ৭, উত্তরা, ঢাকা",
  "Which routine fits you?": "কোন রুটিন আপনার জন্য?",
  "Authentic stock": "আসল পণ্য",
  "Remove": "সরান",
  "Your cart is empty.": "আপনার কার্ট খালি।",
  "Choose a method at the final step.": "শেষ ধাপে একটি পদ্ধতি বেছে নিন।",
  "Details": "তথ্য",
  "Items in this order": "এই অর্ডারের পণ্য",
  "Your items": "আপনার পণ্য",
  "No payment method is available right now.": "এই মুহূর্তে কোনো পেমেন্ট পদ্ধতি নেই।",
  "Payment method": "পেমেন্ট পদ্ধতি",
};
