/**
 * Phase 2.1 — the widget help corpus.
 *
 * Every `SectionType` declares bilingual help: one sentence that answers
 * "what does this widget do and when do I reach for it". The record is
 * *total* over `SectionType`, so adding a widget to the catalog without
 * writing help is a type error, and `widget-metadata.test.ts` re-asserts it
 * at runtime (a type-only guarantee dies the moment someone casts).
 *
 * Prop-level hints live here too. Exact keys win; pattern families cover the
 * repeated `i1Image` / `r2c3` / `l3Href` style keys the catalog generates so
 * we do not hand-write 164 near-identical strings.
 */
import type { SectionType } from "./builder-ast";

export type BiText = { en: string; bn: string };

export const WIDGET_HELP: Record<SectionType, BiText> = {
  container: { en: "A layout box that holds other widgets in columns with its own padding and background.", bn: "লেআউট বক্স — ভেতরে অন্য উইজেট কলামে সাজায়, নিজস্ব প্যাডিং ও ব্যাকগ্রাউন্ড থাকে।" },
  columns: { en: "A container with a fixed split, for side-by-side content.", bn: "নির্দিষ্ট ভাগে বিভক্ত কনটেইনার — পাশাপাশি কনটেন্টের জন্য।" },
  divider: { en: "A horizontal rule that separates two blocks of content.", bn: "দুইটি ব্লকের মাঝে আলাদা করার জন্য অনুভূমিক লাইন।" },
  hero: { en: "The first impression of a page: headline, sub-copy and one call to action.", bn: "পেজের প্রথম ইমপ্রেশন — শিরোনাম, সাব-কপি ও একটি কল-টু-অ্যাকশন।" },
  heading: { en: "A section heading (H2 or H3) that structures the page outline.", bn: "সেকশন শিরোনাম (H2/H3) — পেজের আউটলাইন তৈরি করে।" },
  rich_text: { en: "A prose block for paragraphs, lists and links.", bn: "প্যারাগ্রাফ, তালিকা ও লিংকের জন্য টেক্সট ব্লক।" },
  image: { en: "A single responsive image with required alt text.", bn: "একক রেসপন্সিভ ইমেজ — alt টেক্সট বাধ্যতামূলক।" },
  video: { en: "An embedded video from an allow-listed host, loaded on interaction.", bn: "অনুমোদিত হোস্ট থেকে ভিডিও এমবেড — ক্লিক করলে লোড হয়।" },
  product_grid: { en: "A grid of products from a collection or the whole catalogue.", bn: "কালেকশন বা ক্যাটালগ থেকে প্রোডাক্ট গ্রিড।" },
  collection_grid: { en: "A grid of collections that sends shoppers into category pages.", bn: "কালেকশন গ্রিড — ক্রেতাদের ক্যাটাগরি পেজে পাঠায়।" },
  banner: { en: "A promotional band with an image, copy and a link.", bn: "প্রোমোশনাল ব্যানার — ইমেজ, কপি ও লিংক।" },
  feature_row: { en: "Three to four short value propositions in a row.", bn: "সারিতে তিন-চারটি সংক্ষিপ্ত ভ্যালু পয়েন্ট।" },
  testimonial: { en: "A customer quote with attribution, for social proof.", bn: "ক্রেতার মন্তব্য ও নাম — সোশ্যাল প্রুফের জন্য।" },
  faq: { en: "Questions and answers, rendered as crawlable text plus FAQ schema.", bn: "প্রশ্ন-উত্তর — ক্রল-যোগ্য টেক্সট ও FAQ স্কিমা সহ।" },
  countdown: { en: "A timer to a deadline; the block hides itself once the time passes.", bn: "নির্দিষ্ট সময় পর্যন্ত কাউন্টডাউন — সময় শেষে নিজে লুকায়।" },
  marquee: { en: "A slow scrolling strip of short messages; pauses for reduced motion.", bn: "ছোট বার্তার ধীর স্ক্রোলিং স্ট্রিপ — reduced motion-এ থামে।" },
  newsletter: { en: "An email capture form wired to the subscriber list with consent text.", bn: "ইমেইল সংগ্রহ ফর্ম — সাবস্ক্রাইবার লিস্ট ও কনসেন্ট টেক্সট সহ।" },
  spacer: { en: "Vertical breathing room between two sections.", bn: "দুই সেকশনের মাঝে উল্লম্ব ফাঁকা জায়গা।" },
  html: { en: "Custom HTML rendered inside a sandboxed frame — no cookies, no page access.", bn: "কাস্টম HTML — স্যান্ডবক্সড ফ্রেমে চলে, কুকি বা পেজ অ্যাক্সেস নেই।" },
  plugin_block: { en: "A widget supplied by an installed app, rendered in its own boundary.", bn: "ইনস্টল করা অ্যাপের উইজেট — নিজস্ব বাউন্ডারিতে রেন্ডার হয়।" },
  breadcrumb: { en: "The trail back up the category tree, with BreadcrumbList schema.", bn: "ক্যাটাগরি ট্রি-তে ফেরার পথ — BreadcrumbList স্কিমা সহ।" },
  product_media: { en: "The product gallery: main image, thumbnails and zoom.", bn: "প্রোডাক্ট গ্যালারি — প্রধান ইমেজ, থাম্বনেইল ও জুম।" },
  price_block: { en: "Price, compare-at price and savings for the current product.", bn: "বর্তমান প্রোডাক্টের দাম, আগের দাম ও সাশ্রয়।" },
  add_to_cart: { en: "Quantity picker and the add-to-cart action for this product.", bn: "কোয়ান্টিটি সিলেক্টর ও অ্যাড-টু-কার্ট বাটন।" },
  product_meta: { en: "SKU, brand and category metadata for the current product.", bn: "প্রোডাক্টের SKU, ব্র্যান্ড ও ক্যাটাগরি তথ্য।" },
  page_content: { en: "The body of the CMS page this template is rendering.", bn: "এই টেমপ্লেট যে CMS পেজ দেখাচ্ছে তার মূল কনটেন্ট।" },
  cart_summary: { en: "Order totals, coupon field and the checkout button.", bn: "অর্ডার টোটাল, কুপন ফিল্ড ও চেকআউট বাটন।" },
  tabs: { en: "Content split across tabs; all panels stay in the document for SEO.", bn: "ট্যাবে ভাগ করা কনটেন্ট — SEO-র জন্য সব প্যানেল ডকুমেন্টে থাকে।" },
  accordion: { en: "Collapsible rows for long content; the first can start open.", bn: "লম্বা কনটেন্টের জন্য কোলাপসিবল সারি — প্রথমটি খোলা রাখা যায়।" },
  sticky_bar: { en: "A bar pinned to the top or bottom after a scroll threshold.", bn: "স্ক্রল করার পর উপরে/নিচে আটকে থাকা বার।" },
  spec_table: { en: "A two-column specification table, one row per attribute.", bn: "দুই কলামের স্পেসিফিকেশন টেবিল — প্রতি সারিতে এক অ্যাট্রিবিউট।" },
  quiz: { en: "A short guided quiz that routes shoppers to a filtered result page.", bn: "ছোট কুইজ — উত্তর অনুযায়ী ফিল্টার করা রেজাল্ট পেজে পাঠায়।" },
  recently_viewed: { en: "Products this visitor opened before, read from local history.", bn: "এই ভিজিটরের আগে দেখা প্রোডাক্ট — লোকাল হিস্ট্রি থেকে।" },
  quick_view: { en: "Opens a product preview drawer without leaving the listing.", bn: "লিস্টিং না ছেড়ে প্রোডাক্ট প্রিভিউ ড্রয়ার খোলে।" },
  bundle_offer: { en: "A discounted bundle of this product with companions.", bn: "এই প্রোডাক্টের সাথে ছাড়যুক্ত বান্ডল অফার।" },
  announcement_bar: { en: "A thin site-wide message strip, optionally dismissible and rotating.", bn: "সাইট-জুড়ে সরু বার্তা স্ট্রিপ — বন্ধ করা ও রোটেট করা যায়।" },
  utility_bar: { en: "Secondary header row: language, currency and support links.", bn: "হেডারের দ্বিতীয় সারি — ভাষা, মুদ্রা ও সাপোর্ট লিংক।" },
  trust_bar: { en: "Delivery, returns and authenticity promises in one row.", bn: "ডেলিভারি, রিটার্ন ও অথেন্টিসিটির প্রতিশ্রুতি এক সারিতে।" },
  payment_icons: { en: "Accepted payment methods, shown as recognisable marks.", bn: "গ্রহণযোগ্য পেমেন্ট মাধ্যমের পরিচিত আইকন।" },
  notice: { en: "An inline informational, warning or error message.", bn: "ইনলাইন তথ্য, সতর্কতা বা ত্রুটির বার্তা।" },
  mega_menu: { en: "Three-level navigation built from the category taxonomy.", bn: "ক্যাটাগরি ট্যাক্সোনমি থেকে তৈরি তিন-স্তরের নেভিগেশন।" },
  department_strip: { en: "A scrollable row of top departments for fast entry.", bn: "প্রধান ডিপার্টমেন্টের স্ক্রলযোগ্য সারি — দ্রুত প্রবেশের জন্য।" },
  footer_sitemap: { en: "Grouped footer links: policies, help and categories.", bn: "ফুটার লিংক গ্রুপ — পলিসি, সহায়তা ও ক্যাটাগরি।" },
  search_command: { en: "The search entry point with suggestions and keyboard access.", bn: "সার্চ এন্ট্রি পয়েন্ট — সাজেশন ও কীবোর্ড অ্যাক্সেস সহ।" },
  account_cart: { en: "Account and cart affordances for the header.", bn: "হেডারের অ্যাকাউন্ট ও কার্ট বাটন।" },
  product_rail: { en: "A horizontally scrolling row of products with a heading.", bn: "শিরোনাম সহ অনুভূমিক স্ক্রলিং প্রোডাক্ট সারি।" },
  deal_card: { en: "One highlighted offer with price, saving and a deadline.", bn: "একটি হাইলাইট করা অফার — দাম, সাশ্রয় ও সময়সীমা সহ।" },
  deal_strip: { en: "A compact strip of running deals.", bn: "চলমান অফারের সংক্ষিপ্ত স্ট্রিপ।" },
  sponsored_slot: { en: "A labelled paid placement; the sponsor disclosure is mandatory.", bn: "লেবেলযুক্ত পেইড প্লেসমেন্ট — স্পনসর ঘোষণা বাধ্যতামূলক।" },
  brand_strip: { en: "A row of brand marks that link to brand pages.", bn: "ব্র্যান্ড লোগোর সারি — ব্র্যান্ড পেজে লিংক করে।" },
  brand_rail: { en: "A scrollable brand rail with names and product counts.", bn: "স্ক্রলযোগ্য ব্র্যান্ড রেল — নাম ও প্রোডাক্ট সংখ্যা সহ।" },
  compare_table: { en: "Side-by-side comparison of a few products' key attributes.", bn: "কয়েকটি প্রোডাক্টের মূল বৈশিষ্ট্যের পাশাপাশি তুলনা।" },
  rank_list: { en: "A numbered best-seller or editor's-pick list.", bn: "নম্বরযুক্ত বেস্ট-সেলার বা এডিটরস-পিক তালিকা।" },
  buy_box: { en: "The purchase panel: price, stock, delivery and the buy actions.", bn: "ক্রয় প্যানেল — দাম, স্টক, ডেলিভারি ও ক্রয় বাটন।" },
  variant_picker: { en: "Selectable options (size, colour) for the current product.", bn: "প্রোডাক্টের অপশন নির্বাচন — সাইজ, রঙ ইত্যাদি।" },
  delivery_promise: { en: "The delivery window quoted for the shopper's area.", bn: "ক্রেতার এলাকার জন্য প্রতিশ্রুত ডেলিভারি সময়।" },
  stock_delivery: { en: "Stock state plus the low-stock threshold and dispatch note.", bn: "স্টক অবস্থা, লো-স্টক সীমা ও ডিসপ্যাচ নোট।" },
  rating_summary: { en: "Average rating, review count and an optional histogram.", bn: "গড় রেটিং, রিভিউ সংখ্যা ও ঐচ্ছিক হিস্টোগ্রাম।" },
  review_list: { en: "Published reviews, optionally limited to verified purchases.", bn: "প্রকাশিত রিভিউ — চাইলে শুধু ভেরিফায়েড ক্রয়।" },
  product_qna: { en: "Shopper questions and merchant answers for this product.", bn: "এই প্রোডাক্ট নিয়ে ক্রেতার প্রশ্ন ও বিক্রেতার উত্তর।" },
  seller_card: { en: "Who is selling: name, rating and fulfilment note.", bn: "বিক্রেতার পরিচয় — নাম, রেটিং ও ফুলফিলমেন্ট তথ্য।" },
  sticky_buy_bar: { en: "A mobile bar that keeps price and add-to-cart reachable.", bn: "মোবাইল বার — দাম ও অ্যাড-টু-কার্ট সবসময় হাতের কাছে।" },
  facet_sidebar: { en: "Filter facets for a listing: category, type, price, availability.", bn: "লিস্টিং ফিল্টার — ক্যাটাগরি, ধরন, দাম, স্টক।" },
  filter_chips: { en: "The active filters, each removable, with a clear-all action.", bn: "সক্রিয় ফিল্টার চিপ — আলাদা বা সব একসাথে মোছা যায়।" },
  result_toolbar: { en: "Result count, sort control and density toggle.", bn: "রেজাল্ট সংখ্যা, সর্ট কন্ট্রোল ও ডেনসিটি টগল।" },
  pagination: { en: "Page-by-page navigation with crawlable links.", bn: "পেজ-বাই-পেজ নেভিগেশন — ক্রল-যোগ্য লিংক সহ।" },
  category_header: { en: "Category title, description and optional product count.", bn: "ক্যাটাগরির শিরোনাম, বর্ণনা ও ঐচ্ছিক প্রোডাক্ট সংখ্যা।" },
  empty_state: { en: "What a shopper sees when a listing or search returns nothing.", bn: "লিস্টিং বা সার্চে কিছু না পেলে ক্রেতা যা দেখবে।" },
  cart_lines: { en: "The cart's line items with quantity and remove controls.", bn: "কার্টের আইটেম তালিকা — কোয়ান্টিটি ও রিমুভ কন্ট্রোল সহ।" },
  cart_drawer: { en: "A slide-over cart opened from the header.", bn: "হেডার থেকে খোলা স্লাইড-ওভার কার্ট।" },
  checkout_steps: { en: "The checkout progress indicator.", bn: "চেকআউট অগ্রগতির ধাপ নির্দেশক।" },
  payment_methods: { en: "Selectable payment methods, including cash on delivery.", bn: "পেমেন্ট মাধ্যম নির্বাচন — ক্যাশ অন ডেলিভারি সহ।" },
  order_tracker: { en: "Order status timeline for the signed-in shopper.", bn: "সাইন-ইন করা ক্রেতার অর্ডার স্ট্যাটাস টাইমলাইন।" },
  free_shipping_bar: { en: "Progress toward the free shipping threshold.", bn: "ফ্রি শিপিং সীমার দিকে অগ্রগতি।" },
  editorial_hero: { en: "A magazine-style hero with an image and overlaid copy.", bn: "ম্যাগাজিন-স্টাইল হিরো — ইমেজের উপর কপি।" },
  lookbook: { en: "A styled multi-image lookbook of a collection.", bn: "কালেকশনের একাধিক ইমেজের লুকবুক।" },
  shoppable_image: { en: "An image with pinned hotspots that link to products.", bn: "ইমেজের উপর হটস্পট পিন — প্রোডাক্টে লিংক করে।" },
  split_feature: { en: "An image on one side and copy on the other, flippable.", bn: "একপাশে ইমেজ, অন্যপাশে কপি — দিক বদলানো যায়।" },
  collection_story: { en: "Narrative copy that introduces a collection.", bn: "কালেকশনের পরিচয় দেয় এমন গল্প-ধাঁচের কপি।" },
  ugc_gallery: { en: "Customer photos, loaded lazily and credited.", bn: "ক্রেতাদের ছবি — লেজি লোড ও কৃতিত্ব সহ।" },
  social_strip: { en: "Links to the store's social profiles.", bn: "স্টোরের সোশ্যাল প্রোফাইল লিংক।" },
  store_locator: { en: "Physical outlets with address and opening hours.", bn: "শোরুমের ঠিকানা ও খোলার সময়।" },
  size_selector: { en: "Size options with stock awareness.", bn: "সাইজ অপশন — স্টক অনুযায়ী।" },
  size_guide: { en: "A measurement table in cm or inches.", bn: "সেন্টিমিটার বা ইঞ্চিতে মাপের টেবিল।" },
  fit_note: { en: "A short note on how the item fits.", bn: "পোশাকের ফিট নিয়ে সংক্ষিপ্ত নোট।" },
  back_in_stock: { en: "Collects consent to notify when the item returns.", bn: "স্টকে ফিরলে জানানোর জন্য সম্মতি নেয়।" },
  care_panel: { en: "Care and washing instructions.", bn: "যত্ন ও ধোয়ার নির্দেশনা।" },
  sustain_badge: { en: "A sustainability claim; needs evidence to publish.", bn: "টেকসই দাবি — প্রকাশ করতে প্রমাণ লাগে।" },
  complete_the_look: { en: "Companion products styled with this one.", bn: "এই প্রোডাক্টের সাথে মানানসই অন্য প্রোডাক্ট।" },
  wishlist_button: { en: "Saves the product to the shopper's wishlist.", bn: "প্রোডাক্টটি ক্রেতার উইশলিস্টে সংরক্ষণ করে।" },
  spec_highlights: { en: "The three to six specs that decide the purchase.", bn: "ক্রয়-সিদ্ধান্তে সবচেয়ে গুরুত্বপূর্ণ তিন-ছয়টি স্পেস।" },
  compare_tray: { en: "A tray collecting products the shopper marked to compare.", bn: "তুলনার জন্য চিহ্নিত প্রোডাক্টের ট্রে।" },
  warranty_panel: { en: "Warranty length, coverage and claim route.", bn: "ওয়ারেন্টির মেয়াদ, কভারেজ ও ক্লেইম পদ্ধতি।" },
  authenticity_badge: { en: "Official import or authorised seller assurance.", bn: "অফিসিয়াল ইমপোর্ট বা অনুমোদিত বিক্রেতার নিশ্চয়তা।" },
  emi_calculator: { en: "Monthly instalment estimates; figures are indicative.", bn: "মাসিক কিস্তির হিসাব — সংখ্যাগুলো নির্দেশক মাত্র।" },
  price_sparkline: { en: "Recent price movement over a chosen window.", bn: "নির্বাচিত সময়ে দামের সাম্প্রতিক ওঠানামা।" },
  bundle_builder: { en: "Lets the shopper assemble a kit and see the saving.", bn: "ক্রেতা নিজে কিট বানিয়ে সাশ্রয় দেখতে পারে।" },
  doc_links: { en: "Manuals, datasheets and firmware downloads.", bn: "ম্যানুয়াল, ডেটাশিট ও ফার্মওয়্যার ডাউনলোড।" },
  support_strip: { en: "Service, helpline and repair entry points.", bn: "সার্ভিস, হেল্পলাইন ও রিপেয়ার এন্ট্রি পয়েন্ট।" },
  buying_guide: { en: "An attributed guide that answers how to choose.", bn: "কীভাবে বাছবেন — লেখকের নামসহ গাইড।" },
  trade_in: { en: "Trade-in offer and the quote entry point.", bn: "ট্রেড-ইন অফার ও কোট নেওয়ার জায়গা।" },
  shade_finder: { en: "Guides the shopper to the right shade.", bn: "সঠিক শেড বাছতে ক্রেতাকে সাহায্য করে।" },
  skin_quiz: { en: "A short skin-type quiz that recommends products.", bn: "ছোট স্কিন-টাইপ কুইজ — প্রোডাক্ট সাজেস্ট করে।" },
  routine_builder: { en: "Builds a step-by-step routine from products.", bn: "প্রোডাক্ট দিয়ে ধাপে ধাপে রুটিন তৈরি করে।" },
  ingredient_list: { en: "The full INCI list for this product.", bn: "এই প্রোডাক্টের সম্পূর্ণ INCI তালিকা।" },
  ingredient_glossary: { en: "Plain-language explanations of key ingredients.", bn: "মূল উপাদানের সহজ ভাষায় ব্যাখ্যা।" },
  claim_chips: { en: "Short product claims; each needs substantiation.", bn: "সংক্ষিপ্ত প্রোডাক্ট দাবি — প্রতিটির প্রমাণ দরকার।" },
  before_after: { en: "A before/after pair with a mandatory disclaimer.", bn: "আগে/পরে ছবি — ডিসক্লেইমার বাধ্যতামূলক।" },
  safety_note: { en: "Patch-test and safety guidance.", bn: "প্যাচ-টেস্ট ও নিরাপত্তা নির্দেশনা।" },
  batch_info: { en: "Batch code, manufacture date and period after opening.", bn: "ব্যাচ কোড, উৎপাদনের তারিখ ও খোলার পর ব্যবহারের সময়।" },
  texture_strip: { en: "Texture and finish previews for the range.", bn: "টেক্সচার ও ফিনিশের প্রিভিউ।" },
  how_to_use: { en: "Application steps, emitted as HowTo structured data.", bn: "ব্যবহারের ধাপ — HowTo স্ট্রাকচার্ড ডেটা হিসেবেও যায়।" },
  refill_widget: { en: "Offers the refill pack for this product.", bn: "এই প্রোডাক্টের রিফিল প্যাক অফার করে।" },
  gift_builder: { en: "Assembles a gift set with wrapping options.", bn: "মোড়ক অপশনসহ গিফট সেট তৈরি করে।" },
  sample_picker: { en: "Lets the shopper choose free samples at checkout.", bn: "চেকআউটে বিনামূল্যে স্যাম্পল বাছতে দেয়।" },
  consult_cta: { en: "Books a consultation with a specialist.", bn: "বিশেষজ্ঞের সাথে পরামর্শের বুকিং।" },
  loyalty_strip: { en: "Points balance and the reward the shopper is close to.", bn: "পয়েন্ট ব্যালান্স ও কাছাকাছি থাকা রিওয়ার্ড।" },
  // Phase 7 — layout primitives.
  button: { en: "A single call-to-action link, styled from the theme's button tokens.", bn: "একটি কল-টু-অ্যাকশন লিংক — থিমের বাটন টোকেন থেকে স্টাইল নেয়।" },
  icon: { en: "One icon from the platform set, with an optional caption and link.", bn: "প্ল্যাটফর্ম সেট থেকে একটি আইকন — ঐচ্ছিক ক্যাপশন ও লিংক সহ।" },
  form: { en: "A contact form that files the message against your store inbox.", bn: "যোগাযোগ ফর্ম — বার্তা আপনার স্টোর ইনবক্সে জমা হয়।" },
  nav_menu: { en: "A list of links for the header, footer or a sidebar.", bn: "হেডার, ফুটার বা সাইডবারের জন্য লিংকের তালিকা।" },
  logo: { en: "Your shop mark: an image, or a wordmark when no image is set.", bn: "আপনার দোকানের চিহ্ন — ইমেজ, অথবা ইমেজ না থাকলে লেখা।" },
  carousel: { en: "A swipeable row of images with optional captions and links.", bn: "সোয়াইপ করা যায় এমন ইমেজ সারি — ক্যাপশন ও লিংক ঐচ্ছিক।" },
  // Phase 8 — blog archive pack.
  blog_archive: { en: "The list of blog posts, in a grid, list, magazine or minimal layout.", bn: "ব্লগ পোস্টের তালিকা — গ্রিড, লিস্ট, ম্যাগাজিন বা মিনিমাল লেআউটে।" },
  blog_terms: { en: "Category and tag links for the blog, with article counts.", bn: "ব্লগের ক্যাটাগরি ও ট্যাগ লিংক, লেখার সংখ্যাসহ।" },
  blog_pager: { en: "Previous / next page links for the blog archive.", bn: "ব্লগ আর্কাইভের আগের / পরের পেজ লিংক।" },
};

/** Exact prop-key hints. Keys are catalog `Field.key`s. */
export const PROP_HINTS: Record<string, BiText> = {
  showCover: { en: "Show each post's cover image.", bn: "প্রতিটি পোস্টের কভার ইমেজ দেখান।" },
  showExcerpt: { en: "Show the short summary under each title.", bn: "প্রতিটি শিরোনামের নিচে সংক্ষিপ্ত সারাংশ দেখান।" },
  showMeta: { en: "Show the author name and publish date.", bn: "লেখকের নাম ও প্রকাশের তারিখ দেখান।" },
  style: { en: "Pills for a compact topic rail, or a plain list for a sidebar.", bn: "কম্প্যাক্ট টপিক রেইলের জন্য পিল, সাইডবারের জন্য সাধারণ তালিকা।" },
  showCounts: { en: "Show how many articles each topic has.", bn: "প্রতিটি বিষয়ে কতটি লেখা আছে দেখান।" },
  emptyText: { en: "What readers see before the first post is published.", bn: "প্রথম পোস্ট প্রকাশের আগে পাঠক যা দেখবে।" },
  padY: { en: "Space above and below the widget, in px. Keep rhythm consistent across a page.", bn: "উইজেটের উপরে-নিচে ফাঁকা জায়গা (px)। পুরো পেজে একই ছন্দ রাখুন।" },
  padX: { en: "Inner left/right padding, in px. Leave at 0 to inherit the container.", bn: "ভেতরের ডান-বাম প্যাডিং (px)। 0 রাখলে কনটেইনার থেকে আসবে।" },
  maxW: { en: "How wide the content may grow: container, narrow reading width, or full bleed.", bn: "কনটেন্ট কত চওড়া হবে — কনটেইনার, সরু পাঠ-প্রস্থ, বা পূর্ণ প্রস্থ।" },
  bg: { en: "Background surface, taken from the theme tokens — raw colours are rejected.", bn: "থিম টোকেন থেকে ব্যাকগ্রাউন্ড — সরাসরি রঙ গ্রহণযোগ্য নয়।" },
  align: { en: "Text and content alignment. Can differ per device.", bn: "টেক্সট ও কনটেন্ট অ্যালাইনমেন্ট — ডিভাইসভেদে আলাদা হতে পারে।" },
  radius: { en: "Corner rounding, from the theme radius scale.", bn: "কোণের গোলাকৃতি — থিমের রেডিয়াস স্কেল থেকে।" },
  border: { en: "Outline around the widget.", bn: "উইজেটের চারপাশে বর্ডার।" },
  shadow: { en: "Elevation. Heavier shadows cost contrast on dark themes.", bn: "এলিভেশন — ডার্ক থিমে বেশি ছায়া কনট্রাস্ট কমায়।" },
  ratio: { en: "Aspect ratio reserved for media, so the layout never shifts while loading.", bn: "মিডিয়ার জন্য সংরক্ষিত অনুপাত — লোড হওয়ার সময় লেআউট নড়ে না।" },
  reveal: { en: "Entrance animation. Ignored for visitors who prefer reduced motion.", bn: "প্রবেশ অ্যানিমেশন — reduced motion চাইলে বাদ যায়।" },
  span: { en: "How many of the parent's 12 columns this node occupies. 0 = auto.", bn: "প্যারেন্টের ১২ কলামের কতটা নেবে। 0 = স্বয়ংক্রিয়।" },
  limit: { en: "Maximum products fetched. Lower is faster; the data layer caps it anyway.", bn: "সর্বোচ্চ কত প্রোডাক্ট আসবে। কম রাখলে দ্রুত লোড হয়।" },
  columns: { en: "Columns at this breakpoint. Mobile should rarely exceed two.", bn: "এই ব্রেকপয়েন্টে কলাম সংখ্যা — মোবাইলে সাধারণত দুইয়ের বেশি নয়।" },
  gap: { en: "Space between children, in px.", bn: "চাইল্ড এলিমেন্টের মাঝে ফাঁক (px)।" },
  ctaHref: { en: "Where the button goes. Use a /relative path for pages in this store.", bn: "বাটন কোথায় যাবে। নিজের স্টোরের পেজে /relative পাথ দিন।" },
  href: { en: "Destination link. Relative paths keep the shopper on this store.", bn: "গন্তব্য লিংক — relative পাথ হলে ক্রেতা স্টোরেই থাকে।" },
  cardVariant: { en: "Product card layout. Editorial suits lifestyle imagery, compact suits dense grids.", bn: "প্রোডাক্ট কার্ডের লেআউট — এডিটোরিয়াল লাইফস্টাইল ছবির জন্য, কমপ্যাক্ট ঘন গ্রিডের জন্য।" },
  density: { en: "How tight the card spacing is.", bn: "কার্ডের স্পেসিং কতটা ঘন।" },
  level: { en: "Heading level. Never skip a level — the outline must stay H1 → H2 → H3.", bn: "হেডিং লেভেল — কোনো স্তর বাদ দেবেন না (H1 → H2 → H3)।" },
  scrim: { en: "Darkens the image behind text so the copy keeps its contrast ratio.", bn: "টেক্সটের পেছনে ছবি গাঢ় করে — কনট্রাস্ট ঠিক থাকে।" },
  showCount: { en: "Shows how many products sit in each collection.", bn: "প্রতিটি কালেকশনে কতটি প্রোডাক্ট আছে দেখায়।" },
  showRating: { en: "Shows the star average on each card.", bn: "প্রতিটি কার্ডে গড় রেটিং দেখায়।" },
  showPrice: { en: "Shows price on the card.", bn: "কার্ডে দাম দেখায়।" },
  showCompareAt: { en: "Shows the struck-through original price when one exists.", bn: "আগের দাম থাকলে কাটা দাগে দেখায়।" },
  showQuantity: { en: "Lets the shopper change quantity here.", bn: "এখানেই কোয়ান্টিটি বদলানো যায়।" },
  showCoupon: { en: "Shows the coupon entry field.", bn: "কুপন লেখার ফিল্ড দেখায়।" },
  showCta: { en: "Shows the primary action button.", bn: "প্রধান অ্যাকশন বাটন দেখায়।" },
  showFreeShipping: { en: "Shows progress toward the free shipping threshold.", bn: "ফ্রি শিপিং সীমার অগ্রগতি দেখায়।" },
  showThumbnails: { en: "Shows the gallery thumbnail strip.", bn: "গ্যালারির থাম্বনেইল স্ট্রিপ দেখায়।" },
  showHistogram: { en: "Shows the 1–5 star distribution.", bn: "১–৫ তারার বণ্টন দেখায়।" },
  showBreadcrumb: { en: "Shows the category trail above the title.", bn: "শিরোনামের উপরে ক্যাটাগরি ট্রেইল দেখায়।" },
  showCategories: { en: "Enables the category facet.", bn: "ক্যাটাগরি ফ্যাসেট চালু করে।" },
  showKinds: { en: "Enables the product-type facet.", bn: "প্রোডাক্ট-টাইপ ফ্যাসেট চালু করে।" },
  showStock: { en: "Enables the availability facet.", bn: "স্টক ফ্যাসেট চালু করে।" },
  showSort: { en: "Shows the sort control.", bn: "সর্ট কন্ট্রোল দেখায়।" },
  showDensity: { en: "Shows the grid density toggle.", bn: "গ্রিড ডেনসিটি টগল দেখায়।" },
  showClear: { en: "Shows a clear-all-filters action.", bn: "সব ফিল্টার মোছার বাটন দেখায়।" },
  showSuggestions: { en: "Shows suggested products under the search box.", bn: "সার্চ বক্সের নিচে সাজেস্টেড প্রোডাক্ট দেখায়।" },
  showLanguage: { en: "Shows the English / বাংলা toggle.", bn: "English / বাংলা টগল দেখায়।" },
  showWhenEmpty: { en: "Keeps the widget visible even when nothing is filtered.", bn: "কিছু ফিল্টার না থাকলেও উইজেট দেখায়।" },
  dismissible: { en: "Lets the visitor close it; the choice is remembered for the session.", bn: "ভিজিটর বন্ধ করতে পারে — সেশনজুড়ে মনে রাখা হয়।" },
  rotateMs: { en: "Milliseconds between messages. 0 disables rotation.", bn: "বার্তা বদলের ব্যবধান (মিলিসেকেন্ড)। 0 দিলে রোটেশন বন্ধ।" },
  speed: { en: "Seconds for one full loop. Slower is easier to read.", bn: "একবার লুপ হতে কত সেকেন্ড। ধীর হলে পড়তে সহজ।" },
  pauseOnHover: { en: "Pauses the scroll while the pointer is over it.", bn: "পয়েন্টার উপরে থাকলে স্ক্রল থামে।" },
  tone: { en: "Semantic tone: informational, positive, warning or danger.", bn: "সিমান্টিক টোন — তথ্য, ইতিবাচক, সতর্কতা বা বিপদ।" },
  size: { en: "Height in px.", bn: "উচ্চতা (px)।" },
  height: { en: "Fixed height in px. Prefer a ratio where you can.", bn: "নির্দিষ্ট উচ্চতা (px)। সম্ভব হলে ratio ব্যবহার করুন।" },
  source: { en: "Where the rows come from.", bn: "সারিগুলো কোথা থেকে আসবে।" },
  mode: { en: "How the widget presents its content.", bn: "উইজেট কীভাবে কনটেন্ট দেখাবে।" },
  layout: { en: "Structural arrangement of the widget.", bn: "উইজেটের কাঠামোগত বিন্যাস।" },
  position: { en: "Where the bar docks: top or bottom of the viewport.", bn: "বারটি কোথায় বসবে — উপরে না নিচে।" },
  dockAfter: { en: "Pixels scrolled before the bar appears.", bn: "কত পিক্সেল স্ক্রলের পর বারটি দেখাবে।" },
  sort: { en: "Default ordering applied before the limit.", bn: "লিমিট প্রয়োগের আগে ডিফল্ট ক্রম।" },
  markup: { en: "Runs sandboxed: no cookies, no access to the page. Third-party scripts still cost performance.", bn: "স্যান্ডবক্সে চলে — কুকি বা পেজ অ্যাক্সেস নেই। থার্ড-পার্টি স্ক্রিপ্ট তবু পারফরম্যান্স খরচ করে।" },
  openFirst: { en: "Opens the first row on load; the rest stay collapsed.", bn: "প্রথম সারি খোলা থাকে, বাকিগুলো বন্ধ।" },
  open: { en: "Starts in the open state.", bn: "শুরুতেই খোলা অবস্থায় থাকে।" },
  collapsed: { en: "Starts collapsed to save vertical space on mobile.", bn: "মোবাইলে জায়গা বাঁচাতে শুরুতে বন্ধ থাকে।" },
  grouped: { en: "Groups rows under collapsible headings.", bn: "সারিগুলো কোলাপসিবল শিরোনামে গ্রুপ করে।" },
  zoom: { en: "Enables tap-to-zoom on the main image.", bn: "প্রধান ছবিতে ট্যাপ-টু-জুম চালু করে।" },
  flip: { en: "Puts the image on the right instead of the left.", bn: "ছবি বাঁয়ের বদলে ডানে বসায়।" },
  offset: { en: "Staggers the two halves for an editorial feel.", bn: "দুই অংশ একটু সরিয়ে এডিটোরিয়াল ভাব আনে।" },
  resultBase: { en: "Base URL the quiz result appends its filters to.", bn: "কুইজের ফলাফল যে URL-এ ফিল্টার যোগ করবে।" },
  resultPath: { en: "Path the shopper lands on after finishing.", bn: "শেষ করার পর ক্রেতা যে পাথে যাবে।" },
  compareHref: { en: "Link to the full comparison page.", bn: "পূর্ণ তুলনা পেজের লিংক।" },
  askHref: { en: "Where the ask-a-question button goes.", bn: "প্রশ্ন করার বাটন কোথায় নিয়ে যাবে।" },
  linkHref: { en: "Destination for this card.", bn: "এই কার্ডের গন্তব্য।" },
  lowStockAt: { en: "Units at or below this number show the low-stock warning.", bn: "এই সংখ্যার সমান বা কম হলে লো-স্টক সতর্কতা দেখাবে।" },
  verifiedOnly: { en: "Restricts the list to verified purchases.", bn: "শুধু ভেরিফায়েড ক্রয়ের রিভিউ দেখায়।" },
  rating: { en: "Rating out of 5, used when no live data is connected.", bn: "৫-এর মধ্যে রেটিং — লাইভ ডেটা না থাকলে ব্যবহৃত হয়।" },
  months: { en: "Warranty length in months. 0 hides the duration.", bn: "ওয়ারেন্টির মেয়াদ (মাস)। 0 দিলে মেয়াদ দেখাবে না।" },
  official: { en: "Claims official import. Only tick this if you can evidence it.", bn: "অফিসিয়াল ইমপোর্ট দাবি — প্রমাণ থাকলেই টিক দিন।" },
  verified: { en: "Marks the claim as verified by the store.", bn: "স্টোর কর্তৃক যাচাইকৃত হিসেবে চিহ্নিত করে।" },
  days: { en: "Window in days used for the trend.", bn: "ট্রেন্ডের জন্য কত দিনের সময়সীমা।" },
  unit: { en: "Default measurement unit shown first.", bn: "প্রথমে যে পরিমাপ একক দেখাবে।" },
  fit: { en: "How the garment runs against standard sizing.", bn: "স্ট্যান্ডার্ড সাইজের তুলনায় পোশাকের ফিট।" },
  activeStep: { en: "Which step is highlighted (1–4).", bn: "কোন ধাপ হাইলাইট হবে (১–৪)।" },
  paoMonths: { en: "Months the product stays usable after opening.", bn: "খোলার পর কত মাস ব্যবহারযোগ্য থাকবে।" },
  logoUrl: { en: "Brand mark. Use a transparent PNG or SVG.", bn: "ব্র্যান্ড লোগো — ট্রান্সপারেন্ট PNG বা SVG দিন।" },
  src: { en: "Image source, picked from your media library.", bn: "ইমেজ সোর্স — মিডিয়া লাইব্রেরি থেকে নিন।" },
  image: { en: "Image, picked from your media library.", bn: "ইমেজ — মিডিয়া লাইব্রেরি থেকে নিন।" },
  imageUrl: { en: "Image, picked from your media library.", bn: "ইমেজ — মিডিয়া লাইব্রেরি থেকে নিন।" },
  beforeImage: { en: "The 'before' photo. Unretouched images only.", bn: "‘আগে’-র ছবি — রিটাচ করা নয়।" },
  afterImage: { en: "The 'after' photo, shot under the same lighting.", bn: "‘পরে’-র ছবি — একই আলোতে তোলা।" },
  q1Multiple: { en: "Allows more than one answer at this step.", bn: "এই ধাপে একাধিক উত্তর দেওয়া যাবে।" },
  q2Multiple: { en: "Allows more than one answer at this step.", bn: "এই ধাপে একাধিক উত্তর দেওয়া যাবে।" },
  q3Multiple: { en: "Allows more than one answer at this step.", bn: "এই ধাপে একাধিক উত্তর দেওয়া যাবে।" },
  // Phase 7 — layout primitive pack.
  variant: { en: "Button style: primary, secondary, outline, ghost or text link.", bn: "বাটনের স্টাইল — প্রাইমারি, সেকেন্ডারি, আউটলাইন, ঘোস্ট বা টেক্সট লিংক।" },
  icon: { en: "Optional icon shown after the button or icon widget label.", bn: "বাটন বা আইকন উইজেটের লেবেলের পর ঐচ্ছিক আইকন।" },
  fullWidth: { en: "Stretches the button to the full width of its container.", bn: "বাটনটি কনটেইনারের পূর্ণ প্রস্থে ছড়িয়ে দেয়।" },
  newTab: { en: "Opens the link in a new tab.", bn: "লিংক নতুন ট্যাবে খোলে।" },
  name: { en: "Which icon from the platform set to display.", bn: "প্ল্যাটফর্ম সেট থেকে কোন আইকন দেখাবে।" },
  showPhone: { en: "Adds a phone number field to the contact form.", bn: "যোগাযোগ ফর্মে ফোন নম্বর ফিল্ড যোগ করে।" },
  items: { en: "Repeatable menu links, each with a label and a destination.", bn: "পুনরাবৃত্তযোগ্য মেনু লিংক — প্রতিটিতে লেবেল ও গন্তব্য।" },
  slides: { en: "Repeatable carousel slides, each with an image and caption.", bn: "পুনরাবৃত্তযোগ্য ক্যারোসেল স্লাইড — প্রতিটিতে ইমেজ ও ক্যাপশন।" },
  perView: { en: "How many slides are visible at once.", bn: "একসাথে কতটি স্লাইড দেখা যাবে।" },
  showArrows: { en: "Shows previous/next arrows when some slides are hidden.", bn: "কিছু স্লাইড লুকালে আগে/পরে তীর দেখায়।" },
};

/**
 * Families of generated keys (`i3Image`, `l2Href`, `r4c2`, `p1x`, `*_sizes`).
 * First match wins; the regex is tested against the raw prop key.
 */
export const PROP_HINT_PATTERNS: { test: RegExp; hint: BiText }[] = [
  { test: /_sizes$/, hint: { en: "How wide this image renders, so the browser downloads the right size.", bn: "ছবিটি কত চওড়ায় দেখাবে — ব্রাউজার সেই মাপেই ডাউনলোড করবে।" } },
  { test: /_alt$/, hint: { en: "Describe the image for screen readers and search. Required before publish.", bn: "স্ক্রিন রিডার ও সার্চের জন্য ছবির বর্ণনা — প্রকাশের আগে বাধ্যতামূলক।" } },
  { test: /^[a-z]?\d?Image\d*$|^image\d+$/i, hint: { en: "Image slot. Keep every slot the same aspect ratio to avoid layout shift.", bn: "ইমেজ স্লট — লেআউট নড়া এড়াতে সব স্লটে একই অনুপাত রাখুন।" } },
  { test: /Href\d*$|^[a-z]\dHref$/, hint: { en: "Link target. A /relative path keeps the shopper on this store.", bn: "লিংক গন্তব্য — /relative পাথ দিলে ক্রেতা স্টোরেই থাকে।" } },
  { test: /^p\d[xy]$/, hint: { en: "Hotspot position as a percentage of the image, so it survives any width.", bn: "ছবির শতাংশ হিসেবে হটস্পটের অবস্থান — যেকোনো প্রস্থে ঠিক থাকে।" } },
  { test: /^r\dc\d$/, hint: { en: "Measurement cell, in centimetres. Leave blank to hide the row.", bn: "মাপের ঘর (সেন্টিমিটার)। খালি রাখলে সারি লুকাবে।" } },
];
