-- Framique baseline schema (reconstructed from the generated type contract).
-- Enums, tables, keys, indexes, updated_at triggers, grants and RLS.

-- ============================ enums ============================
do $$ begin create type public.address_type as enum ('shipping', 'billing'); exception when duplicate_object then null; end $$;
do $$ begin create type public.ai_channel as enum ('widget', 'admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.ai_conversation_status as enum ('open', 'needs_agent', 'resolved', 'closed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.ai_message_role as enum ('customer', 'bot', 'agent'); exception when duplicate_object then null; end $$;
do $$ begin create type public.api_key_env as enum ('test', 'live'); exception when duplicate_object then null; end $$;
do $$ begin create type public.approval_status as enum ('pending', 'approved', 'rejected', 'expired', 'cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.billing_plan as enum ('launch', 'growth', 'business', 'enterprise'); exception when duplicate_object then null; end $$;
do $$ begin create type public.catalog_status as enum ('draft', 'active', 'archived'); exception when duplicate_object then null; end $$;
do $$ begin create type public.charge_intent_status as enum ('initiated', 'pending', 'paid', 'failed', 'expired', 'cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.cod_recon_status as enum ('pending', 'matched', 'variance', 'cleared'); exception when duplicate_object then null; end $$;
do $$ begin create type public.consent_channel as enum ('email', 'sms', 'push'); exception when duplicate_object then null; end $$;
do $$ begin create type public.consent_purpose as enum ('marketing', 'cart_recovery', 'stock_alerts'); exception when duplicate_object then null; end $$;
do $$ begin create type public.coupon_status as enum ('draft', 'active', 'paused', 'expired'); exception when duplicate_object then null; end $$;
do $$ begin create type public.coupon_type as enum ('fixed', 'percent', 'bogo', 'free_shipping'); exception when duplicate_object then null; end $$;
do $$ begin create type public.export_job_status as enum ('queued', 'generating', 'signing', 'ready_for_download', 'downloaded', 'expired', 'fail_retry'); exception when duplicate_object then null; end $$;
do $$ begin create type public.export_object_type as enum ('orders', 'products', 'customers', 'product_events', 'analytics_raw'); exception when duplicate_object then null; end $$;
do $$ begin create type public.fraud_blacklist_kind as enum ('phone', 'email'); exception when duplicate_object then null; end $$;
do $$ begin create type public.fraud_case_status as enum ('open', 'evidence_requested', 'approved', 'rejected'); exception when duplicate_object then null; end $$;
do $$ begin create type public.invoice_status as enum ('open', 'paid', 'past_due', 'void'); exception when duplicate_object then null; end $$;
do $$ begin create type public.kyc_state as enum ('pending', 'submitted', 'verified', 'rejected'); exception when duplicate_object then null; end $$;
do $$ begin create type public.kyc_status as enum ('pending', 'verified', 'rejected'); exception when duplicate_object then null; end $$;
do $$ begin create type public.market_install_status as enum ('installed', 'trial', 'paused', 'rolled_back'); exception when duplicate_object then null; end $$;
do $$ begin create type public.market_kind as enum ('theme', 'widget'); exception when duplicate_object then null; end $$;
do $$ begin create type public.market_listing_status as enum ('draft', 'review', 'active', 'paused', 'archived'); exception when duplicate_object then null; end $$;
do $$ begin create type public.merchant_role as enum ('owner', 'admin', 'staff', 'viewer'); exception when duplicate_object then null; end $$;
do $$ begin create type public.merchant_status as enum ('active', 'suspended', 'pending'); exception when duplicate_object then null; end $$;
do $$ begin create type public.notification_severity as enum ('info', 'warning', 'critical'); exception when duplicate_object then null; end $$;
do $$ begin create type public.order_status as enum ('pending', 'payment_pending', 'confirmed', 'paid', 'fulfilled', 'cancelled', 'refunded', 'packed', 'shipped', 'delivered', 'refund_requested'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_method as enum ('cod', 'bkash', 'nagad', 'rocket'); exception when duplicate_object then null; end $$;
do $$ begin create type public.pos_order_status as enum ('local_pending', 'synced', 'paid', 'delivered', 'voided'); exception when duplicate_object then null; end $$;
do $$ begin create type public.pos_origin as enum ('offline', 'online'); exception when duplicate_object then null; end $$;
do $$ begin create type public.pos_payment_method as enum ('cash', 'card', 'cod'); exception when duplicate_object then null; end $$;
do $$ begin create type public.pos_session_status as enum ('open', 'closed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.product_kind as enum ('physical', 'digital', 'service', 'subscription'); exception when duplicate_object then null; end $$;
do $$ begin create type public.product_status as enum ('draft', 'active', 'archived'); exception when duplicate_object then null; end $$;
do $$ begin create type public.review_status as enum ('pending', 'published', 'rejected'); exception when duplicate_object then null; end $$;
do $$ begin create type public.settlement_file_status as enum ('received', 'parsed', 'matched', 'posted', 'rejected', 'variance_hold'); exception when duplicate_object then null; end $$;
do $$ begin create type public.shipment_status as enum ('created', 'pickup_scheduled', 'picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'failed_attempt', 'returned'); exception when duplicate_object then null; end $$;
do $$ begin create type public.staff_mfa_status as enum ('none', 'enrolled', 'enforced'); exception when duplicate_object then null; end $$;
do $$ begin create type public.staff_status as enum ('invited', 'active', 'suspended', 'removed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.subscription_status as enum ('trial', 'active', 'past_due', 'paused', 'cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.sync_status as enum ('pending', 'synced', 'failed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.abandoned_cart_status as enum ('active', 'recovered', 'lost'); exception when duplicate_object then null; end $$;
do $$ begin create type public.cod_settlement_state as enum ('pending', 'matched', 'mismatch', 'settled', 'written_off'); exception when duplicate_object then null; end $$;
do $$ begin create type public.courier_event_status as enum ('processed', 'duplicate', 'rejected', 'dead_letter', 'replayed'); exception when duplicate_object then null; end $$;
do $$ begin create type public.dispute_status as enum ('open', 'evidence_submitted', 'won', 'lost', 'withdrawn'); exception when duplicate_object then null; end $$;
do $$ begin create type public.fulfilment_status as enum ('pending', 'packed', 'shipped', 'delivered', 'cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.gift_card_status as enum ('active', 'redeemed', 'expired', 'void'); exception when duplicate_object then null; end $$;
do $$ begin create type public.return_status as enum ('requested', 'approved', 'rejected', 'received', 'refunded', 'cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.seo_entity_type as enum ('store', 'product', 'collection', 'page', 'article'); exception when duplicate_object then null; end $$;
do $$ begin create type public.transfer_status as enum ('draft', 'in_transit', 'received', 'cancelled'); exception when duplicate_object then null; end $$;

-- ======================= shared utilities =======================
create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end $$;

create or replace function public.is_platform_admin(_user_id uuid default auth.uid())
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.platform_admins pa where pa.user_id = _user_id)
$$;

create or replace function public.is_merchant_member(_merchant_id uuid, _user_id uuid default auth.uid())
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.merchant_members m
    where m.merchant_id = _merchant_id and m.user_id = _user_id and m.status = 'active'
  )
$$;

create or replace function public.is_merchant_admin(_merchant_id uuid, _user_id uuid default auth.uid())
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.merchant_members m
    where m.merchant_id = _merchant_id and m.user_id = _user_id
      and m.status = 'active' and m.role in ('owner','admin')
  )
$$;

grant execute on function public.is_platform_admin(uuid) to authenticated, service_role;
grant execute on function public.is_merchant_member(uuid, uuid) to authenticated, service_role;
grant execute on function public.is_merchant_admin(uuid, uuid) to authenticated, service_role;
create table if not exists public.auth_events (created_at timestamptz default now() not null, detail jsonb default '{}'::jsonb not null, email_hash text, event text not null, id uuid default gen_random_uuid() not null, ip_hash text, outcome text not null, user_agent text, user_id uuid, primary key (id));
create table if not exists public.auth_sessions (aal text, created_at timestamptz default now() not null, device text, id uuid default gen_random_uuid() not null, ip_hash text, last_seen_at timestamptz default now() not null, revoked_at timestamptz, session_id uuid not null, user_id uuid not null, primary key (id));
create table if not exists public.fx_rates (base_currency text not null, created_at timestamptz default now() not null, effective_at timestamptz default now() not null, id uuid default gen_random_uuid() not null, quote_currency text not null, rate_ppm bigint not null, source text not null, primary key (id));
create table if not exists public.merchants (created_at timestamptz default now() not null, currency_code text default 'BDT' not null, id uuid default gen_random_uuid() not null, kyc_status public.kyc_status default 'pending'::public.kyc_status not null, name text not null, slug text not null, status public.merchant_status default 'active'::public.merchant_status not null, updated_at timestamptz default now() not null, vat_registration_no text, primary key (id));
create unique index if not exists merchants_slug_uq on public.merchants (slug);
create policy "merchants_read" on public.merchants for select to authenticated
  using (public.is_merchant_member(id) or public.is_platform_admin());
create policy "merchants_manage" on public.merchants for all to authenticated
  using (public.is_merchant_admin(id) or public.is_platform_admin())
  with check (public.is_merchant_admin(id) or public.is_platform_admin());
create table if not exists public.ops_backup_runs (artifact_ref text, checks jsonb default '{}'::jsonb not null, created_at timestamptz default now() not null, created_by uuid, finished_at timestamptz, id uuid default gen_random_uuid() not null, kind text not null, notes text, rows_verified bigint default 0 not null, scope text default '' not null, started_at timestamptz default now() not null, status text default '' not null, primary key (id));
create table if not exists public.ops_incidents (components text[] default '{}'::text[] not null, created_at timestamptz default now() not null, created_by uuid, id uuid default gen_random_uuid() not null, is_public boolean default false not null, resolved_at timestamptz, severity text default '' not null, started_at timestamptz default now() not null, status text default '' not null, title text not null, updated_at timestamptz default now() not null, primary key (id));
create table if not exists public.ops_retention_runs (cutoff text not null, deleted_rows bigint default 0 not null, id uuid default gen_random_uuid() not null, ran_at timestamptz default now() not null, table_name text not null, primary key (id));
create table if not exists public.ops_status_components (key text not null, label text not null, position bigint default 0 not null, state text default '' not null, updated_at timestamptz default now() not null);
create table if not exists public.order_status_transitions (from_status public.order_status not null, to_status public.order_status not null);
create table if not exists public.plan_definitions (active boolean default false not null, created_at timestamptz default now() not null, currency_code text default 'BDT' not null, feature_flags jsonb default '{}'::jsonb not null, features jsonb default '{}'::jsonb not null, payment_methods_allowed jsonb default '{}'::jsonb not null, plan public.billing_plan not null, price_minor_int bigint, products_limit bigint default 0 not null, sort_order bigint default 0 not null, staff_limit bigint default 0 not null, title_bn text not null, title_en text not null, trial_days bigint default 0 not null, updated_at timestamptz default now() not null);
create table if not exists public.platform_admins (created_at timestamptz default now() not null, user_id uuid not null, primary key (user_id));
create policy "platform_admins_read" on public.platform_admins for select to authenticated
  using (user_id = auth.uid() or public.is_platform_admin());
create table if not exists public.platform_audit_log (action text not null, actor text, after_data jsonb default '{}'::jsonb not null, before_data jsonb default '{}'::jsonb not null, created_at timestamptz default now() not null, entity text not null, entity_id uuid, id uuid default gen_random_uuid() not null, scope text default '' not null, primary key (id));
create table if not exists public.platform_flags (created_at timestamptz default now() not null, key text not null, updated_at timestamptz default now() not null, updated_by uuid, value jsonb default '{}'::jsonb not null);
create table if not exists public.profiles (created_at timestamptz default now() not null, email text, full_name text, id uuid not null, phone text, updated_at timestamptz default now() not null, primary key (id));
create table if not exists public.rate_limit_counters (bucket text not null, hits bigint default 0 not null, subject text not null, window_start text not null);
create table if not exists public.refund_status_transitions (from_status text not null, to_status text not null);
create table if not exists public.theme_registry (active boolean default false not null, category text default '' not null, created_at timestamptz default now() not null, key text not null, name_bn text not null, name_en text not null, preset jsonb default '{}'::jsonb not null, sort_order bigint default 0 not null, summary_bn text default '' not null, summary_en text default '' not null, updated_at timestamptz default now() not null, version text default '' not null);
create table if not exists public.trial_fingerprints (blocked boolean default false not null, fingerprint text not null, first_seen_at timestamptz default now() not null, last_seen_at timestamptz default now() not null, merchant_count bigint default 0 not null);
create table if not exists public.vat_rates (category text default '' not null, country_code text default '' not null, created_at timestamptz default now() not null, effective_year bigint not null, id uuid default gen_random_uuid() not null, rate_basis_points bigint not null, primary key (id));
create table if not exists public.activity_log (action text not null, actor text, changed jsonb default '{}'::jsonb not null, created_at timestamptz default now() not null, id bigint generated always as identity, merchant_id uuid not null, resource_id uuid, resource_type text not null, primary key (id));
alter table public.activity_log add constraint activity_log_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.api_keys (active boolean default false not null, created_at timestamptz default now() not null, created_by uuid, env public.api_key_env default 'test'::public.api_key_env not null, id uuid default gen_random_uuid() not null, key_hash text not null, last_used_at timestamptz, merchant_id uuid not null, name text not null, prefix text not null, revoked_at timestamptz, scopes jsonb default '{}'::jsonb not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.api_keys add constraint api_keys_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.approval_requests (created_at timestamptz default now() not null, expires_at timestamptz default now() not null, id uuid default gen_random_uuid() not null, merchant_id uuid not null, payload jsonb default '{}'::jsonb not null, resource_action text not null, resource_id uuid, resource_type text not null, review_comment text, reviewed_at timestamptz, reviewed_by uuid, status public.approval_status default 'pending'::public.approval_status not null, submitted_by uuid not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.approval_requests add constraint approval_requests_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.billing_events (actor text, created_at timestamptz default now() not null, event_type text not null, id uuid default gen_random_uuid() not null, merchant_id uuid not null, payload jsonb default '{}'::jsonb not null, primary key (id));
alter table public.billing_events add constraint billing_events_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.brands (created_at timestamptz default now() not null, deleted_at timestamptz, description text, id uuid default gen_random_uuid() not null, logo_url text, merchant_id uuid not null, name text not null, slug text not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.brands add constraint brands_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.carriers (adapter text default '' not null, api_mode text default '' not null, code text not null, config jsonb default '{}'::jsonb not null, created_at timestamptz default now() not null, cutoff_hour bigint default 0 not null, deleted_at timestamptz, enabled boolean default false not null, id uuid default gen_random_uuid() not null, merchant_id uuid not null, name text not null, sort_order bigint default 0 not null, supports_pickup boolean default false not null, supports_pudo boolean default false not null, updated_at timestamptz default now() not null, webhook_secret text default '' not null, primary key (id));
alter table public.carriers add constraint carriers_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.catalog_import_jobs (applied_at timestamptz, applied_summary jsonb, created_at timestamptz default now() not null, created_by uuid, diff jsonb default '{}'::jsonb not null, error text, file_name text default '' not null, id uuid default gen_random_uuid() not null, merchant_id uuid not null, row_count bigint default 0 not null, source_hash text not null, status text default '' not null, summary jsonb default '{}'::jsonb not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.catalog_import_jobs add constraint catalog_import_jobs_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.categories (created_at timestamptz default now() not null, deleted_at timestamptz, description text, id uuid default gen_random_uuid() not null, merchant_id uuid not null, name text not null, parent_id uuid, slug text not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.categories add constraint categories_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
alter table public.categories add constraint categories_parent_id_fkey foreign key (parent_id) references public.categories(id) on delete set null;
create table if not exists public.collections (created_at timestamptz default now() not null, deleted_at timestamptz, description text, id uuid default gen_random_uuid() not null, image_url text, is_published boolean default false not null, is_smart boolean default false not null, merchant_id uuid not null, name text not null, position bigint default 0 not null, rules jsonb default '{}'::jsonb not null, slug text not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.collections add constraint collections_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.consent_events (actor text, channel public.consent_channel not null, created_at timestamptz default now() not null, customer_id uuid, granted boolean not null, id uuid default gen_random_uuid() not null, merchant_id uuid not null, purpose public.consent_purpose not null, reason text, source text not null, subject_hash text, subscriber_id uuid, primary key (id));
alter table public.consent_events add constraint consent_events_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.coupons (allow_combine boolean default false not null, amount_minor_int bigint default 0 not null, batch_label text, buy_quantity bigint default 0 not null, code text not null, created_at timestamptz default now() not null, currency_code text default 'BDT' not null, deleted_at timestamptz, expires_at timestamptz, get_quantity bigint default 0 not null, id uuid default gen_random_uuid() not null, max_discount_minor_int bigint, merchant_id uuid not null, min_subtotal_minor_int bigint default 0 not null, one_per_order boolean default false not null, per_customer_limit bigint, percent_off bigint default 0 not null, priority bigint default 0 not null, redeemed_count bigint default 0 not null, starts_at timestamptz, status public.coupon_status default 'draft'::public.coupon_status not null, type public.coupon_type default 'fixed'::public.coupon_type not null, updated_at timestamptz default now() not null, usage_limit bigint, primary key (id));
alter table public.coupons add constraint coupons_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.customers (auth_uid text not null, created_at timestamptz default now() not null, deleted_at timestamptz, email text, id uuid default gen_random_uuid() not null, locale text default '' not null, merchant_id uuid not null, name text default '' not null, phone text, updated_at timestamptz default now() not null, primary key (id));
alter table public.customers add constraint customers_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.export_jobs (attempts bigint default 0 not null, created_at timestamptz default now() not null, downloaded_at timestamptz, error text, expires_at timestamptz, filters jsonb default '{}'::jsonb not null, finished_at timestamptz, format text default '' not null, id uuid default gen_random_uuid() not null, merchant_id uuid not null, object_type public.export_object_type not null, range_end text, range_start text, requested_by uuid, schema_version bigint default 0 not null, signed_url text, signed_url_expires_at timestamptz, size_bytes bigint default 0 not null, started_at timestamptz, status public.export_job_status default 'queued'::public.export_job_status not null, storage_path text, total_rows bigint default 0 not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.export_jobs add constraint export_jobs_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.fraud_blacklist (active boolean default false not null, created_at timestamptz default now() not null, created_by uuid, id uuid default gen_random_uuid() not null, kind public.fraud_blacklist_kind not null, merchant_id uuid not null, reason text, updated_at timestamptz default now() not null, value text not null, primary key (id));
alter table public.fraud_blacklist add constraint fraud_blacklist_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.fraud_rules (action text default '' not null, code text not null, created_at timestamptz default now() not null, deleted_at timestamptz, enabled boolean default false not null, id uuid default gen_random_uuid() not null, merchant_id uuid not null, params jsonb default '{}'::jsonb not null, precedence bigint default 0 not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.fraud_rules add constraint fraud_rules_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.gateway_accounts (active boolean default false not null, created_at timestamptz default now() not null, id uuid default gen_random_uuid() not null, merchant_id uuid not null, provider text not null, sandbox boolean default false not null, updated_at timestamptz default now() not null, webhook_secret text not null, primary key (id));
alter table public.gateway_accounts add constraint gateway_accounts_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.gift_cards (balance_minor_int bigint not null, code text not null, created_at timestamptz default now() not null, currency_code text default 'BDT' not null, expires_at timestamptz, id uuid default gen_random_uuid() not null, initial_minor_int bigint not null, issued_by uuid, merchant_id uuid not null, recipient_email text, recipient_phone text, status public.gift_card_status not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.gift_cards add constraint gift_cards_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.impersonation_grants (consent_at timestamptz, consent_by uuid, expires_at timestamptz not null, id uuid default gen_random_uuid() not null, last_used_at timestamptz, merchant_id uuid not null, reason text not null, requested_at timestamptz default now() not null, requested_by uuid not null, revoked_at timestamptz, revoked_by uuid, scope text default '' not null, use_count bigint default 0 not null, primary key (id));
alter table public.impersonation_grants add constraint impersonation_grants_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.inventory_locations (active boolean default false not null, address_line text, city text, code text not null, created_at timestamptz default now() not null, id uuid default gen_random_uuid() not null, is_default boolean default false not null, merchant_id uuid not null, name text not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.inventory_locations add constraint inventory_locations_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.invoices (created_at timestamptz default now() not null, currency_code text default 'BDT' not null, id uuid default gen_random_uuid() not null, idempotency_key text not null, invoice_number text not null, merchant_id uuid not null, paid_at timestamptz, period_end text not null, period_start text not null, plan public.billing_plan not null, status public.invoice_status default 'open'::public.invoice_status not null, subtotal_minor_int bigint default 0 not null, total_minor_int bigint default 0 not null, updated_at timestamptz default now() not null, vat_minor_int bigint default 0 not null, vat_rate_basis_points bigint default 0 not null, primary key (id));
alter table public.invoices add constraint invoices_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.local_transactions (attempts bigint default 0 not null, client_id uuid not null, created_at timestamptz default now() not null, error text, id uuid default gen_random_uuid() not null, merchant_id uuid not null, payload jsonb default '{}'::jsonb not null, status public.sync_status default 'pending'::public.sync_status not null, updated_at timestamptz default now() not null, primary key (id));
alter table public.local_transactions add constraint local_transactions_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.marketplace_themes (category text default '' not null, compatible_versions jsonb default '{}'::jsonb not null, created_at timestamptz default now() not null, currency_code text default 'BDT' not null, description text, id uuid default gen_random_uuid() not null, install_count bigint default 0 not null, manifest jsonb default '{}'::jsonb not null, name text not null, price_minor_int bigint default 0 not null, rating_count bigint default 0 not null, rating_sum bigint default 0 not null, seller_merchant_id uuid not null, slug text not null, status public.market_listing_status default 'draft'::public.market_listing_status not null, thumbnail_url text, trial_allowed boolean default false not null, updated_at timestamptz default now() not null, vendor_name text default '' not null, version text default '' not null, version_history jsonb default '{}'::jsonb not null, primary key (id));
alter table public.marketplace_themes add constraint marketplace_themes_seller_merchant_id_fkey foreign key (seller_merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.marketplace_widgets (category text default '' not null, compatible_versions jsonb default '{}'::jsonb not null, created_at timestamptz default now() not null, currency_code text default 'BDT' not null, description text, id uuid default gen_random_uuid() not null, install_count bigint default 0 not null, manifest jsonb default '{}'::jsonb not null, name text not null, price_minor_int bigint default 0 not null, rating_count bigint default 0 not null, rating_sum bigint default 0 not null, registry_id uuid not null, seller_merchant_id uuid not null, slug text not null, status public.market_listing_status default 'draft'::public.market_listing_status not null, thumbnail_url text, trial_allowed boolean default false not null, updated_at timestamptz default now() not null, vendor_name text default '' not null, version text default '' not null, version_history jsonb default '{}'::jsonb not null, primary key (id));
alter table public.marketplace_widgets add constraint marketplace_widgets_seller_merchant_id_fkey foreign key (seller_merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.media_assets (alt_text text, content_type text default '' not null, created_at timestamptz default now() not null, deleted_at timestamptz, file_name text not null, id uuid default gen_random_uuid() not null, merchant_id uuid not null, size_bytes bigint default 0 not null, storage_path text not null, updated_at timestamptz default now() not null, url text not null, primary key (id));
alter table public.media_assets add constraint media_assets_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.merchant_kyc (bin_no text, contact_phone text, created_at timestamptz default now() not null, document_paths jsonb default '{}'::jsonb not null, id uuid default gen_random_uuid() not null, legal_name text, merchant_id uuid not null, rejection_reason text, reviewed_at timestamptz, reviewed_by uuid, state public.kyc_state default 'pending'::public.kyc_state not null, submitted_at timestamptz, trade_license_no text, updated_at timestamptz default now() not null, primary key (id));
alter table public.merchant_kyc add constraint merchant_kyc_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.merchant_settings (business_bin text, cod_enabled boolean default false not null, cod_surcharge_minor_int bigint default 0 not null, created_at timestamptz default now() not null, free_shipping_threshold_minor_int bigint, low_stock_threshold bigint default 0 not null, merchant_id uuid not null, mfs_enabled boolean default false not null, notify_prefs jsonb default '{}'::jsonb not null, prices_include_vat boolean default false not null, setup_dismissed_at timestamptz, setup_steps jsonb default '{}'::jsonb not null, ship_address_line text, ship_city text, ship_postcode text, shipping_flat_minor_int bigint default 0 not null, support_email text, support_phone text, tagline text, updated_at timestamptz default now() not null);
alter table public.merchant_settings add constraint merchant_settings_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
create table if not exists public.merchant_suspensions (id uuid default gen_random_uuid() not null, merchant_id uuid not null, payments_frozen boolean default false not null, reason text not null, reinstate_note text, reinstated_at timestamptz, reinstated_by uuid, suspended_at timestamptz default now() not null, suspended_by uuid not null, primary key (id));
alter table public.merchant_suspensions add constraint merchant_suspensions_merchant_id_fkey foreign key (merchant_id) references public.merchants(id) on delete cascade;
