/**
 * Phase 14 — widget catalogue.
 *
 * Mirrors free Elementor's element panel: collapsible categories, a search box
 * that matches label *and* keywords, and locked cards for elements that need a
 * connected storefront. Every entry knows its own defaults so "drag in and it
 * already looks right" holds.
 */
import type { NodeSettings, StudioNode } from "./model";
import { uid } from "./model";

export type WidgetCategory =
  "layout" | "basic" | "general" | "media" | "commerce" | "advanced";

export const CATEGORY_ORDER: WidgetCategory[] = [
  "layout",
  "basic",
  "general",
  "media",
  "commerce",
  "advanced",
];

export const CATEGORY_LABEL: Record<WidgetCategory, string> = {
  layout: "Layout",
  basic: "Basic",
  general: "General",
  media: "Media",
  commerce: "Commerce",
  advanced: "Advanced",
};

export type WidgetDef = {
  key: string;
  label: string;
  category: WidgetCategory;
  /** lucide-react icon name, resolved by the panel. */
  icon: string;
  keywords: string[];
  /** Needs a connected storefront; card renders greyed with a lock. */
  locked?: boolean;
  container?: boolean;
  defaults: NodeSettings;
};

const text = (value: string) => ({ text: value });

export const WIDGETS: WidgetDef[] = [
  {
    key: "container",
    label: "Container",
    category: "layout",
    icon: "Square",
    keywords: ["flex", "section", "div", "wrapper"],
    container: true,
    defaults: {
      layout: "flex",
      direction: "column",
      gap: 20,
      contentWidth: "boxed",
      paddingY: 40,
      paddingX: 16,
    },
  },
  {
    key: "grid",
    label: "Grid",
    category: "layout",
    icon: "LayoutGrid",
    keywords: ["columns", "rows", "layout"],
    container: true,
    defaults: {
      layout: "grid",
      columns: 3,
      gap: 20,
      contentWidth: "boxed",
      paddingY: 40,
      paddingX: 16,
    },
  },
  {
    key: "heading",
    label: "Heading",
    category: "basic",
    icon: "Heading",
    keywords: ["title", "h1", "h2", "headline"],
    defaults: {
      text: "Add your heading text",
      level: 2,
      fontSize: 32,
      fontWeight: 700,
      textAlign: "left",
    },
  },
  {
    key: "text",
    label: "Text",
    category: "basic",
    icon: "Type",
    keywords: ["paragraph", "copy", "body"],
    defaults: {
      text: "Write something your customers need to know.",
      fontSize: 16,
      textAlign: "left",
    },
  },
  {
    key: "text-editor",
    label: "Text editor",
    category: "basic",
    icon: "AlignLeft",
    keywords: ["rich", "wysiwyg", "paragraph"],
    defaults: {
      text: "Rich text block. Use the toolbar to format.",
      fontSize: 16,
    },
  },
  {
    key: "image",
    label: "Image",
    category: "basic",
    icon: "Image",
    keywords: ["photo", "picture", "media"],
    defaults: { url: "", alt: "", radius: 12, textAlign: "center", width: 100 },
  },
  {
    key: "video",
    label: "Video",
    category: "media",
    icon: "Video",
    keywords: ["youtube", "vimeo", "embed", "player"],
    defaults: { url: "", title: "Video", ratio: "16:9" },
  },
  {
    key: "button",
    label: "Button",
    category: "basic",
    icon: "MousePointerClick",
    keywords: ["cta", "link", "action"],
    defaults: {
      label: "Shop now",
      href: "/products",
      variant: "primary",
      size: "md",
      textAlign: "left",
    },
  },
  {
    key: "divider",
    label: "Divider",
    category: "basic",
    icon: "Minus",
    keywords: ["hr", "line", "separator"],
    defaults: { style: "solid", weight: 1, width: 100, textAlign: "center" },
  },
  {
    key: "spacer",
    label: "Spacer",
    category: "basic",
    icon: "MoveVertical",
    keywords: ["gap", "space", "margin"],
    defaults: { height: 40 },
  },
  {
    key: "map",
    label: "Google Maps",
    category: "media",
    icon: "MapPin",
    keywords: ["location", "address", "map"],
    defaults: { query: "Dhaka, Bangladesh", zoom: 12, height: 320 },
  },
  {
    key: "icon",
    label: "Icon",
    category: "general",
    icon: "Star",
    keywords: ["symbol", "glyph"],
    defaults: { icon: "Star", size: 40, textAlign: "center", color: "" },
  },
  {
    key: "tabs",
    label: "Tabs",
    category: "general",
    icon: "PanelTop",
    keywords: ["tabbed", "panels"],
    defaults: {
      items: [
        { title: "Tab one", content: "Content for the first tab." },
        { title: "Tab two", content: "Content for the second tab." },
      ],
    },
  },
  {
    key: "accordion",
    label: "Accordion",
    category: "general",
    icon: "Rows3",
    keywords: ["faq", "collapse", "expand"],
    defaults: {
      items: [
        {
          title: "How long is delivery?",
          content: "Inside Dhaka 24–48 hours.",
        },
        { title: "Can I return an item?", content: "Yes, within 7 days." },
      ],
    },
  },
  {
    key: "toggle",
    label: "Toggle",
    category: "general",
    icon: "ChevronsUpDown",
    keywords: ["collapse", "show", "hide"],
    defaults: {
      items: [{ title: "Read more", content: "Extra detail lives here." }],
    },
  },
  {
    key: "image-box",
    label: "Image box",
    category: "general",
    icon: "GalleryVerticalEnd",
    keywords: ["card", "feature", "picture"],
    defaults: {
      url: "",
      title: "Feature title",
      text: "One line about this feature.",
      textAlign: "center",
    },
  },
  {
    key: "icon-box",
    label: "Icon box",
    category: "general",
    icon: "BadgeCheck",
    keywords: ["feature", "benefit", "usp"],
    defaults: {
      icon: "BadgeCheck",
      title: "Free delivery",
      text: "On every order over ৳2,000.",
      textAlign: "center",
    },
  },
  {
    key: "carousel",
    label: "Image carousel",
    category: "media",
    icon: "GalleryHorizontal",
    keywords: ["slider", "gallery", "swipe"],
    defaults: { items: [], perView: 3, gap: 16 },
  },
  {
    key: "gallery",
    label: "Basic gallery",
    category: "media",
    icon: "Images",
    keywords: ["grid", "photos"],
    defaults: { items: [], columns: 3, gap: 12 },
  },
  {
    key: "icon-list",
    label: "Icon list",
    category: "general",
    icon: "List",
    keywords: ["bullets", "checklist", "features"],
    defaults: {
      icon: "Check",
      items: [
        { text: "Cash on delivery" },
        { text: "Free returns" },
        { text: "48h dispatch" },
      ],
    },
  },
  {
    key: "counter",
    label: "Counter",
    category: "general",
    icon: "Hash",
    keywords: ["number", "stat", "metric"],
    defaults: {
      start: 0,
      end: 1200,
      prefix: "",
      suffix: "+",
      title: "Happy customers",
      textAlign: "center",
    },
  },
  {
    key: "progress",
    label: "Progress bar",
    category: "general",
    icon: "Gauge",
    keywords: ["bar", "percent", "skill"],
    defaults: { title: "Order fulfilment", percent: 82, showPercent: true },
  },
  {
    key: "testimonial",
    label: "Testimonial",
    category: "general",
    icon: "Quote",
    keywords: ["review", "quote", "customer"],
    defaults: {
      text: "This store made ordering effortless.",
      author: "Nusrat A.",
      role: "Verified buyer",
      textAlign: "left",
    },
  },
  {
    key: "social",
    label: "Social icons",
    category: "general",
    icon: "Share2",
    keywords: ["facebook", "instagram", "links"],
    defaults: {
      items: [
        { network: "facebook", href: "https://facebook.com" },
        { network: "instagram", href: "https://instagram.com" },
      ],
      textAlign: "left",
    },
  },
  {
    key: "alert",
    label: "Alert",
    category: "general",
    icon: "TriangleAlert",
    keywords: ["notice", "warning", "info"],
    defaults: {
      tone: "info",
      title: "Heads up",
      text: "Delivery may take an extra day during Eid.",
    },
  },
  {
    key: "html",
    label: "HTML",
    category: "advanced",
    icon: "Code",
    keywords: ["embed", "custom", "script"],
    defaults: { html: "<p>Custom markup</p>" },
  },
  {
    key: "app-block",
    label: "App block",
    category: "advanced",
    icon: "Blocks",
    keywords: ["shortcode", "plugin", "widget"],
    defaults: { pluginKey: "", height: 320 },
  },
  {
    key: "anchor",
    label: "Menu anchor",
    category: "advanced",
    icon: "Anchor",
    keywords: ["jump", "scroll", "id"],
    defaults: { anchorId: "section" },
  },
  {
    key: "read-more",
    label: "Read more",
    category: "advanced",
    icon: "TextCursorInput",
    keywords: ["excerpt", "cut", "teaser"],
    defaults: {},
  },
  {
    key: "rating",
    label: "Rating",
    category: "general",
    icon: "Star",
    keywords: ["stars", "score", "review"],
    defaults: { value: 4.5, max: 5, textAlign: "left" },
  },
  {
    key: "text-path",
    label: "Text path",
    category: "advanced",
    icon: "Spline",
    keywords: ["curve", "circle", "svg"],
    defaults: { text: "Handmade in Bangladesh", path: "circle", size: 200 },
  },
  ...(
    [
      ["products", "Products", "ShoppingBag", ["catalogue", "grid", "shop"]],
      [
        "product-categories",
        "Product categories",
        "Tags",
        ["collections", "taxonomy"],
      ],
      ["add-to-cart", "Add to cart", "ShoppingCart", ["buy", "purchase"]],
      ["cart", "Cart", "ShoppingCart", ["basket", "bag"]],
      ["checkout", "Checkout", "CreditCard", ["pay", "order"]],
      ["menu-cart", "Menu cart", "ShoppingBasket", ["mini cart", "header"]],
      ["reviews", "Reviews", "MessageSquareQuote", ["ratings", "feedback"]],
    ] as const
  ).map(([key, label, icon, keywords]) => ({
    key,
    label,
    category: "commerce" as WidgetCategory,
    icon,
    keywords: [...keywords],
    locked: false,
    defaults: { source: "auto", limit: 8, columns: 4 } as NodeSettings,
  })),
  // Ported from the theme engine so page builders get the same storefront
  // vocabulary (flat scalar props mirror the theme defaults exactly).
  {
    key: "faq",
    label: "FAQ",
    category: "general",
    icon: "CircleHelp",
    keywords: ["faq", "questions", "answers", "accordion", "help"],
    defaults: {
      heading: "Frequently asked",
      q1: "",
      a1: "",
      q2: "",
      a2: "",
      q3: "",
      a3: "",
      items: [],
    },
  },
  {
    key: "marquee",
    label: "Marquee",
    category: "general",
    icon: "Megaphone",
    keywords: ["marquee", "ticker", "scrolling", "announcement"],
    defaults: { text: "New arrivals every week", speed: 30, pauseOnHover: true },
  },
  {
    key: "countdown",
    label: "Countdown",
    category: "general",
    icon: "Timer",
    keywords: ["countdown", "timer", "offer", "deal", "urgency"],
    defaults: { label: "Offer ends in", endsAt: "" },
  },
  {
    key: "banner",
    label: "Banner",
    category: "general",
    icon: "Flag",
    keywords: ["banner", "announcement", "notice", "message"],
    defaults: { text: "Free delivery over BDT 2,000", tone: "info" },
  },
  {
    key: "trust_bar",
    label: "Trust bar",
    category: "general",
    icon: "ShieldCheck",
    keywords: ["trust", "badges", "delivery", "returns", "payment"],
    defaults: {
      i1Icon: "delivery",
      i1Title: "Fast delivery",
      i1Body: "",
      i2Icon: "returns",
      i2Title: "Easy returns",
      i2Body: "",
      i3Icon: "secure",
      i3Title: "Secure payment",
      i3Body: "",
      i4Icon: "support",
      i4Title: "",
      i4Body: "",
      items: [],
    },
  },
  {
    key: "announcement_bar",
    label: "Announcement bar",
    category: "general",
    icon: "BadgeCheck",
    keywords: ["announcement", "rotating", "messages", "header", "promo"],
    defaults: {
      m1: "Free delivery over BDT 2,000",
      m2: "",
      m3: "",
      href: "",
      dismissible: true,
      rotateMs: 6000,
      items: [],
    },
  },
  // Heritage + hero batch: flat scalar props mirror the theme defaults, so
  // what merchants author in the theme studio renders identically here.
  {
    key: "heritage_story",
    label: "Heritage story",
    category: "general",
    icon: "Landmark",
    keywords: ["heritage", "story", "craft", "artisan", "about"],
    defaults: { image: "", headline: "", body: "", ctaLabel: "", ctaUrl: "", layout: "image-left" },
  },
  {
    key: "editorial_banner",
    label: "Editorial banner",
    category: "general",
    icon: "Newspaper",
    keywords: ["editorial", "banner", "feature", "wide", "cta"],
    defaults: { image: "", headline: "", subhead: "", ctaLabel: "", ctaUrl: "" },
  },
  {
    key: "editorial_hero",
    label: "Editorial hero",
    category: "general",
    icon: "Sparkles",
    keywords: ["hero", "editorial", "season", "collection", "split"],
    defaults: {
      eyebrow: "",
      heading: "The new season",
      body: "",
      ctaLabel: "Shop the collection",
      ctaHref: "",
      imageUrl: "",
      layout: "stacked",
      scrim: true,
    },
  },
  {
    key: "lookbook",
    label: "Lookbook",
    category: "general",
    icon: "Images",
    keywords: ["lookbook", "gallery", "editorial", "fashion", "offset"],
    defaults: {
      heading: "Lookbook",
      i1Image: "",
      i1Alt: "",
      i1Href: "",
      i2Image: "",
      i2Alt: "",
      i2Href: "",
      i3Image: "",
      i3Alt: "",
      i3Href: "",
      i4Image: "",
      i4Alt: "",
      i4Href: "",
      offset: true,
      items: [],
    },
  },
  {
    key: "hero",
    label: "Hero",
    category: "general",
    icon: "PanelTop",
    keywords: ["hero", "slides", "welcome", "cta", "banner"],
    defaults: {
      heading: "Welcome to our store",
      subheading: "",
      ctaLabel: "",
      ctaHref: "",
      align: "left",
      image: "",
      s2Heading: "",
      s2Image: "",
      s3Heading: "",
      s3Image: "",
      items: [],
    },
  },
  {
    key: "textile_showcase",
    label: "Textile showcase",
    category: "general",
    icon: "Shirt",
    keywords: ["textile", "showcase", "fabric", "products", "craft"],
    defaults: { headline: "", items: [] },
  },
  {
    key: "department_grid",
    label: "Department grid",
    category: "general",
    icon: "LayoutGrid",
    keywords: ["departments", "categories", "grid", "shop"],
    defaults: { departments: [], columns: 4 },
  },
  {
    key: "story_trunk",
    label: "Story trunk",
    category: "general",
    icon: "History",
    keywords: ["story", "timeline", "trunk", "history", "years"],
    defaults: { headline: "", items: [] },
  },
  {
    key: "marquee_strip",
    label: "Marquee strip",
    category: "general",
    icon: "MoveHorizontal",
    keywords: ["marquee", "strip", "ticker", "scrolling"],
    defaults: { items: [], speed: "normal" },
  },
  {
    key: "hero_carousel",
    label: "Hero carousel",
    category: "general",
    icon: "GalleryHorizontal",
    keywords: ["hero", "carousel", "slides", "slider"],
    defaults: { slides: [], autoAdvanceMs: 5000 },
  },
  {
    key: "testimonial_carousel",
    label: "Testimonial carousel",
    category: "general",
    icon: "MessagesSquare",
    keywords: ["testimonials", "reviews", "carousel", "quotes"],
    defaults: { testimonials: [], autoAdvanceMs: 6000 },
  },
  {
    key: "feature_row",
    label: "Feature row",
    category: "general",
    icon: "LayoutList",
    keywords: ["features", "benefits", "three", "strip"],
    defaults: {
      itemOne: "Cash on delivery",
      itemTwo: "Mobile payments",
      itemThree: "Nationwide shipping",
    },
  },
  {
    key: "utility_bar",
    label: "Utility bar",
    category: "general",
    icon: "SlidersHorizontal",
    keywords: ["utility", "topbar", "links", "language", "header"],
    defaults: {
      note: "",
      l1Label: "",
      l1Href: "",
      l2Label: "",
      l2Href: "",
      l3Label: "",
      l3Href: "",
      showLanguage: true,
    },
  },
  {
    key: "footer_sitemap",
    label: "Footer sitemap",
    category: "general",
    icon: "FolderTree",
    keywords: ["footer", "sitemap", "links", "columns"],
    defaults: {
      c1Title: "Shop",
      c1Links: "New in|/, Best sellers|/",
      c2Title: "Help",
      c2Links: "Contact|/, Shipping|/",
      c3Title: "About",
      c3Links: "",
      c4Title: "",
      c4Links: "",
      items: [],
    },
  },
  {
    key: "doc_links",
    label: "Tech documents",
    category: "general",
    icon: "FileText",
    keywords: ["docs", "manual", "pdf", "downloads", "spec"],
    defaults: {
      heading: "Documents",
      d1Label: "User manual",
      d1Href: "",
      d1Meta: "PDF",
      d2Label: "",
      d2Href: "",
      d2Meta: "",
      d3Label: "",
      d3Href: "",
      d3Meta: "",
      d4Label: "",
      d4Href: "",
      d4Meta: "",
    },
  },
  {
    key: "claim_chips",
    label: "Claim chips",
    category: "general",
    icon: "Award",
    keywords: ["claims", "certified", "badges", "proof", "chips"],
    defaults: {
      heading: "Tested & certified",
      c1Label: "",
      c1Source: "",
      c2Label: "",
      c2Source: "",
      c3Label: "",
      c3Source: "",
      c4Label: "",
      c4Source: "",
      c5Label: "",
      c5Source: "",
      c6Label: "",
      c6Source: "",
    },
  },
  {
    key: "texture_strip",
    label: "Texture strip",
    category: "general",
    icon: "Palette",
    keywords: ["texture", "finish", "swatches", "shades", "gallery"],
    defaults: {
      heading: "Texture & finish",
      t1Image: "",
      t1Label: "",
      t1Alt: "",
      t2Image: "",
      t2Label: "",
      t2Alt: "",
      t3Image: "",
      t3Label: "",
      t3Alt: "",
      t4Image: "",
      t4Label: "",
      t4Alt: "",
    },
  },
  {
    key: "split_feature",
    label: "Split feature",
    category: "general",
    icon: "Columns2",
    keywords: ["split", "feature", "image", "text", "two-column"],
    defaults: {
      eyebrow: "",
      heading: "Made to last",
      body: "",
      ctaLabel: "",
      ctaHref: "",
      imageUrl: "",
      imageAlt: "",
      flip: false,
    },
  },
  {
    key: "notice",
    label: "Notice",
    category: "general",
    icon: "Bell",
    keywords: ["notice", "message", "dismissible", "tone", "banner"],
    defaults: { text: "", tone: "info", dismissible: false },
  },
  {
    key: "empty_state",
    label: "Empty state",
    category: "general",
    icon: "PackageOpen",
    keywords: ["empty", "no results", "filters", "clear", "search"],
    defaults: {
      heading: "Nothing matches those filters",
      body: "Try removing a filter or searching for something else.",
      clearLabel: "Clear all filters",
      showSuggestions: true,
      limit: 4,
    },
  },
  {
    key: "breadcrumb",
    label: "Breadcrumb",
    category: "general",
    icon: "ChevronsRight",
    keywords: ["breadcrumb", "trail", "navigation", "home", "path"],
    defaults: { homeLabel: "Home" },
  },
  {
    key: "brand_strip",
    label: "Brand strip",
    category: "general",
    icon: "Store",
    keywords: ["brands", "strip", "logos", "taxonomy"],
    defaults: { heading: "Shop by brand", limit: 12, columns: 4, kind: "brand" },
  },
  {
    key: "subbrand_bar",
    label: "Sub-brand bar",
    category: "general",
    icon: "Layers",
    keywords: ["subbrand", "brands", "family", "header", "tagline"],
    defaults: {
      activeBrand: "Aarong",
      tagline: "A Social Enterprise",
      b1Name: "Aarong",
      b1Href: "/",
      b2Name: "Taaga",
      b2Href: "/collections/taaga",
      b3Name: "Taaga Man",
      b3Href: "/collections/taaga-man",
      b4Name: "Herstory",
      b4Href: "/collections/herstory",
      b5Name: "Grassroots",
      b5Href: "/pages/grassroots",
    },
  },
  {
    key: "support_strip",
    label: "Support strip",
    category: "general",
    icon: "LifeBuoy",
    keywords: ["support", "help", "hotline", "contact", "service"],
    defaults: {
      heading: "Support",
      t1Title: "Hotline",
      t1Body: "",
      t1Href: "",
      t2Title: "WhatsApp",
      t2Body: "",
      t2Href: "",
      t3Title: "Service centre",
      t3Body: "",
      t3Href: "",
      t4Title: "Returns",
      t4Body: "",
      t4Href: "",
    },
  },
  {
    key: "social_strip",
    label: "Social strip",
    category: "general",
    icon: "AtSign",
    keywords: ["social", "instagram", "gallery", "feed", "photos"],
    defaults: {
      heading: "@yourstore",
      href: "",
      i1Image: "",
      i2Image: "",
      i3Image: "",
      i4Image: "",
      i5Image: "",
      i6Image: "",
    },
  },
  {
    key: "logo",
    label: "Logo",
    category: "general",
    icon: "Badge",
    keywords: ["logo", "brand", "wordmark", "header", "image"],
    defaults: { image: "", alt: "", text: "", href: "/", height: 40 },
  },
  {
    key: "how_to_use",
    label: "How to use",
    category: "general",
    icon: "ListOrdered",
    keywords: ["how to", "steps", "instructions", "usage", "guide"],
    defaults: {
      heading: "How to use",
      s1Title: "",
      s1Body: "",
      s2Title: "",
      s2Body: "",
      s3Title: "",
      s3Body: "",
      s4Title: "",
      s4Body: "",
      s5Title: "",
      s5Body: "",
      author: "",
      authorRole: "",
      reviewedBy: "",
      reviewedOn: "",
    },
  },
  {
    key: "buying_guide",
    label: "Buying guide",
    category: "general",
    icon: "BookOpen",
    keywords: ["buying", "guide", "how to choose", "advice", "links"],
    defaults: {
      heading: "How to choose",
      body: "",
      l1Label: "",
      l1Href: "",
      l2Label: "",
      l2Href: "",
      l3Label: "",
      l3Href: "",
      l4Label: "",
      l4Href: "",
      author: "",
      authorRole: "",
      reviewedBy: "",
      reviewedOn: "",
    },
  },
  {
    key: "care_panel",
    label: "Material & care",
    category: "general",
    icon: "Shirt",
    keywords: ["care", "material", "composition", "fabric", "origin"],
    defaults: {
      heading: "Material & care",
      composition: "",
      care: "",
      origin: "",
      open: false,
    },
  },
  {
    key: "safety_note",
    label: "Safety note",
    category: "general",
    icon: "ShieldAlert",
    keywords: ["safety", "patch test", "warning", "caution", "beauty"],
    defaults: {
      heading: "Patch test first",
      body: "Apply a small amount to the inner arm and wait 24 hours before full use.",
      howTo: "",
      howToLabel: "How to patch test",
    },
  },
  {
    key: "fit_note",
    label: "Fit note",
    category: "general",
    icon: "Ruler",
    keywords: ["fit", "size", "true to size", "model", "apparel"],
    defaults: { fit: "true", note: "", modelHeight: "", modelSize: "" },
  },
  {
    key: "authenticity_badge",
    label: "Authenticity badge",
    category: "general",
    icon: "BadgeCheck",
    keywords: ["authentic", "official", "verified", "genuine"],
    defaults: {
      label: "Official product",
      note: "Sourced from the authorised distributor.",
      verified: true,
      source: "",
    },
  },
  {
    key: "sustain_badge",
    label: "Sustainability claims",
    category: "general",
    icon: "Leaf",
    keywords: ["sustainability", "eco", "claims", "green"],
    defaults: {
      heading: "",
      c1Label: "",
      c1Source: "",
      c2Label: "",
      c2Source: "",
      c3Label: "",
      c3Source: "",
    },
  },
  {
    key: "discount_badge",
    label: "Discount badge",
    category: "general",
    icon: "Percent",
    keywords: ["discount", "sale", "saving", "off", "deal"],
    defaults: { label: "", priceMinor: 80000, compareAtMinor: 100000 },
  },
  {
    key: "batch_info",
    label: "Batch & expiry",
    category: "general",
    icon: "Package",
    keywords: ["batch", "expiry", "manufactured", "mfg", "pao"],
    defaults: {
      heading: "Batch & expiry",
      mfgLabel: "Manufactured",
      mfgDate: "",
      expiryLabel: "Best before",
      expiryDate: "",
      batchLabel: "Batch",
      batchCode: "",
      paoMonths: 0,
    },
  },
  {
    key: "delivery_promise",
    label: "Delivery promise",
    category: "general",
    icon: "Truck",
    keywords: ["delivery", "shipping", "promise", "dhaka", "dispatch"],
    defaults: {
      heading: "Delivery",
      insideLabel: "Inside Dhaka",
      insideDays: "1-2 working days",
      outsideLabel: "Outside Dhaka",
      outsideDays: "2-4 working days",
      note: "",
    },
  },
  {
    key: "free_shipping_bar",
    label: "Free shipping progress",
    category: "general",
    icon: "Truck",
    keywords: ["free", "shipping", "progress", "cart", "threshold"],
    defaults: {
      freeShippingLabel: "Spend",
      freeShippingSuffix: "more for free shipping",
      freeShippingDone: "Free shipping unlocked.",
    },
  },
  {
    key: "stock_delivery",
    label: "Stock and dispatch",
    category: "general",
    icon: "Boxes",
    keywords: ["stock", "inventory", "dispatch", "cut-off", "availability"],
    defaults: {
      handle: "",
      lowStockAt: 5,
      cutOff: "Order before 4pm for same-day dispatch",
    },
  },
  {
    key: "rank_list",
    label: "Rank list",
    category: "general",
    icon: "Trophy",
    keywords: ["rank", "bestsellers", "top", "list", "numbered"],
    defaults: { heading: "Bestsellers", limit: 10, collection: "" },
  },
  {
    key: "seller_card",
    label: "Seller card",
    category: "general",
    icon: "Store",
    keywords: ["seller", "vendor", "store", "merchant"],
    defaults: {
      name: "",
      tagline: "",
      logoUrl: "",
      rating: 0,
      policy: "",
      linkLabel: "Visit store",
      linkHref: "",
    },
  },
  {
    key: "category_header",
    label: "Category header",
    category: "general",
    icon: "Folder",
    keywords: ["category", "collection", "header", "banner", "breadcrumb"],
    defaults: {
      heading: "All products",
      body: "",
      imageUrl: "",
      scrim: true,
      showCount: true,
      showBreadcrumb: true,
      homeLabel: "Home",
    },
  },
  {
    key: "collection_story",
    label: "Collection story",
    category: "general",
    icon: "BookOpen",
    keywords: ["collection", "story", "editorial", "about", "banner"],
    defaults: {
      eyebrow: "",
      heading: "The story",
      body: "",
      ctaLabel: "",
      ctaHref: "",
      imageUrl: "",
      scrim: true,
    },
  },
  {
    key: "brand_rail",
    label: "Brand rail",
    category: "general",
    icon: "Tags",
    keywords: ["brand", "rail", "logos", "shop"],
    defaults: { heading: "Top brands", limit: 16, kind: "brand" },
  },
  {
    key: "concern_rail",
    label: "Concern rail",
    category: "general",
    icon: "Sparkles",
    keywords: ["concern", "acne", "skin", "rail", "shop"],
    defaults: {
      heading: "Shop by concern",
      terms: "acne,dark-spots,dryness",
      collection: "",
      limit: 12,
      cardVariant: "compact",
      showRating: false,
    },
  },
  {
    key: "back_in_stock",
    label: "Back in stock",
    category: "general",
    icon: "Bell",
    keywords: ["back", "stock", "notify", "restock", "email"],
    defaults: {
      handle: "",
      heading: "Notify me when it's back",
      body: "",
      buttonLabel: "Notify me",
      consentText: "",
    },
  },
  {
    key: "price_block",
    label: "Price block",
    category: "general",
    icon: "Tag",
    keywords: ["price", "compare", "product", "cost"],
    defaults: { showCompareAt: true, note: "" },
  },
  {
    key: "price_sparkline",
    label: "Price history",
    category: "general",
    icon: "TrendingDown",
    keywords: ["price", "history", "sparkline", "chart", "trend"],
    defaults: {
      heading: "Price history",
      handle: "",
      summary: "",
      emptyText: "No price history yet.",
      days: 90,
    },
  },
  {
    key: "deal_card",
    label: "Deal card",
    category: "general",
    icon: "BadgePercent",
    keywords: ["deal", "offer", "sale", "promo", "ends"],
    defaults: {
      heading: "Deal of the day",
      badgeLabel: "Save",
      endsAt: "",
      ctaLabel: "Shop now",
      ctaHref: "",
    },
  },
  {
    key: "deal_strip",
    label: "Deal strip",
    category: "general",
    icon: "Zap",
    keywords: ["deal", "strip", "sale", "savings", "rail"],
    defaults: {
      heading: "Today's deals",
      limit: 8,
      collection: "",
      badgeLabel: "Save",
      cardVariant: "compact",
    },
  },
  {
    key: "sponsored_slot",
    label: "Sponsored slot",
    category: "general",
    icon: "Megaphone",
    keywords: ["sponsored", "featured", "promoted", "ads"],
    defaults: { heading: "Featured", limit: 4, cardVariant: "compact" },
  },
  {
    key: "subbrand_spotlight",
    label: "Sub-brand spotlight",
    category: "general",
    icon: "Layers",
    keywords: ["sub-brand", "spotlight", "taaga", "house", "brands"],
    defaults: {
      heading: "Our Sub-Brands",
      subheading: "Curated lifestyle edits from our house of heritage craft",
      b1Name: "TAAGA",
      b1Tagline: "Bohemian & contemporary youth fusion",
      b1Image: "",
      b1Href: "/collections/taaga",
      b2Name: "TAAGA MAN",
      b2Tagline: "Modern urban essentials & relaxed cuts",
      b2Image: "",
      b2Href: "/collections/mens",
      b3Name: "HERSTORY",
      b3Tagline: "Luxury couture & handwoven silk drapes",
      b3Image: "",
      b3Href: "/collections/womens",
      b4Name: "AARONG EARTH",
      b4Tagline: "Pure chemical-free botanical wellness",
      b4Image: "",
      b4Href: "/collections/beauty",
    },
  },
  {
    key: "size_guide",
    label: "Size guide",
    category: "general",
    icon: "Ruler",
    keywords: ["size", "guide", "measurements", "fit", "chart"],
    defaults: {
      heading: "Size guide",
      openLabel: "Size guide",
      unit: "cm",
      c1Label: "Chest",
      c2Label: "Waist",
      c3Label: "Length",
      r1Label: "S",
      r1c1: 0,
      r1c2: 0,
      r1c3: 0,
      r2Label: "M",
      r2c1: 0,
      r2c2: 0,
      r2c3: 0,
      r3Label: "L",
      r3c1: 0,
      r3c2: 0,
      r3c3: 0,
      r4Label: "XL",
      r4c1: 0,
      r4c2: 0,
      r4c3: 0,
      note: "",
    },
  },
  {
    key: "routine_builder",
    label: "Routine builder",
    category: "general",
    icon: "CalendarCheck",
    keywords: ["routine", "skincare", "morning", "night", "regimen"],
    defaults: {
      heading: "Build your routine",
      amLabel: "Morning",
      pmLabel: "Night",
      swapLabel: "Swap",
      addAllLabel: "Add routine to cart",
      note: "Totals are confirmed at checkout.",
      limit: 4,
      collection: "",
    },
  },
  {
    key: "sample_picker",
    label: "Sample picker",
    category: "general",
    icon: "Gift",
    keywords: ["sample", "free", "trial", "picker"],
    defaults: {
      heading: "Pick a free sample",
      thresholdText: "Free sample over",
      collection: "",
      limit: 4,
    },
  },
  {
    key: "shade_finder",
    label: "Shade finder",
    category: "general",
    icon: "Palette",
    keywords: ["shade", "foundation", "undertone", "match", "finder"],
    defaults: {
      heading: "Find your shade",
      undertonePrompt: "What is your undertone?",
      depthPrompt: "How deep is your skin tone?",
      emptyText: "No shades match yet — try a different answer.",
      handle: "",
    },
  },
  {
    key: "skin_quiz",
    label: "Skin quiz",
    category: "general",
    icon: "ClipboardList",
    keywords: ["skin", "quiz", "concern", "routine", "finder"],
    defaults: {
      heading: "Skin quiz",
      body: "Four questions for a routine that suits you.",
      typePrompt: "Your skin type?",
      concernPrompt: "Main concern?",
      sensitivityPrompt: "Sensitive skin?",
      finishPrompt: "Preferred finish?",
      resultText: "Here is what we suggest.",
      resultLabel: "Shop my routine",
      resultPath: "/search",
    },
  },
  {
    key: "quiz",
    label: "Quiz / finder",
    category: "general",
    icon: "CircleHelp",
    keywords: ["quiz", "finder", "flow", "questions", "filter"],
    defaults: {
      heading: "Find your match",
      resultBase: "/",
      resultLabel: "See my matches",
      q1Key: "",
      q1Label: "",
      q1Choices: "",
      q1Multiple: false,
      q2Key: "",
      q2Label: "",
      q2Choices: "",
      q2Multiple: false,
      q3Key: "",
      q3Label: "",
      q3Choices: "",
      q3Multiple: false,
      consentText: "",
    },
  },
  {
    key: "consult_cta",
    label: "Consult CTA",
    category: "general",
    icon: "PhoneCall",
    keywords: ["consult", "advisor", "whatsapp", "call", "beauty"],
    defaults: {
      heading: "Talk to a beauty advisor",
      body: "Not sure what suits you? We will help.",
      whatsapp: "",
      whatsappLabel: "WhatsApp",
      phone: "",
      callLabel: "Call us",
      fieldLabel: "Your number",
      buttonLabel: "Book a consult",
      pendingText: "We will call you back.",
      consentText: "",
    },
  },
  {
    key: "gift_builder",
    label: "Gift set builder",
    category: "general",
    icon: "Gift",
    keywords: ["gift", "set", "builder", "box", "bundle"],
    defaults: {
      heading: "Build a gift set",
      size: 3,
      messageLabel: "Message card",
      buttonLabel: "Add gift set",
      note: "Gift box and total are confirmed at checkout.",
      collection: "",
      limit: 8,
    },
  },
  {
    key: "bundle_builder",
    label: "Bundle builder",
    category: "general",
    icon: "PackagePlus",
    keywords: ["bundle", "builder", "combo", "add-ons", "pack"],
    defaults: {
      heading: "Build your bundle",
      collection: "",
      limit: 4,
      buttonLabel: "Add bundle",
      note: "Bundle total is confirmed in the cart.",
    },
  },
  {
    key: "shoppable_image",
    label: "Shoppable image",
    category: "general",
    icon: "ImagePlus",
    keywords: ["shoppable", "hotspot", "pins", "shop the look"],
    defaults: {
      heading: "Shop the look",
      imageUrl: "",
      altText: "",
      limit: 4,
      collection: "",
      p1x: 25,
      p1y: 30,
      p2x: 60,
      p2y: 45,
      p3x: 40,
      p3y: 70,
      p4x: 75,
      p4y: 80,
    },
  },
  {
    key: "compare_table",
    label: "Compare table",
    category: "general",
    icon: "Table",
    keywords: ["compare", "table", "versus", "products"],
    defaults: {
      caption: "Compare products",
      limit: 4,
      collection: "",
      r1Label: "Price",
      r2Label: "Availability",
      r3Label: "",
      r4Label: "",
    },
  },
  {
    key: "spec_table",
    label: "Spec table",
    category: "general",
    icon: "Table",
    keywords: ["spec", "specs", "table", "technical", "details"],
    defaults: {
      caption: "",
      columnLabel: "This product",
      grouped: true,
      handle: "",
      r1Group: "",
      r1Label: "",
      r1Value: "",
      r2Group: "",
      r2Label: "",
      r2Value: "",
      r3Group: "",
      r3Label: "",
      r3Value: "",
      r4Group: "",
      r4Label: "",
      r4Value: "",
      r5Group: "",
      r5Label: "",
      r5Value: "",
      r6Group: "",
      r6Label: "",
      r6Value: "",
      items: [],
    },
  },
  {
    key: "spec_highlights",
    label: "Spec highlights",
    category: "general",
    icon: "Zap",
    keywords: ["spec", "highlights", "at a glance", "tiles"],
    defaults: {
      heading: "At a glance",
      columns: 4,
      t1Label: "Chipset",
      t1Value: "",
      t2Label: "Memory",
      t2Value: "",
      t3Label: "Battery",
      t3Value: "",
      t4Label: "Warranty",
      t4Value: "",
      t5Label: "",
      t5Value: "",
      t6Label: "",
      t6Value: "",
    },
  },
  {
    key: "ingredient_glossary",
    label: "Ingredient glossary",
    category: "general",
    icon: "BookOpen",
    keywords: ["ingredient", "glossary", "terms", "dictionary"],
    defaults: {
      heading: "Ingredient glossary",
      g1Term: "",
      g1Body: "",
      g2Term: "",
      g2Body: "",
      g3Term: "",
      g3Body: "",
      g4Term: "",
      g4Body: "",
      g5Term: "",
      g5Body: "",
      g6Term: "",
      g6Body: "",
    },
  },
  {
    key: "ingredient_list",
    label: "Ingredient list",
    category: "general",
    icon: "FlaskConical",
    keywords: ["ingredient", "inci", "actives", "formula"],
    defaults: {
      heading: "Key ingredients",
      i1Name: "",
      i1Amount: "",
      i1Gloss: "",
      i2Name: "",
      i2Amount: "",
      i2Gloss: "",
      i3Name: "",
      i3Amount: "",
      i3Gloss: "",
      i4Name: "",
      i4Amount: "",
      i4Gloss: "",
      i5Name: "",
      i5Amount: "",
      i5Gloss: "",
      i6Name: "",
      i6Amount: "",
      i6Gloss: "",
      inci: "",
      inciLabel: "Full ingredients (INCI)",
      handle: "",
    },
  },
  {
    key: "ingredient_rail",
    label: "Ingredient rail",
    category: "general",
    icon: "Tags",
    keywords: ["ingredient", "rail", "shop by", "chips"],
    defaults: {
      heading: "Shop by ingredient",
      i1Name: "Niacinamide",
      i1Gloss: "",
      i2Name: "",
      i2Gloss: "",
      i3Name: "",
      i3Gloss: "",
      i4Name: "",
      i4Gloss: "",
      collection: "",
      limit: 12,
      cardVariant: "compact",
    },
  },
  {
    key: "payment_methods",
    label: "Payment methods",
    category: "general",
    icon: "CreditCard",
    keywords: ["payment", "methods", "checkout", "bkash", "cod"],
    defaults: {
      heading: "Payment method",
      note: "",
      emptyText: "No payment method is available right now.",
    },
  },
  {
    key: "payment_icons",
    label: "Payment icons",
    category: "general",
    icon: "Wallet",
    keywords: ["payment", "icons", "marks", "accept", "footer"],
    defaults: {
      heading: "We accept",
      marks: "bKash, Nagad, Rocket, Visa, Mastercard, Cash on delivery",
    },
  },
  {
    key: "emi_calculator",
    label: "EMI calculator",
    category: "general",
    icon: "Calculator",
    keywords: ["emi", "instalment", "calculator", "plans", "bank"],
    defaults: {
      heading: "EMI plans",
      handle: "",
      note: "Bank EMI available on selected cards.",
      emptyText: "EMI is not available for this product.",
      perMonthLabel: "per month",
    },
  },
  {
    key: "order_tracker",
    label: "Order tracker",
    category: "general",
    icon: "Truck",
    keywords: ["order", "tracker", "status", "tracking", "delivery"],
    defaults: {
      heading: "Order status",
      step1: "Placed",
      step2: "Confirmed",
      step3: "Shipped",
      step4: "Delivered",
      note: "",
    },
  },
  {
    key: "product_grid",
    label: "Product grid",
    category: "commerce",
    icon: "LayoutGrid",
    keywords: ["products", "grid", "catalogue", "shop"],
    defaults: {
      heading: "Products",
      limit: 12,
      columns: 4,
      cardVariant: "standard",
      density: "comfortable",
      showRating: false,
      promise: "",
    },
  },
  {
    key: "product_rail",
    label: "Product rail",
    category: "commerce",
    icon: "GalleryHorizontal",
    keywords: ["products", "rail", "carousel", "trending"],
    defaults: {
      heading: "Trending now",
      limit: 12,
      source: "collection",
      collection: "",
      cardVariant: "compact",
      showRating: false,
      promise: "",
    },
  },
  {
    key: "product_media",
    label: "Product media",
    category: "commerce",
    icon: "Image",
    keywords: ["product", "gallery", "images", "zoom"],
    defaults: {
      ratio: "1/1",
      showThumbnails: true,
      zoom: true,
      image1: "",
      image2: "",
      image3: "",
      image4: "",
      altText: "",
    },
  },
  {
    key: "product_meta",
    label: "Product details",
    category: "commerce",
    icon: "Info",
    keywords: ["product", "details", "meta", "specs"],
    defaults: { heading: "Product details" },
  },
  {
    key: "product_qna",
    label: "Questions and answers",
    category: "commerce",
    icon: "MessageSquareQuote",
    keywords: ["qna", "questions", "answers", "product"],
    defaults: {
      handle: "",
      heading: "Questions and answers",
      askLabel: "Ask a question",
      askHref: "",
      q1: "",
      a1: "",
      q2: "",
      a2: "",
      q3: "",
      a3: "",
      items: [],
    },
  },
  {
    key: "collection_grid",
    label: "Collection grid",
    category: "commerce",
    icon: "Tags",
    keywords: ["collections", "categories", "grid"],
    defaults: {
      heading: "Collections",
      limit: 8,
      columns: 4,
      cardVariant: "standard",
      showCount: true,
    },
  },
  {
    key: "account_cart",
    label: "Account and cart",
    category: "commerce",
    icon: "User",
    keywords: ["account", "cart", "header", "login"],
    defaults: { accountLabel: "Account", cartLabel: "Cart", showCount: true },
  },
  {
    key: "cart_drawer",
    label: "Cart drawer",
    category: "commerce",
    icon: "ShoppingBag",
    keywords: ["cart", "drawer", "minicart", "slideover"],
    defaults: {
      heading: "Your cart",
      triggerLabel: "Cart",
      removeLabel: "Remove",
      emptyText: "Your cart is empty.",
      totalLabel: "Total",
      subtotalLabel: "Subtotal",
      shippingLabel: "Delivery",
      ctaLabel: "Checkout",
      showCoupon: false,
      showCta: true,
      showFreeShipping: true,
    },
  },
  {
    key: "cart_lines",
    label: "Cart lines",
    category: "commerce",
    icon: "List",
    keywords: ["cart", "lines", "items"],
    defaults: {
      heading: "Your items",
      removeLabel: "Remove",
      emptyText: "Your cart is empty.",
    },
  },
  {
    key: "cart_summary",
    label: "Cart summary",
    category: "commerce",
    icon: "Receipt",
    keywords: ["cart", "summary", "total", "checkout"],
    defaults: {
      heading: "Order summary",
      subtotalLabel: "Subtotal",
      discountLabel: "Discount",
      shippingLabel: "Delivery",
      codLabel: "Cash on delivery fee",
      vatLabel: "VAT",
      totalLabel: "Total",
      ctaLabel: "Checkout",
      couponLabel: "Coupon code",
      couponApplyLabel: "Apply",
      emptyText: "Add something to see your total.",
      freeShippingLabel: "Spend",
      freeShippingSuffix: "more for free shipping",
      freeShippingDone: "Free shipping unlocked.",
      showCoupon: true,
      showCta: true,
      showFreeShipping: true,
    },
  },
  {
    key: "checkout_steps",
    label: "Checkout steps",
    category: "commerce",
    icon: "ListOrdered",
    keywords: ["checkout", "steps", "progress"],
    defaults: {
      heading: "Checkout progress",
      step1: "Cart",
      step2: "Details",
      step3: "Payment",
      step4: "Confirmation",
      activeStep: 1,
    },
  },
  {
    key: "search_command",
    label: "Search",
    category: "commerce",
    icon: "Search",
    keywords: ["search", "command", "typeahead", "suggestions"],
    defaults: { placeholder: "Search products", buttonLabel: "Search", limit: 6 },
  },
  {
    key: "facet_sidebar",
    label: "Facet sidebar",
    category: "commerce",
    icon: "SlidersHorizontal",
    keywords: ["filters", "facets", "sidebar", "refine"],
    defaults: {
      heading: "Filters",
      limit: 24,
      showCategories: true,
      showKinds: true,
      showPrice: true,
      showStock: true,
      collapsed: false,
      drawerLabel: "Filters",
      clearLabel: "Clear all",
      categoryLabel: "Category",
      kindLabel: "Type",
      priceLabel: "Price",
      stockLabel: "Availability",
      inStockLabel: "In stock only",
    },
  },
  {
    key: "pagination",
    label: "Pagination",
    category: "commerce",
    icon: "MoreHorizontal",
    keywords: ["pagination", "pages", "load more"],
    defaults: {
      mode: "numbered",
      moreLabel: "Load more",
      prevLabel: "Previous",
      nextLabel: "Next",
      pageLabel: "Page",
    },
  },
  {
    key: "result_toolbar",
    label: "Result toolbar",
    category: "commerce",
    icon: "ArrowUpDown",
    keywords: ["toolbar", "sort", "count", "results"],
    defaults: {
      countLabel: "products",
      showSort: true,
      showDensity: true,
      filtersLabel: "Filters",
      sortLabel: "Sort",
    },
  },
  {
    key: "blog_archive",
    label: "Blog archive",
    category: "general",
    icon: "Newspaper",
    keywords: ["blog", "archive", "articles", "posts"],
    defaults: {
      heading: "",
      layout: "grid",
      columns: 3,
      limit: 9,
      showCover: true,
      showExcerpt: true,
      showMeta: true,
      emptyText: "No articles yet.",
    },
  },
  {
    key: "blog_pager",
    label: "Blog pagination",
    category: "general",
    icon: "MoreHorizontal",
    keywords: ["blog", "pagination", "pages"],
    defaults: { align: "center" },
  },
  {
    key: "blog_terms",
    label: "Blog topics",
    category: "general",
    icon: "Tags",
    keywords: ["blog", "topics", "tags", "categories"],
    defaults: { heading: "", style: "pills", showCounts: true },
  },
  {
    key: "review_list",
    label: "Review list",
    category: "commerce",
    icon: "Star",
    keywords: ["reviews", "ratings", "feedback"],
    defaults: {
      handle: "",
      heading: "Reviews",
      limit: 6,
      sort: "recent",
      verifiedOnly: false,
      emptyText: "No reviews yet.",
    },
  },
  {
    key: "rating_summary",
    label: "Rating summary",
    category: "commerce",
    icon: "BarChart3",
    keywords: ["rating", "summary", "histogram", "stars"],
    defaults: {
      handle: "",
      heading: "Customer ratings",
      showHistogram: true,
      verifiedOnly: false,
    },
  },
  {
    key: "recently_viewed",
    label: "Recently viewed",
    category: "commerce",
    icon: "History",
    keywords: ["recently", "viewed", "history"],
    defaults: { heading: "Recently viewed", limit: 6, showClear: true },
  },
  {
    key: "wishlist_button",
    label: "Wishlist button",
    category: "commerce",
    icon: "Heart",
    keywords: ["wishlist", "save", "favourite"],
    defaults: { productId: "", addLabel: "Save", savedLabel: "Saved", showCount: false },
  },
  {
    key: "compare_tray",
    label: "Compare tray",
    category: "commerce",
    icon: "ArrowLeftRight",
    keywords: ["compare", "tray", "versus"],
    defaults: {
      heading: "Compare",
      compareLabel: "Compare now",
      clearLabel: "Clear",
      emptyText: "Add products to compare.",
      compareHref: "/compare",
      limit: 8,
    },
  },
  {
    key: "bundle_offer",
    label: "Bundle offer",
    category: "commerce",
    icon: "Gift",
    keywords: ["bundle", "offer", "kit", "total"],
    defaults: {
      heading: "Build your bundle",
      buttonLabel: "Calculate total",
      i1Label: "",
      i1VariantId: "",
      i2Label: "",
      i2VariantId: "",
      i3Label: "",
      i3VariantId: "",
      i4Label: "",
      i4VariantId: "",
    },
  },
  {
    key: "add_to_cart",
    label: "Add to cart",
    category: "commerce",
    icon: "ShoppingCart",
    keywords: ["add", "cart", "buy", "purchase", "quantity"],
    defaults: { label: "Add to cart", showQuantity: true },
  },
  {
    key: "rewards_club",
    label: "Rewards club",
    category: "commerce",
    icon: "Trophy",
    keywords: ["rewards", "loyalty", "points", "tiers", "membership"],
    defaults: {
      heading: "My Rewards",
      body: "Earn points on every purchase and unlock member prices.",
      tier1Name: "Silver",
      tier1Points: "0+ points",
      tier2Name: "Gold",
      tier2Points: "5,000+ points",
      tier3Name: "Platinum",
      tier3Points: "15,000+ points",
      buttonLabel: "Join free",
      buttonHref: "/pages/rewards",
    },
  },
  {
    key: "wedding_shop",
    label: "Wedding shop",
    category: "commerce",
    icon: "Heart",
    keywords: ["wedding", "bridal", "groom", "gifting", "collections"],
    defaults: {
      heading: "The Wedding Shop",
      body: "Bridal sarees, groom panjabis and festive gifting — curated for the big day.",
      c1Name: "Bridal Sarees",
      c1Href: "/c/bridal",
      c2Name: "Groom Panjabis",
      c2Href: "/c/groom",
      c3Name: "Festive Gifting",
      c3Href: "/c/gifting",
      buttonLabel: "Shop all wedding",
      buttonHref: "/c/wedding",
    },
  },
  {
    key: "gift_finder",
    label: "Gift finder",
    category: "commerce",
    icon: "Compass",
    keywords: ["gift", "finder", "occasion", "search", "gifts"],
    defaults: {
      heading: "Find the perfect gift",
      body: "Pick an occasion — we take you straight to matching gifts.",
      o1Label: "For Her",
      o1Query: "saree",
      o2Label: "For Him",
      o2Query: "panjabi",
      o3Label: "For Home",
      o3Query: "home decor",
      buttonLabel: "Browse all gifts",
      buttonHref: "/search",
    },
  },
  {
    key: "rich_text",
    label: "Text block",
    category: "general",
    icon: "FileText",
    keywords: ["text", "paragraph", "copy", "prose", "body"],
    defaults: { heading: "", body: "Tell customers about your store." },
  },
  {
    key: "form",
    label: "Contact form",
    category: "general",
    icon: "ClipboardList",
    keywords: ["contact", "form", "message", "email", "support"],
    defaults: {
      heading: "Send us a message",
      body: "",
      nameLabel: "Your name",
      emailLabel: "Email",
      phoneLabel: "Phone",
      messageLabel: "How can we help?",
      buttonLabel: "Send",
      successText: "Thank you — we will reply shortly.",
      consentText: "We only use your details to answer this message.",
      showPhone: true,
    },
  },
  {
    key: "nav_menu",
    label: "Menu",
    category: "general",
    icon: "List",
    keywords: ["menu", "nav", "navigation", "links", "header"],
    defaults: {
      heading: "",
      // Widget→menu binding (Content › Menus). Empty = manual `items`.
      menuId: "",
      layout: "row",
      align: "left",
      items: [
        { label: "Home", href: "/" },
        { label: "Shop", href: "" },
        { label: "Contact", href: "/contact" },
      ],
    },
  },
  {
    key: "newsletter",
    label: "Newsletter signup",
    category: "general",
    icon: "Mail",
    keywords: ["newsletter", "email", "subscribe", "signup", "footer"],
    defaults: {
      heading: "Stay in touch",
      body: "Get offers by email. Unsubscribe any time.",
      buttonLabel: "Subscribe",
      consentText: "",
    },
  },
  {
    key: "sticky_bar",
    label: "Sticky bar",
    category: "general",
    icon: "Megaphone",
    keywords: ["sticky", "bar", "announcement", "promo", "cta"],
    defaults: {
      text: "Free delivery over BDT 2,000",
      ctaLabel: "",
      ctaHref: "",
      position: "bottom",
    },
  },
  {
    key: "mega_menu",
    label: "Mega menu",
    category: "general",
    icon: "Menu",
    keywords: ["mega", "menu", "navigation", "taxonomy", "header"],
    defaults: { label: "Shop", limit: 8, columns: 4, menuId: "" },
  },
  {
    key: "buy_box",
    label: "Buy box",
    category: "commerce",
    icon: "CreditCard",
    keywords: ["buy", "price", "cart", "product", "purchase"],
    defaults: {
      handle: "",
      label: "Add to cart",
      showQuantity: true,
      showCompareAt: true,
      note: "",
      promise: "",
    },
  },
  {
    key: "variant_picker",
    label: "Variant picker",
    category: "commerce",
    icon: "Palette",
    keywords: ["variant", "option", "size", "colour", "picker", "chip"],
    defaults: {
      handle: "",
      heading: "Choose an option",
      mode: "chip",
      axisOneLabel: "",
      axisTwoLabel: "",
    },
  },
  {
    key: "sticky_buy_bar",
    label: "Sticky buy bar",
    category: "commerce",
    icon: "Zap",
    keywords: ["sticky", "buy", "cart", "quick", "product", "dock"],
    defaults: {
      handle: "",
      label: "Add to cart",
      showPrice: true,
      dockAfter: 320,
    },
  },
  {
    key: "filter_chips",
    label: "Active filter chips",
    category: "commerce",
    icon: "Filter",
    keywords: ["filter", "chips", "facets", "active", "clear", "collection"],
    defaults: { clearLabel: "Clear all", emptyText: "", showWhenEmpty: false },
  },
  {
    key: "size_selector",
    label: "Size selector",
    category: "commerce",
    icon: "Ruler",
    keywords: ["size", "variant", "apparel", "guide", "fit"],
    defaults: {
      handle: "",
      heading: "Size",
      notifyLabel: "Notify me",
      guideLabel: "Size guide",
    },
  },
  {
    key: "complete_the_look",
    label: "Complete the look",
    category: "commerce",
    icon: "Shirt",
    keywords: ["complete", "look", "bundle", "outfit", "add-all", "product"],
    defaults: {
      heading: "Complete the look",
      limit: 4,
      collection: "",
      buttonLabel: "Add all",
    },
  },
  {
    key: "circle_categories",
    label: "Circle categories",
    category: "commerce",
    icon: "Store",
    keywords: ["circle", "categories", "collections", "shop by", "round"],
    defaults: {
      heading: "Shop by Category",
      c1Title: "Women's Sarees",
      c1Image: "",
      c1Href: "/collections/womens",
      c2Title: "Men's Panjabi",
      c2Image: "",
      c2Href: "/collections/mens",
      c3Title: "Taaga",
      c3Image: "",
      c3Href: "/collections/taaga",
      c4Title: "Jamdani Weaves",
      c4Image: "",
      c4Href: "/collections/heritage-handloom",
      c5Title: "Nakshi Kantha",
      c5Image: "",
      c5Href: "/collections/nakshi-kantha",
      c6Title: "Handcrafted Jewelry",
      c6Image: "",
      c6Href: "/collections/jewelry",
      c7Title: "Home & Living",
      c7Image: "",
      c7Href: "/collections/living",
      c8Title: "Aarong Earth",
      c8Image: "",
      c8Href: "/collections/beauty",
    },
  },
  {
    key: "store_locator",
    label: "Store locator",
    category: "general",
    icon: "MapPin",
    keywords: ["store", "locator", "branches", "address", "hours", "visit"],
    defaults: {
      heading: "Visit us",
      s1Name: "",
      s1Address: "",
      s1Hours: "",
      s1Phone: "",
      s2Name: "",
      s2Address: "",
      s2Hours: "",
      s2Phone: "",
      s3Name: "",
      s3Address: "",
      s3Hours: "",
      s3Phone: "",
    },
  },
  {
    key: "ugc_gallery",
    label: "Customer gallery",
    category: "media",
    icon: "Images",
    keywords: ["ugc", "customer", "gallery", "worn", "photos", "community"],
    defaults: { heading: "As worn by you", limit: 6, collection: "", note: "" },
  },
  {
    key: "trade_in",
    label: "Trade-in",
    category: "general",
    icon: "ArrowLeftRight",
    keywords: ["trade", "exchange", "old device", "quote", "lead", "form"],
    defaults: {
      heading: "Trade in your old device",
      body: "Tell us what you have and we will send a quote.",
      buttonLabel: "Get a quote",
      pendingText: "We will email your quote shortly.",
      consentText: "",
    },
  },
  {
    key: "combo_card",
    label: "Combo card",
    category: "general",
    icon: "PackagePlus",
    keywords: ["combo", "pack", "bundle", "kit", "offer", "set"],
    defaults: {
      heading: "Combo pack",
      body: "",
      buttonLabel: "Add combo to cart",
      note: "",
      collection: "",
      limit: 3,
      i1VariantId: "",
      i2VariantId: "",
      i3VariantId: "",
      i4VariantId: "",
    },
  },
  {
    key: "loyalty_strip",
    label: "Loyalty strip",
    category: "general",
    icon: "Star",
    keywords: ["loyalty", "points", "rewards", "order", "strip"],
    defaults: { label: "Points on this order", handle: "" },
  },
  {
    key: "warranty_panel",
    label: "Warranty panel",
    category: "general",
    icon: "ShieldCheck",
    keywords: ["warranty", "guarantee", "service", "centre", "official", "import"],
    defaults: {
      heading: "Warranty",
      months: 12,
      coverage: "Manufacturer warranty against defects.",
      official: true,
      officialLabel: "Official import",
      parallelLabel: "Parallel import",
      s1Name: "",
      s1Address: "",
      s2Name: "",
      s2Address: "",
      s3Name: "",
      s3Address: "",
    },
  },
  {
    key: "before_after",
    label: "Before & after",
    category: "media",
    icon: "Columns2",
    keywords: ["before", "after", "results", "comparison", "proof", "images"],
    defaults: {
      heading: "Real results",
      beforeImage: "",
      beforeAlt: "",
      beforeLabel: "Before",
      afterImage: "",
      afterAlt: "",
      afterLabel: "After",
      disclaimer: "Individual results vary. Images are unretouched.",
    },
  },
  {
    key: "refill_widget",
    label: "Refill & subscribe",
    category: "commerce",
    icon: "Package",
    keywords: ["refill", "subscribe", "cadence", "schedule", "repeat", "delivery"],
    defaults: {
      heading: "Refill & save",
      body: "Get a refill delivered on your schedule.",
      c1Label: "Every month",
      c1Value: "30",
      c2Label: "Every 2 months",
      c2Value: "60",
      c3Label: "Every 3 months",
      c3Value: "90",
      buttonLabel: "Subscribe",
      handle: "",
    },
  },
  {
    key: "quick_view",
    label: "Quick view",
    category: "commerce",
    icon: "Search",
    keywords: ["quick", "view", "preview", "overlay", "products", "modal"],
    defaults: { heading: "Quick view", buttonLabel: "Quick view", limit: 6 },
  },
  {
    key: "department_strip",
    label: "Department strip",
    category: "general",
    icon: "Tags",
    keywords: ["department", "strip", "chips", "categories", "rail", "taxonomy"],
    defaults: { heading: "", limit: 12 },
  },
  {
    key: "columns",
    label: "Columns",
    category: "layout",
    icon: "GalleryHorizontal",
    keywords: ["columns", "split", "layout", "section"],
    container: true,
    defaults: {
      columns: 2,
      gap: 24,
      padY: 0,
      maxW: "container",
      align: "left",
      bg: "none",
    },
  },
  // Songoskriti heritage gap pack: defaults mirror builder-ast 1:1, with
  // empty বাংলা twins for every theme-authored string.
  {
    key: "finder_row",
    label: "Occasion finder",
    category: "general",
    icon: "Compass",
    keywords: ["occasion", "finder", "eid", "wedding", "gifting", "chips"],
    defaults: {
      heading: "Shop by occasion",
      heading_bn: "",
      body: "",
      body_bn: "",
      o1Label: "Eid and festive",
      o1Label_bn: "",
      o1Href: "/c/festive",
      o2Label: "Wedding",
      o2Label_bn: "",
      o2Href: "/c/wedding",
      o3Label: "Gifting",
      o3Label_bn: "",
      o3Href: "/c/gifting",
      buttonLabel: "",
      buttonLabel_bn: "",
      buttonHref: "",
    },
  },
  {
    key: "craft_story",
    label: "Craft story",
    category: "general",
    icon: "BookOpen",
    keywords: ["craft", "story", "artisan", "loom", "heritage", "about"],
    defaults: {
      eyebrow: "Our craft",
      eyebrow_bn: "",
      heading: "From loom to wardrobe",
      heading_bn: "",
      body: "We work with weaving clusters across Bengal. Every piece carries the name of its maker.",
      body_bn: "",
      ctaLabel: "Read our story",
      ctaLabel_bn: "",
      ctaHref: "/pages/our-craft",
      imageUrl: "",
      scrim: true,
    },
  },
  {
    key: "testimonials",
    label: "Testimonials",
    category: "general",
    icon: "MessagesSquare",
    keywords: ["testimonials", "reviews", "quotes", "carousel", "customers"],
    defaults: { testimonials: [], autoAdvanceMs: 6000 },
  },
  {
    key: "trust_footer",
    label: "Trust footer",
    category: "general",
    icon: "ShieldCheck",
    keywords: ["trust", "badges", "delivery", "returns", "payment", "footer"],
    defaults: {
      items: [],
      i1Icon: "delivery",
      i1Title: "Fast delivery",
      i1Title_bn: "",
      i1Body: "",
      i1Body_bn: "",
      i2Icon: "returns",
      i2Title: "Easy returns",
      i2Title_bn: "",
      i2Body: "",
      i2Body_bn: "",
      i3Icon: "secure",
      i3Title: "Secure payment",
      i3Title_bn: "",
      i3Body: "",
      i3Body_bn: "",
      i4Icon: "support",
      i4Title: "",
      i4Title_bn: "",
      i4Body: "",
      i4Body_bn: "",
    },
  },
];

export const WIDGET_BY_KEY: Record<string, WidgetDef> = WIDGETS.reduce<
  Record<string, WidgetDef>
>((acc, widget) => {
  acc[widget.key] = widget;
  return acc;
}, {});

export function widgetLabel(key: string): string {
  return WIDGET_BY_KEY[key]?.label ?? key;
}

export function widgetIcon(key: string): string {
  return WIDGET_BY_KEY[key]?.icon ?? "Square";
}

/** Search across label and keywords; empty query returns everything. */
export function searchWidgets(
  query: string,
  widgets: WidgetDef[] = WIDGETS,
): WidgetDef[] {
  const q = query.trim().toLowerCase();
  if (!q) return widgets;
  return widgets.filter(
    (widget) =>
      widget.label.toLowerCase().includes(q) ||
      widget.key.includes(q) ||
      widget.keywords.some((keyword) => keyword.includes(q)),
  );
}

export function groupWidgets(
  widgets: WidgetDef[],
): { category: WidgetCategory; items: WidgetDef[] }[] {
  return CATEGORY_ORDER.map((category) => ({
    category,
    items: widgets.filter((widget) => widget.category === category),
  })).filter((group) => group.items.length > 0);
}

export function newWidgetNode(key: string): StudioNode {
  const def = WIDGET_BY_KEY[key];
  const node: StudioNode = {
    id: uid(),
    el: key,
    settings: def ? structuredClone(def.defaults) : text("New element"),
  };
  if (def?.container) node.children = [];
  return node;
}
