import type { Section } from "../../builder-ast";
import type { SectionBuilder } from "./types";

export function buildHomepageMain(s: SectionBuilder): Section[] {
  return [
    s("hero_carousel", {
      advPadY: 40,
      autoAdvanceMs: 6000,
      slides: [
        {
          image: "/api/public/ph/hero/heritage-festive-drop.svg",
          headline: "The Festive Drop ’26 is here",
          headline_bn: "উৎসব কালেকশন ’২৬ এসে গেছে",
          subhead:
            "Pure silk panjabis, Jamdani sarees & wedding finery — woven for the season of celebrations",
          ctaLabel: "Shop festive",
          ctaUrl: "/c/eid-festive",
          caption: "Festive Drop ’26",
        },
        {
          image: "/api/public/ph/hero/heritage-weaves.svg",
          headline: "Woven with patience, worn with pride",
          headline_bn: "যত্নে বোনা, গর্বে পরা",
          subhead: "Tangail & Jamdani handloom — a living craft legacy",
          ctaLabel: "Explore the collection",
          ctaUrl: "/c/heritage-handloom",
          caption: "Living Craft",
        },
        {
          image: "/api/public/ph/hero/artisan-story.svg",
          headline: "65,000+ rural artisans empowered",
          headline_bn: "৬৫,০০০+ গ্রামীণ কারিগরের পাশে",
          subhead: "Fair-trade handloom from 64 districts",
          ctaLabel: "Our story",
          ctaUrl: "/pages/about",
          caption: "Fair Trade",
        },
      ],
    }),
    s("circle_categories", {
      heading: "Shop by category",
      advPadY: 48,
      c1Title: "Women",
      c1Image: "/api/public/ph/womens/tangail-taant-cotton-saree.svg",
      c1Href: "/c/womens",
      c2Title: "Men",
      c2Image: "/api/public/ph/mens/pure-silk-embroidered-panjabi.svg",
      c2Href: "/c/mens",
      c3Title: "Kids",
      c3Image: "/api/public/ph/kids/kids-festive-kurta.svg",
      c3Href: "/c/kids",
      c4Title: "Living",
      c4Image: "/api/public/ph/living/handcrafted-nakshi-kantha-quilt.svg",
      c4Href: "/c/living",
      c5Title: "Jewelry",
      c5Image: "/api/public/ph/jewelry/terracotta-heritage-necklace.svg",
      c5Href: "/c/jewelry",
      c6Title: "Taaga",
      c6Image: "/api/public/ph/taaga/taaga-fusion-kurti.svg",
      c6Href: "/c/taaga-fusion",
      c7Title: "Earth",
      c7Image: "/api/public/ph/earth/aarong-earth-handloom-tote.svg",
      c7Href: "/c/aarong-earth",
      c8Title: "Sale",
      c8Image: "/api/public/ph/sale/festive-sale-edit.svg",
      c8Href: "/c/festive-sale",
    }),
    s("product_rail", {
      advPadY: 40,
      heading: "New arrivals",
      collection: "new-in",
      limit: 8,
      cardVariant: "standard",
      showRating: true,
      promise: "In stock · Dispatched in 24h",
    }),
    s("collection_story", {
      advPadY: 56,
      eyebrow: "Puja ’26",
      heading: "Made for the season of light",
      body: "Festive silks, handloom cottons and sparkling details — crafted for Puja celebrations.",
      ctaLabel: "Shop the festive edit",
      ctaHref: "/c/eid-festive",
      imageUrl: "/api/public/ph/hero/heritage-festive-drop.svg",
      scrim: true,
    }),
    s("lookbook", {
      advPadY: 48,
      heading: "Shop the look",
      i1Image: "/api/public/ph/look/puja-festive-look.svg",
      i1Alt: "Puja",
      i1Href: "/c/eid-festive",
      i2Image: "/api/public/ph/look/wedding-bridal-look.svg",
      i2Alt: "Wedding",
      i2Href: "/c/wedding",
      i3Image: "/api/public/ph/look/everyday-handloom-look.svg",
      i3Alt: "Everyday",
      i3Href: "/c/heritage-handloom",
      i4Image: "/api/public/ph/look/home-decor-look.svg",
      i4Alt: "Home",
      i4Href: "/c/home-decor",
      offset: true,
    }),
    s("textile_showcase", {
      advPadY: 48,
      headline: "Our textiles",
      items: [
        {
          image: "/api/public/ph/textile/dhakai-jamdani.svg",
          title: "Jamdani",
          subtitle: "Dhakai royal drape",
        },
        {
          image: "/api/public/ph/textile/tangail-taant.svg",
          title: "Tangail Taant",
          subtitle: "Handloom cotton",
        },
        {
          image: "/api/public/ph/textile/nakshi-kantha.svg",
          title: "Nakshi Kantha",
          subtitle: "Hand embroidery",
        },
        {
          image: "/api/public/ph/textile/pure-silk.svg",
          title: "Pure Silk",
          subtitle: "Rajshahi festive",
        },
      ],
    }),
    s("trust_bar", {
      advPadY: 24,
      i1Icon: "delivery",
      i1Title: "Nationwide 48h dispatch",
      i1Body: "Orders dispatched within 48 hours, anywhere in Bangladesh",
      i2Icon: "returns",
      i2Title: "7-day easy exchange",
      i2Body: "Hassle-free size and style exchanges within 7 days",
      i3Icon: "secure",
      i3Title: "100% genuine craft",
      i3Body: "Authentic handloom, certified by master weavers",
      i4Icon: "support",
      i4Title: "Dedicated helpline 10am-9pm",
      i4Body: "Real humans, every day from 10am to 9pm",
    }),
    s("wedding_shop", {
      advPadY: 40,
      heading: "The Wedding Shop",
      body: "Bridal sarees, groom panjabis and festive finery for the big day and every celebration around it.",
      c1Name: "Bridal Sarees",
      c1Href: "/c/bridal-sarees",
      c2Name: "Groom Panjabis",
      c2Href: "/c/groom-panjabis",
      c3Name: "Festive Gifting",
      c3Href: "/c/festive-gifting",
      buttonLabel: "Shop all wedding",
      buttonHref: "/c/wedding",
    }),
    s("gift_finder", {
      advPadY: 40,
      heading: "Find the perfect gift",
      body: "Thoughtful handcrafted gifts for every occasion — pick who you are shopping for.",
      o1Label: "For Her",
      o1Query: "saree",
      o2Label: "For Him",
      o2Query: "panjabi",
      o3Label: "For Home",
      o3Query: "kantha",
      buttonLabel: "Browse all gifts",
    }),
    s("heritage_story", {
      advPadY: 56,
      eyebrow: "The master weavers",
      headline: "Tangail & Jamdani: A living legacy",
      body: "On wooden pit looms in Tangail and Sonargaon, master weavers carry forward centuries of handloom craft. Every thread is dyed, warped and woven by hand — no two pieces exactly alike.",
      ctaLabel: "Read the story",
      ctaHref: "/blog/master-weavers",
      image: "/api/public/ph/story/master-weavers.svg",
    }),
    s("editorial_banner", {
      advPadY: 48,
      eyebrow: "Festive occasions",
      headline: "Pure silk panjabi & fine muslin",
      subhead: "Natural fibers cut for Bangladeshi celebrations.",
      cta_label: "See the collection",
      cta_url: "/c/eid-festive",
    }),
    s("testimonial_carousel", {
      advPadY: 48,
      testimonials: [
        {
          quote:
            "My Jamdani from Aarong drapes like a dream — the weave is so fine it feels alive. I get compliments every time I wear it.",
          author: "Farhana Ahmed",
        },
        {
          quote:
            "Three generations of our family have worn Aarong panjabis for Eid. The craftsmanship today is as honest as it was decades ago.",
          author: "Tanvir Rahman",
        },
      ],
    }),
    s("rewards_club", {
      advPadY: 48,
      heading: "My Rewards",
      body: "Earn points on every purchase and unlock member-only festive previews.",
      tier1Name: "Silver",
      tier1Points: "0+",
      tier2Name: "Gold",
      tier2Points: "5000+",
      tier3Name: "Platinum",
      tier3Points: "15000+",
      buttonLabel: "Join free",
      buttonHref: "/pages/rewards",
    }),
    s("subbrand_spotlight", {
      advPadY: 48,
      heading: "One craft, many voices",
      subheading: "Aarong family brands",
      b1Name: "Aarong",
      b1Tagline: "Heritage handloom for the whole family",
      b1Href: "/",
      b2Name: "Taaga",
      b2Tagline: "Contemporary fusion for the bold",
      b2Href: "/c/taaga-fusion",
      b3Name: "Herstory",
      b3Tagline: "Women-led craft, modern silhouettes",
      b3Href: "/c/herstory",
      b4Name: "Aarong Earth",
      b4Tagline: "Natural fibers, gentle footprint",
      b4Href: "/c/aarong-earth",
    }),
    s("marquee_strip", {
      speed: "normal",
      direction: "left",
      items: [
        { text: "Handloom" },
        { text: "Fair Trade" },
        { text: "Artisan-Owned" },
        { text: "Natural Dyes" },
        { text: "Zero Plastic" },
      ],
    }),
  ];
}
