apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: framique-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout invalid_header http_502 http_503 http_504"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/upstream-keepalive-connections: "64"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - framique.com
        - "*.framique.com"
      secretName: framique-tls-cert
  rules:
    - host: framique.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: framique-active
                port:
                  number: 80
