/**
 * Generates migration/0003_demo_catalogue.sql — literal INSERT statements for
 * the demo store (P0.5). Theme rows are emitted from the typed presets in
 * src/lib/theme-presets.ts so the installed theme is the real package, not a
 * hand-written approximation.
 *
 *   bun tmpscripts/gen-demo-seed.ts > /dev/null
 */
import { THEME_PRESETS } from "../src/lib/theme-presets";

const MERCHANT = "11111111-1111-4111-8111-111111111111";
const q = (v: string | null) => (v === null ? "null" : `'${v.replace(/'/g, "''")}'`);
const j = (v: unknown) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const uuid = (prefix: string, n: number) =>
  `${prefix.padEnd(8, "0").slice(0, 8)}-0000-4000-8000-${String(n).padStart(12, "0")}`;

const out: string[] = [];
out.push(`-- Demo catalogue for the Frame19 demo store. Idempotent: every insert upserts.
-- Generated by tmpscripts/gen-demo-seed.ts — do not hand-edit.
begin;`);

/* ------------------------------------------------------------- taxonomy --- */
const cats = [
  { slug: "sarees", name: "Sarees", desc: "Handloom and jamdani sarees woven in Bangladesh." },
  { slug: "panjabi", name: "Panjabi", desc: "Everyday and occasion panjabi in cotton and khadi." },
  { slug: "home", name: "Home & living", desc: "Nakshi kantha, ceramics and rugs for the home." },
  { slug: "accessories", name: "Accessories", desc: "Leather, jute and brass finishing pieces." },
];
cats.forEach((c, i) => {
  out.push(`insert into public.categories (id, merchant_id, name, slug, description) values
  (${q(uuid("c1", i + 1))}, ${q(MERCHANT)}, ${q(c.name)}, ${q(c.slug)}, ${q(c.desc)})
  on conflict (id) do update set name = excluded.name, description = excluded.description;`);
});

const brands = [
  { slug: "framique-studio", name: "Framique Studio" },
  { slug: "tangail-looms", name: "Tangail Looms" },
];
brands.forEach((b, i) => {
  out.push(`insert into public.brands (id, merchant_id, name, slug) values
  (${q(uuid("b1", i + 1))}, ${q(MERCHANT)}, ${q(b.name)}, ${q(b.slug)})
  on conflict (id) do update set name = excluded.name;`);
});

/* -------------------------------------------------------------- products --- */
type Seed = { title: string; slug: string; cat: number; price: number; compare: number | null; stock: number; kind: string; desc: string };
const titles: Seed[] = [
  ["Jamdani handloom saree — indigo", "sarees", 1, 8450, 9900, 12],
  ["Jamdani handloom saree — ivory", "sarees", 1, 7950, null, 8],
  ["Tangail cotton saree — rust", "sarees", 1, 3250, 3900, 24],
  ["Tangail cotton saree — moss", "sarees", 1, 3250, null, 18],
  ["Silk saree — deep teal", "sarees", 1, 12400, 14500, 5],
  ["Muslin saree — pearl", "sarees", 1, 15900, null, 3],
  ["Khadi panjabi — charcoal", "panjabi", 2, 2450, 2900, 30],
  ["Khadi panjabi — sand", "panjabi", 2, 2450, null, 26],
  ["Cotton panjabi — white", "panjabi", 2, 1890, 2200, 40],
  ["Embroidered panjabi — midnight", "panjabi", 2, 3600, null, 14],
  ["Linen panjabi — olive", "panjabi", 2, 3150, 3600, 16],
  ["Eid panjabi set — ecru", "panjabi", 2, 4750, 5400, 9],
  ["Nakshi kantha throw — garden", "home", 3, 5600, 6400, 7],
  ["Nakshi kantha cushion pair", "home", 3, 1750, null, 22],
  ["Terracotta serving bowl", "home", 3, 980, 1200, 35],
  ["Stoneware mug set of four", "home", 3, 1650, null, 19],
  ["Jute floor rug — 4x6", "home", 3, 4200, 4900, 6],
  ["Brass table lamp", "home", 3, 3850, null, 11],
  ["Leather wallet — tan", "accessories", 4, 1450, 1800, 44],
  ["Leather satchel — walnut", "accessories", 4, 6200, 6900, 8],
  ["Jute tote — natural", "accessories", 4, 890, null, 60],
  ["Brass bangle pair", "accessories", 4, 1250, 1500, 28],
  ["Silk scarf — sunrise", "accessories", 4, 1950, null, 17],
  ["Gift card — digital", "accessories", 4, 2000, null, 999],
].map(([title, , cat, price, compare, stock], i) => ({
  title: title as string,
  slug: String(title).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60),
  cat: cat as number,
  price: (price as number) * 100,
  compare: compare === null ? null : (compare as number) * 100,
  stock: stock as number,
  kind: i === 23 ? "digital" : "physical",
  desc: `${title}. Made in Bangladesh, photographed in daylight, shipped in recycled packaging.`,
}));

titles.forEach((p, i) => {
  const id = uuid("d1", i + 1);
  const img = `https://picsum.photos/seed/${p.slug}/900/900`;
  out.push(`insert into public.products (id, merchant_id, title, slug, description, image_url, status, product_kind, requires_shipping, category_id, brand_id, tags, search_doc, tax_category) values
  (${q(id)}, ${q(MERCHANT)}, ${q(p.title)}, ${q(p.slug)}, ${q(p.desc)}, ${q(img)}, 'active', ${q(p.kind)}::product_kind, ${p.kind === "physical"}, ${q(uuid("c1", p.cat))}, ${q(uuid("b1", (i % 2) + 1))}, ${q(`{${cats[p.cat - 1]!.slug}}`)}, ${q(`${p.title} ${cats[p.cat - 1]!.name}`)}, 'standard')
  on conflict (id) do update set title = excluded.title, description = excluded.description, image_url = excluded.image_url, status = 'active';`);
  const variants =
    p.kind === "digital"
      ? [{ name: "Digital", sku: `GC-${i + 1}`, price: p.price, stock: p.stock }]
      : [
          { name: "Standard", sku: `FR-${i + 1}-S`, price: p.price, stock: Math.ceil(p.stock / 2) },
          { name: "Large", sku: `FR-${i + 1}-L`, price: p.price + 30000, stock: Math.floor(p.stock / 2) },
        ];
  variants.forEach((v, vi) => {
    out.push(`insert into public.product_variants (id, merchant_id, product_id, name, sku, price_amount_minor_int, compare_at_amount_minor_int, stock_quantity, position, currency_code) values
  (${q(uuid("e1", (i + 1) * 10 + vi))}, ${q(MERCHANT)}, ${q(id)}, ${q(v.name)}, ${q(v.sku)}, ${v.price}, ${p.compare === null ? "null" : p.compare + vi * 30000}, ${v.stock}, ${vi}, 'BDT')
  on conflict (id) do update set price_amount_minor_int = excluded.price_amount_minor_int, stock_quantity = excluded.stock_quantity;`);
  });
});

/* ------------------------------------------------------------ collections -- */
const collections = [
  { slug: "new-arrivals", name: "New arrivals", cat: 0 },
  { slug: "eid-edit", name: "The Eid edit", cat: 2 },
  { slug: "home-textiles", name: "Home textiles", cat: 3 },
  { slug: "everyday-carry", name: "Everyday carry", cat: 4 },
];
collections.forEach((c, i) => {
  const id = uuid("f1", i + 1);
  out.push(`insert into public.collections (id, merchant_id, name, slug, description, image_url, is_published, position) values
  (${q(id)}, ${q(MERCHANT)}, ${q(c.name)}, ${q(c.slug)}, ${q(`${c.name} — a curated selection from the Frame19 demo catalogue.`)}, ${q(`https://picsum.photos/seed/${c.slug}/1200/600`)}, true, ${i})
  on conflict (id) do update set name = excluded.name, is_published = true;`);
  const members = titles
    .map((p, pi) => ({ p, pi }))
    .filter(({ p }, pi) => (c.cat === 0 ? pi % 4 === 0 : p.cat === c.cat))
    .slice(0, 8);
  members.forEach(({ pi }, mi) => {
    out.push(`insert into public.collection_products (id, merchant_id, collection_id, product_id, position) values
  (${q(uuid("a1", (i + 1) * 100 + mi))}, ${q(MERCHANT)}, ${q(id)}, ${q(uuid("d1", pi + 1))}, ${mi})
  on conflict (id) do nothing;`);
  });
});

/* -------------------------------------------------------------- customers -- */
const customers = [
  { id: uuid("11", 1), name: "Ayesha Rahman", email: "ayesha@example.com", phone: "+8801711000001" },
  { id: uuid("11", 2), name: "Tanvir Hasan", email: "tanvir@example.com", phone: "+8801711000002" },
];
customers.forEach((c, i) => {
  out.push(`insert into public.customers (id, merchant_id, auth_uid, name, email, phone, locale) values
  (${q(c.id)}, ${q(MERCHANT)}, ${q(`demo-customer-${i + 1}`)}, ${q(c.name)}, ${q(c.email)}, ${q(c.phone)}, 'bn')
  on conflict (id) do update set name = excluded.name, email = excluded.email;`);
});

/* ----------------------------------------------------------------- orders -- */
const statuses = ["pending", "confirmed", "paid", "shipped", "delivered", "refunded"];
const methods = ["cod", "bkash", "sslcommerz", "nagad", "card", "bkash"];
statuses.forEach((status, i) => {
  const id = uuid("21", i + 1);
  const cust = customers[i % 2]!;
  const productIndex = i * 3 + 1;
  const p = titles[productIndex - 1]!;
  const qty = (i % 3) + 1;
  const sub = p.price * qty;
  const ship = status === "delivered" ? 0 : 6000;
  const vat = Math.round(sub * 0.075);
  out.push(`insert into public.orders (id, merchant_id, customer_id, order_number, status, payment_method, customer_name, customer_email, customer_phone, address_line, city, postcode, subtotal_minor_int, shipping_minor_int, vat_minor_int, vat_rate_basis_points, total_minor_int, currency_code, note) values
  (${q(id)}, ${q(MERCHANT)}, ${q(cust.id)}, ${q(`FR-10${i + 1}`)}, ${q(status)}::order_status, ${q(methods[i]!)}::payment_method, ${q(cust.name)}, ${q(cust.email)}, ${q(cust.phone)}, ${q(`House ${12 + i}, Road ${3 + i}, Dhanmondi`)}, 'Dhaka', '1209', ${sub}, ${ship}, ${vat}, 750, ${sub + ship + vat}, 'BDT', ${q(`Demo order in ${status} state.`)})
  on conflict (id) do update set status = excluded.status, total_minor_int = excluded.total_minor_int;`);
  out.push(`insert into public.order_items (id, merchant_id, order_id, variant_id, product_title, variant_name, sku, quantity, unit_price_minor_int, line_total_minor_int) values
  (${q(uuid("22", i + 1))}, ${q(MERCHANT)}, ${q(id)}, ${q(uuid("e1", productIndex * 10))}, ${q(p.title)}, 'Standard', ${q(`FR-${productIndex}-S`)}, ${qty}, ${p.price}, ${sub})
  on conflict (id) do update set quantity = excluded.quantity;`);
});

/* ---------------------------------------------------------------- reviews -- */
const reviews = [
  { p: 1, rating: 5, title: "Exactly as pictured", body: "The weave is beautiful and it arrived in two days." },
  { p: 1, rating: 4, title: "Lovely, runs long", body: "Colour is true to the photo. Length is generous." },
  { p: 7, rating: 5, title: "Perfect for Eid", body: "Fabric breathes and the stitching is clean." },
  { p: 13, rating: 4, title: "Warm and soft", body: "Kantha stitching is dense; washed well." },
  { p: 19, rating: 5, title: "Great leather", body: "Smells like real leather and holds cards snugly." },
];
reviews.forEach((r, i) => {
  out.push(`insert into public.product_reviews (id, merchant_id, product_id, customer_id, author_name, rating, title, body, status, verified_purchase, published_at) values
  (${q(uuid("31", i + 1))}, ${q(MERCHANT)}, ${q(uuid("d1", r.p))}, ${q(customers[i % 2]!.id)}, ${q(customers[i % 2]!.name)}, ${r.rating}, ${q(r.title)}, ${q(r.body)}, 'published', true, now() - interval '${i + 2} days')
  on conflict (id) do update set status = 'published', published_at = excluded.published_at;`);
});

/* ------------------------------------------------------------------ pages -- */
const pages = [
  { slug: "about", title: "About Frame19", body: "## Woven in Bangladesh\n\nFrame19 works with looms in Tangail and Narayanganj. Every piece is photographed in daylight and shipped in recycled packaging." },
  { slug: "shipping-returns", title: "Shipping & returns", body: "## Delivery\n\nInside Dhaka: 1–2 working days. Outside Dhaka: 2–4 working days.\n\n## Returns\n\nUnworn items can be returned within 7 days." },
  { slug: "contact", title: "Contact us", body: "## Talk to us\n\nCall +8809600000000, 10am–8pm, or email hello@frame19.demo." },
];
pages.forEach((p, i) => {
  out.push(`insert into public.storefront_pages (id, merchant_id, slug, title, excerpt, body_markdown, meta_title, meta_description, is_published, show_in_nav, position, published_at, robots) values
  (${q(uuid("41", i + 1))}, ${q(MERCHANT)}, ${q(p.slug)}, ${q(p.title)}, ${q(p.body.split("\n\n")[1] ?? "")}, ${q(p.body)}, ${q(`${p.title} — Frame19 Demo Store`)}, ${q(`${p.title} at Frame19: handloom sarees, panjabi and home textiles from Bangladesh.`)}, true, true, ${i}, now() - interval '${20 - i} days', 'index,follow')
  on conflict (id) do update set title = excluded.title, body_markdown = excluded.body_markdown, is_published = true;`);
});

/* ------------------------------------------------------------------ posts -- */
const posts = [
  { slug: "how-jamdani-is-woven", title: "How a jamdani saree is woven", excerpt: "Two weavers, one loom, six weeks." },
  { slug: "caring-for-khadi", title: "Caring for khadi", excerpt: "Cold water, shade drying, no wringing." },
  { slug: "eid-gift-guide", title: "The Eid gift guide", excerpt: "Twelve gifts under 5,000 taka." },
  { slug: "meet-the-tangail-looms", title: "Meet the Tangail looms", excerpt: "The families behind our cotton sarees." },
];
posts.forEach((p, i) => {
  out.push(`insert into public.articles (id, merchant_id, slug, title, title_en, excerpt, body, status, tags, meta_title, meta_description, cover_image_url, published_at, robots) values
  (${q(uuid("51", i + 1))}, ${q(MERCHANT)}, ${q(p.slug)}, ${q(p.title)}, ${q(p.title)}, ${q(p.excerpt)}, ${q(`## ${p.title}\n\n${p.excerpt}\n\nThis is demo editorial content for the Frame19 store, written so the blog, feeds and sitemaps have something real to render.`)}, 'published', ${q("{journal}")}, ${q(`${p.title} — Frame19 journal`)}, ${q(p.excerpt)}, ${q(`https://picsum.photos/seed/${p.slug}/1200/630`)}, now() - interval '${10 - i} days', 'index,follow')
  on conflict (id) do update set title = excluded.title, status = 'published', published_at = excluded.published_at;`);
});

/* ------------------------------------------------------------------- menu -- */
out.push(`insert into public.nav_menus (id, merchant_id, name, handle, locations) values
  (${q(uuid("61", 1))}, ${q(MERCHANT)}, 'Main menu', 'main-menu', '{header}')
  on conflict (id) do update set name = excluded.name;`);
const menuItems = [
  { label: "Shop", url: "/search" },
  { label: "New arrivals", url: "/c/new-arrivals" },
  { label: "The Eid edit", url: "/c/eid-edit" },
  { label: "Journal", url: "/blog" },
  { label: "About", url: "/pages/about" },
  { label: "Contact", url: "/pages/contact" },
];
menuItems.forEach((m, i) => {
  out.push(`insert into public.nav_menu_items (id, menu_id, label, url, kind, position) values
  (${q(uuid("62", i + 1))}, ${q(uuid("61", 1))}, ${q(m.label)}, ${q(m.url)}, 'custom', ${i})
  on conflict (id) do update set label = excluded.label, url = excluded.url;`);
});

/* --------------------------------------------------------- payment rails --- */
["bkash", "sslcommerz"].forEach((provider, i) => {
  out.push(`insert into public.gateway_accounts (id, merchant_id, provider, active, sandbox, webhook_secret) values
  (${q(uuid("71", i + 1))}, ${q(MERCHANT)}, ${q(provider)}, true, true, ${q(`demo-sandbox-secret-${provider}`)})
  on conflict (id) do update set active = true, sandbox = true;`);
});

/* ------------------------------------------------------------- vat rates --- */
const year = new Date().getUTCFullYear();
[year - 1, year, year + 1].forEach((y, i) => {
  out.push(`insert into public.vat_rates (id, country_code, category, rate_basis_points, effective_year) values
  (${q(uuid("81", i + 1))}, 'BD', 'standard', 750, ${y})
  on conflict (id) do update set rate_basis_points = excluded.rate_basis_points;`);
});

/* ----------------------------------------------------------------- themes -- */
THEME_PRESETS.forEach((preset, i) => {
  out.push(`insert into public.theme_registry (key, name_en, name_bn, summary_en, summary_bn, category, version, preset, active, sort_order) values
  (${q(preset.key)}, ${q(preset.nameEn ?? preset.key)}, ${q(preset.nameBn ?? preset.key)}, ${q(preset.summaryEn ?? "")}, ${q(preset.summaryBn ?? "")}, ${q(preset.category ?? "general")}, ${q(preset.version ?? "1.0.0")}, ${j({ tokens: preset.tokens, templates: preset.templates })}, true, ${i})
  on conflict (key) do update set name_en = excluded.name_en, preset = excluded.preset, active = true, sort_order = excluded.sort_order;`);
});

const active = THEME_PRESETS.find((p) => p.key === "modern") ?? THEME_PRESETS[0]!;
const themeId = uuid("91", 1);
const versionId = uuid("92", 1);
out.push(`insert into public.store_themes (id, merchant_id, name, is_active, source_listing_slug, source_version, author, description, tags, installed_at) values
  (${q(themeId)}, ${q(MERCHANT)}, ${q(active.nameEn ?? active.key)}, true, ${q(active.key)}, ${q(active.version ?? "1.0.0")}, 'Framique', ${q(active.summaryEn ?? "")}, ${q("{official}")}, now())
  on conflict (id) do update set is_active = true;`);
out.push(`insert into public.theme_versions (id, merchant_id, theme_id, version, status, label, tokens, templates, ast, source_registry_key, source_registry_version, published_at) values
  (${q(versionId)}, ${q(MERCHANT)}, ${q(themeId)}, 1, 'published', 'Installed from the official catalogue', ${j(active.tokens)}, ${j(active.templates)}, ${j((active.templates as Record<string, unknown>)["index"] ?? {})}, ${q(active.key)}, ${q(active.version ?? "1.0.0")}, now())
  on conflict (id) do update set status = 'published', tokens = excluded.tokens, templates = excluded.templates;`);

out.push(`update public.store_themes set published_version_id = ${q(versionId)} where id = ${q(themeId)};`);
out.push(`update public.merchant_settings set cod_enabled = true, mfs_enabled = true,
  shipping_flat_minor_int = 6000, free_shipping_threshold_minor_int = 500000,
  cod_surcharge_minor_int = 2000, prices_include_vat = false, low_stock_threshold = 5,
  support_email = 'hello@frame19.demo', support_phone = '+8809600000000',
  tagline = 'Handloom sarees, panjabi and home textiles, woven in Bangladesh'
  where merchant_id = ${q(MERCHANT)};`);
out.push("commit;");

await Bun.write("migration/0003_demo_catalogue.sql", out.join("\n") + "\n");
console.log(`wrote migration/0003_demo_catalogue.sql (${out.length} statements)`);
