#!/usr/bin/env node
/**
 * Generate the self-hosted scheduler crontab from src/lib/cron-registry.ts.
 *
 * Why generated: the registry is already the single owner of every job's key,
 * schedule, timeout and alert threshold. A hand-written crontab drifts from it
 * silently — that is exactly how "cron executor still TBD" happened for the
 * tenant purge window, where the endpoint existed and nothing ever called it.
 *
 * Two modes:
 *   `--check`  compare the generated output with ops/cron/crontab and exit 1 on
 *              drift. Wired into `bun run gates` so a new job cannot land
 *              without a schedule.
 *   (default)  write ops/cron/crontab.
 *
 * The emitted lines call the app's own `/api/public/cron/<key>` endpoints with
 * the bearer secret, so all the operational behaviour (lease, ledger, timeout,
 * alerting) stays in one place instead of in shell.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const REGISTRY = "src/lib/cron-registry.ts";
const OUT = "ops/cron/crontab";

const source = readFileSync(REGISTRY, "utf8");

/**
 * Parse the registry without importing it: the module pulls in the server
 * observability registry, which is not loadable from a plain node script.
 * The shape is fixed and contract-tested, so a field-wise regex is honest here.
 */
function parseJobs(src) {
  const jobs = [];
  const blocks = src.split(/\n\s*\{\s*\n/).slice(1);
  for (const block of blocks) {
    const key = block.match(/key:\s*"([^"]+)"/)?.[1];
    const schedule = block.match(/schedule:\s*"([^"]+)"/)?.[1];
    const timeoutMs = Number(block.match(/timeoutMs:\s*([\d_]+)/)?.[1]?.replace(/_/g, "") ?? 0);
    const label = block.match(/label:\s*"([^"]+)"/)?.[1] ?? key;
    if (!key || !schedule) continue;
    jobs.push({ key, schedule, timeoutMs, label });
  }
  return jobs;
}

const jobs = parseJobs(source);
if (jobs.length === 0) {
  console.error("gen-crontab: parsed zero jobs from the registry — refusing to write an empty schedule");
  process.exit(1);
}

const fiveFields = /^(\S+\s+){4}\S+$/;
const bad = jobs.filter((j) => !fiveFields.test(j.schedule));
if (bad.length) {
  console.error(`gen-crontab: invalid cron expressions: ${bad.map((j) => `${j.key}="${j.schedule}"`).join(", ")}`);
  process.exit(1);
}

const lines = [
  "# GENERATED by scripts/gen-crontab.mjs — do not edit by hand.",
  "# Source of truth: src/lib/cron-registry.ts. Regenerate with `bun run cron:generate`.",
  "#",
  "# Runs inside the supercronic container (ops/docker-compose.cron.yml), which",
  "# reads APP_INTERNAL_URL and BILLING_CRON_SECRET from ops/.env.",
  "# Each job answers 200 (ran), 409 (another scheduler holds the lease) or 5xx;",
  "# supercronic logs the status line and Promtail ships it to Loki.",
  "SHELL=/bin/sh",
  "",
];

for (const job of jobs) {
  // curl budget = the job's own wall-clock budget plus a small connect margin,
  // so the scheduler never outlives the request it is waiting on.
  const maxTime = Math.max(10, Math.ceil((job.timeoutMs || 30_000) / 1000) + 5);
  lines.push(`# ${job.label}`);
  lines.push(
    `${job.schedule} curl -sS -X POST -m ${maxTime} --retry 1 --retry-delay 5 ` +
      `-H "authorization: Bearer $BILLING_CRON_SECRET" ` +
      `-H "x-cron-trigger: supercronic" ` +
      `-o /dev/null -w 'cron ${job.key} status=%{http_code} t=%{time_total}s\\n' ` +
      `"$APP_INTERNAL_URL/api/public/cron/${job.key}"`,
  );
  lines.push("");
}

const output = `${lines.join("\n").trimEnd()}\n`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    console.error(`gen-crontab: ${OUT} is missing — run \`bun run cron:generate\``);
    process.exit(1);
  }
  if (current !== output) {
    console.error(`gen-crontab: ${OUT} is stale (${jobs.length} jobs in the registry) — run \`bun run cron:generate\``);
    process.exit(1);
  }
  console.log(`gen-crontab: ok (${jobs.length} jobs scheduled)`);
  process.exit(0);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, output);
console.log(`gen-crontab: wrote ${OUT} (${jobs.length} jobs)`);
