/**
 * Generates the theme_registry seed migration from code presets.
 *
 * `public.theme_registry` is generated from `src/lib/theme-presets.ts` so
 * SQL and runtime can never drift (see header comment there). The import
 * RPCs (supabase/migrations/20260920_import_rpcs.sql) read blueprints
 * from this table — an empty registry makes every demo import a noop.
 *
 * Curated offer (Sept 2026): seed Supershop + Clothing Heritage only.
 *
 * Usage: bun scripts/seed-theme-registry.ts > supabase/migrations/<ts>_theme_registry_seed.sql
 * Review the output before applying; apply live as supabase_admin.
 *
 * RETIRED 2026-09-23 (theme purge, Task 5): the theming system is removed and
 * 20260923_retire_themes.sql closes the write surface. This script now refuses
 * to generate seed migrations so no future theme rows can be (re)introduced.
 */
throw new Error(
  "theme system retired 2026-09-23: seed-theme-registry is disabled. " +
    "See supabase/migrations/20260923_retire_themes.sql.",
);

import { THEME_PRESETS } from "../src/lib/theme-presets";

const KEYS = ["supershop", "clothing-heritage"];

function sqlString(v: string): string {
  return `'${v.replace(/'/g, "''")}'`;
}

const lines: string[] = [
  "-- Generated by scripts/seed-theme-registry.ts — do not hand-edit.",
  "-- Seeds public.theme_registry from code presets (curated offer).",
  "-- Idempotent: INSERT ... ON CONFLICT (key) DO UPDATE.",
  "",
];
for (const key of KEYS) {
  const p = THEME_PRESETS.find((t) => t.key === key);
  if (!p) throw new Error(`preset missing in code: ${key}`);
  const preset = JSON.stringify({ tokens: p.tokens, templates: p.templates });
  lines.push(
    `INSERT INTO public.theme_registry (key, name_en, name_bn, summary_en, summary_bn, category, version, preset, active, sort_order) VALUES (` +
      [
        sqlString(p.key),
        sqlString(p.nameEn),
        sqlString(p.nameBn),
        sqlString(p.summaryEn),
        sqlString(p.summaryBn),
        sqlString(p.category),
        sqlString(p.version),
        sqlString(preset),
        "true",
        String(p.sortOrder),
      ].join(", ") +
      `) ON CONFLICT (key) DO UPDATE SET ` +
      `name_en = EXCLUDED.name_en, name_bn = EXCLUDED.name_bn, ` +
      `summary_en = EXCLUDED.summary_en, summary_bn = EXCLUDED.summary_bn, ` +
      `category = EXCLUDED.category, version = EXCLUDED.version, ` +
      `preset = EXCLUDED.preset, active = true, ` +
      `sort_order = EXCLUDED.sort_order, updated_at = now();`,
  );
}
lines.push("");
console.log(lines.join("\n"));
