// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request
        ? input.headers
        : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) =>
        headers.set(key, value),
      );
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

type CachedClaims = {
  claims: Record<string, unknown> & { sub: string; exp?: number };
  expiresAt: number;
};

const claimsCache = new Map<string, CachedClaims>();
const CLAIMS_CACHE_MAX = 500;
const CLAIMS_CACHE_TTL_MS = 60_000; // 60 seconds

function getCachedClaims(token: string): (Record<string, unknown> & { sub: string }) | null {
  const entry = claimsCache.get(token);
  if (!entry) return null;
  if (Date.now() > entry.expiresAt) {
    claimsCache.delete(token);
    return null;
  }
  return entry.claims;
}

function setCachedClaims(
  token: string,
  claims: Record<string, unknown> & { sub: string; exp?: number },
) {
  if (claimsCache.size >= CLAIMS_CACHE_MAX) {
    const firstKeys = claimsCache.keys();
    for (let i = 0; i < 50; i++) {
      const k = firstKeys.next().value;
      if (!k) break;
      claimsCache.delete(k);
    }
  }
  let ttlMs = CLAIMS_CACHE_TTL_MS;
  if (claims.exp && typeof claims.exp === "number") {
    const msUntilExp = claims.exp * 1000 - Date.now();
    if (msUntilExp < ttlMs) {
      ttlMs = Math.max(0, msUntilExp);
    }
  }
  claimsCache.set(token, {
    claims,
    expiresAt: Date.now() + ttlMs,
  });
}

export const requireSupabaseAuth = createMiddleware({
  type: "function",
}).server(async ({ next }) => {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please set SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const request = getRequest();

  if (!request?.headers) {
    throw new Error("Unauthorized: No request headers available");
  }

  const authHeader = request.headers.get("authorization");

  if (!authHeader) {
    throw new Error("Unauthorized: No authorization header provided");
  }

  if (!authHeader.startsWith("Bearer ")) {
    throw new Error("Unauthorized: Only Bearer tokens are supported");
  }

  const token = authHeader.replace("Bearer ", "");
  if (!token) {
    throw new Error("Unauthorized: No token provided");
  }

  if (token.split(".").length !== 3) {
    throw new Error("Unauthorized: Invalid token");
  }

  const supabase = createClient<Database>(
    SUPABASE_URL!,
    SUPABASE_PUBLISHABLE_KEY!,
    {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    },
  );

  let claims = getCachedClaims(token);
  if (!claims) {
    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    claims = data.claims as Record<string, unknown> & { sub: string };
    setCachedClaims(token, claims);
  }

  return next({
    context: {
      supabase,
      userId: claims.sub,
      claims,
    },
  });
});

